### ISSUE TITLE
[CURATOR-482] zookeeper exists waiting forever 

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1002]
<p>exists waiting forever</p>

<p>server version 3.4.6</p>

<p>zookeeper cient version 3.4.8 </p>

<p>curator version curator-client-2.12</p>

<p>because of the exists waiting forever, cause the cutator TreeCache thread block  </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">// code placeholder
</span><span class="code-quote">"ZZBOOK_UPDATE_JDID_JOB2_QuartzSchedulerThread"</span> #781 prio=5 os_prio=0 tid=0x00007f1a7611e800 nid=0x7661 in <span class="code-object">Object</span>.wait() [0x00007f1936cee000]
 java.lang.<span class="code-object">Thread</span>.State: WAITING (on object monitor)
 at java.lang.<span class="code-object">Object</span>.wait(Native Method)
 at java.lang.<span class="code-object">Object</span>.wait(<span class="code-object">Object</span>.java:502)
 at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1406)
 - locked <0x00000000a6d2a5c8> (a org.apache.zookeeper.ClientCnxn$Packet)
 at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1097)
 at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:237)
 at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
 at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
 at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:223)
 at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:216)
 at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:175)
 at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:32)
 at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:210)
 at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.isJobNodeExisted(JobNodeStorage.java:66)
 at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.createJobNodeIfNeeded(JobNodeStorage.java:107)
 at com.dangdang.ddframe.job.lite.internal.execution.ExecutionService.setMisfire(ExecutionService.java:189)
 at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:47)
 at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1905)
 at org.quartz.core.SchedulerSignalerImpl.notifyTriggerListenersMisfired(SchedulerSignalerImpl.java:74)
 at org.quartz.simpl.RAMJobStore.applyMisfire(RAMJobStore.java:1354)
 at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1412)
 - locked <0x00000000c4c9fb10> (a java.lang.<span class="code-object">Object</span>)
 at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)

<span class="code-quote">"ZZBOOK_UPDATE_JDID_JOB2_Worker-1"</span> #780 prio=5 os_prio=0 tid=0x00007f1a7611d000 nid=0x7660 in <span class="code-object">Object</span>.wait() [0x00007f1936ef0000]
 java.lang.<span class="code-object">Thread</span>.State: TIMED_WAITING (on object monitor)
 at java.lang.<span class="code-object">Object</span>.wait(Native Method)
 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
 - locked <0x00000000c4c228c8> (a java.lang.<span class="code-object">Object</span>)

<span class="code-quote">"Curator-TreeCache-77"</span> #779 daemon prio=5 os_prio=0 tid=0x00007f19a4091000 nid=0x765f waiting <span class="code-keyword">for</span> monitor entry [0x00007f1936def000]
 java.lang.<span class="code-object">Thread</span>.State: BLOCKED (on object monitor)
 at org.quartz.simpl.RAMJobStore.storeTrigger(RAMJobStore.java:413)
 - waiting to lock <0x00000000c4c9fb10> (a java.lang.<span class="code-object">Object</span>)
 at org.quartz.core.QuartzScheduler.triggerJob(QuartzScheduler.java:1187)
 at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:341)
 at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:331)
 at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.triggerJob(JobScheduleController.java:153)
 at com.dangdang.ddframe.job.lite.internal.server.JobOperationListenerManager$JobTriggerStatusJobListener.dataChanged(JobOperationListenerManager.java:103)
 at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:43)
 at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:741)
 at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:735)
 at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
 at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
 at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
 at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:734)
 at org.apache.curator.framework.recipes.cache.TreeCache.access$1700(TreeCache.java:71)
 at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:852)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)

<span class="code-quote">"main-EventThread"</span> #236 daemon prio=5 os_prio=0 tid=0x00007f1a7546a800 nid=0x74bf waiting on condition [0x00007f194e96e000]
 java.lang.<span class="code-object">Thread</span>.State: WAITING (parking)
 at sun.misc.Unsafe.park(Native Method)
 - parking to wait <span class="code-keyword">for</span> <0x00000000c24ca218> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
 at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:501)

<span class="code-quote">"main-SendThread(tjtx-84-168.58os.org:2181)"</span> #235 daemon prio=5 os_prio=0 tid=0x00007f1a7596c000 nid=0x74be runnable [0x00007f194ea6f000]
 java.lang.<span class="code-object">Thread</span>.State: RUNNABLE
 at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
 at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
 at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 - locked <0x00000000c1da74d0> (a sun.nio.ch.Util$2)
 - locked <0x00000000c1da75a8> (a java.util.Collections$UnmodifiableSet)
 - locked <0x00000000c1ace0a0> (a sun.nio.ch.EPollSelectorImpl)
 at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:349)
 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
</pre>
</div></div>
<p> </p>

---
<details><summary><i>Originally reported by <a title="zhaoziyan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaoziyan">zhaoziyan</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-482" target="_blank">zookeeper exists waiting forever </a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2018-12-05T09:34:44+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaoziyan" class="user-hover" rel="zhaoziyan">zhaoziyan</a>, Would you be able to provide a unit test that can reliably reproduce this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaoziyan">zhaoziyan</a>:</i>
<p>sorry , I have found is not the curator have problem , but A another thread call client in a loop .</p>

**Comment by suoyunqing** [comment]
@jira-importer Hello, I have the similar issue. Could you give more details about "A another thread call client in a loop"?
