### ISSUE TITLE
[CURATOR-488] NoSuchMethodError calling client close() in 3.4 compatibility mode 

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1008]
<p>Affected version is 4.0.2-SNAPSHOT. Version 4.0.1 is not affected</p>

<p>When closing client it is calling zooKeeper.close(waitForShutdownTimeoutMs) This method is only supported starting from ZK 3.5. So when running in compatibility mode with ZK 3.4.x it throws NoSuchMethodError.  So for ZK 3.4.x need to use  zooKeeper.close() with no arguments. </p>

<p> </p>

<p>To reproduce:</p>

<p>Start ZK 3.4 server locally. </p>

<p>In pom.xml add dependency on zookeeper 3.4.13 and exclude default dependency (on 3.5). Full pom.xml is attached. </p>

<p> </p>

<p>Run this code snippet: </p>

<p>public class CloseTest {<br/>
   public static void main(String[] args) throws Exception</p>

{     CuratorFramework client = CuratorFrameworkFactory.newClient("localhost:2181", new  ExponentialBackoffRetry(1000, 3));     client.start();     client.close();   }

<p>}</p>

<p> </p>

<p>It will throw exception: </p>

<p>Exception in thread "main" java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.close(I)Z<br/>
 at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:158)<br/>
 at org.apache.curator.HandleHolder.closeAndClear(HandleHolder.java:78)<br/>
 at org.apache.curator.ConnectionState.close(ConnectionState.java:125)<br/>
 at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:266)<br/>
 at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:249)<br/>
 at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:388)<br/>
 at leader.CloseTest.main(CloseTest.java:11)</p>

---
<details><summary><i>Originally reported by <a title="Boris Dainson" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=borisd">borisd</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-488" target="_blank">NoSuchMethodError calling client close() in 3.4 compatibility mode </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-12-04T22:10:14+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>We pushed a change yesterday as part of <a href="https://issues.apache.org/jira/browse/CURATOR-472" title="Test-only code started to be called in prod" class="issue-link" data-issue-key="CURATOR-472"><del>CURATOR-472</del></a> that should fix this. When did you try this? Can you try again with a fresh pull?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=borisd">borisd</a>:</i>
<p>You're right. It is fixed now. Closing.</p>

<p>Thank you</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=borisd">borisd</a>:</i>
<p>Fixed now, see comments</p>
