### ISSUE TITLE
[CURATOR-507] PERSISTENT NODE ISSUE

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1027]
<p>Hi there,</p>

<p>I am using Apache Curator 4.1.0 with Zk 3.4.10 (Open JDK 1.8)</p>

<p>openjdk version "1.8.0_191"</p>

<p>I am PersistentNode recipe and I am receiving this exception</p>

<p> </p>

<p>java.lang.IllegalStateException: initial create has not been processed. Call waitForInitialCreate() to ensure.<br/>
 at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)<br/>
 at org.apache.curator.framework.recipes.nodes.PersistentNode.setData(PersistentNode.java:392)<br/>
 at com.cheva.udr.sm.RemoteReporter.reportToRemote(RemoteReporter.java:67)<br/>
 at com.cheva.udr.sm.RemoteReporter.lambda$2(RemoteReporter.java:84)<br/>
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>
 at java.lang.Thread.run(Thread.java:748)</p>

<p> </p>

<p>My class RemoteReporter.java (assumes that PersistentNode is thread safe)</p>

<p>// The class is final, and the attribute is private final so allow safe publication<br/>
private final Persistent pn;</p>

<p>Constrcutor() </p>
{
...
PersistentNode pn = new PersistentNode(cf, CreateMode.EPHEMERAL, false, path, dataToReport());
}

<p>// Class has also an start method<br/>
start() </p>
{
...
79 pn.start();
...
// Create new thread and execute the follwoing code
84 pn.waitForInitialCreate(1000, TimeUnit.DAYS);
85 pn.setData("XXx");
86 statusCache.getListenable().addListener(listener);
}

<p>I was checking the PersistentNode code and the excepction happens because nodePath.get()==null variable. I am not 100% sure if the problem is in my code or in the recipe...</p>

<ul class="alternate" type="square">
	<li>My code is using the waitForinitial as suggested</li>
	<li>The recipe uses a CountDownLatch, but there are 2 different paths for the latch to be countDown (via initalisationComplete() method), and I am not sure that one of them assures that nodePath.get() != null</li>
</ul>

<p>In this code snippet, you can see that the latch is countDown, but I am not sure that nodePath.set(whatever) is called, so I guess there could be a race condition</p>

<p>private final BackgroundCallback setDataCallback = new BackgroundCallback()<br/>
 {</p>

<p>@Override<br/>
 public void processResult(CuratorFramework dummy, CuratorEvent event)<br/>
 throws Exception<br/>
 {<br/>
 //If the result is ok then initialisation is complete (if we're still initialising)<br/>
 //Don't retry on other errors as the only recoverable cases will be connection loss<br/>
 //and the node not existing, both of which are already handled by other watches.<br/>
 if ( event.getResultCode() == KeeperException.Code.OK.intValue() )</p>
 {
 //Update is ok, mark initialisation as complete if required.
 initialisationComplete();
 }
<p> else if ( event.getResultCode() == KeeperException.Code.NOAUTH.intValue() )<br/>
 {<br/>
 log.warn("Client does not have authorisation to write node at path {}", event.getPath());<br/>
 authFailure.set(true);<br/>
 }<br/>
 }<br/>
 };</p>

<p>Thanks in adavance for the help,</p>

<p>Evaristo</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Chevaris" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-507" target="_blank">PERSISTENT NODE ISSUE</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2020-05-06T09:06:49+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I don't think it's a race condition. The two paths for initialisationComplete() to be called seem mutually exclusive to me, but maybe I'm missing something.</p>

<p>Could you write a small unit test to reproduce the problem? It's difficult to work out what's going on from the code snippets.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Thanks Cameron. I am working with a unit test trying to reproduce the issue. So far, I have not been successful. Give me a couple of days, and if I cannot provide a unit test, then I will close the ticket. Is that OK?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Yep, that's fine.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>I realized that I forgot to answer to this issue. I was not able to reproduce anymore. I guess it was an error on my application.</p>

<p>I am closing the issue.</p>

<p> </p>
