### ISSUE TITLE
[CURATOR-509] Incompatible with Java 11

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1029]
<p>In java 11, this exception is thrown:</p>
<blockquote><p>java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/apache/curator/framework/CuratorFramework. Method lambda$postSafeNotify$0(Ljava/lang/Object;)V at index 99 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef</p>

<p>at org.apache.curator.framework.CuratorFramework.postSafeNotify(CuratorFramework.java:344)</p>

<p>at org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2$1.process(InterProcessSemaphoreV2.java:90)</p>

<p>at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:77)</p>

<p>at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:533)</p>

<p>at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)</p></blockquote>
<p>As I understood it, this is because there is a lambda in a default interface method and earlier versions of java 8 incorrectly compiled the method reference as a Method instead of an Interface method. Compiling with the latest java 8 compiler (8.0.172) seems to correctly compile the classin a way that works in java 8 and 11 (did not verify 9 and 10 but I suspect they behave like 11)</p>

---
<details><summary><i>Originally reported by <a title="Brian Vella" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianvell">brianvell</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-509" target="_blank">Incompatible with Java 11</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2019-03-01T16:44:45+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>So is the fix to build with the latest Java 8 JDK? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianvell">brianvell</a>:</i>
<p>Yes, it seems so. I diassembled the interface org/apache/curator/framework/CuratorFramework from the 4.1.0 artifact in maven central and from a local build of the same tag.</p>

<p>This is the line of interest from the maven central one (built with 1.8.0_101):</p>

<p>InvokeDynamic invokeStatic Method java/lang/invoke/LambdaMetafactory metafactory (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; MethodType ()V MethodHandle invokeStatic <b>Method</b> org/apache/curator/framework/CuratorFramework lambda$postSafeNotify$0 (Ljava/lang/Object;)V MethodType ()V : run (Ljava/lang/Object;)Ljava/lang/Runnable; </p>

<p>And the same line from the locally built one (built with 1.0.8_172):</p>

<p>InvokeDynamic invokeStatic Method java/lang/invoke/LambdaMetafactory metafactory (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; MethodType ()V MethodHandle invokeStatic <b>InterfaceMethod</b> org/apache/curator/framework/CuratorFramework lambda$postSafeNotify$0 (Ljava/lang/Object;)V MethodType ()V : run (Ljava/lang/Object;)Ljava/lang/Runnable; </p>

<p>Thus, the issue should be resolved if a new version is built with 1.0.8_172 or later. Let me know if you require further information.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I've updated my local version of Java to 1.8.0_201. All other committers (attn: <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a>) should do the same. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianvell">brianvell</a>:</i>
<p>Excellent. Thank you for the prompt consideration</p>
