### ISSUE TITLE
[CURATOR-520] NoSuchMethod Exception on curator.close() in 3.4 compatibility mode

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1040]
<p>Running in 3.4 compatibility mode, Curator improperly appears to attempt to call the <em>close(I)</em> method which does not exist on the 3.4 version of the Zookeeper API: </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Uncaught error from thread [timeline-manager-akka.actor.<span class="code-keyword">default</span>-dispatcher-4]: org.apache.zookeeper.ZooKeeper.close(I)Z, shutting down JVM since <span class="code-quote">'akka.jvm-exit-on-fatal-error'</span> is enabled <span class="code-keyword">for</span> ActorSystem[timeline-manager]
java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.close(I)Z
at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:164)
at org.apache.curator.HandleHolder.closeAndClear(HandleHolder.java:78)
at org.apache.curator.ConnectionState.close(ConnectionState.java:125)
at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:266)
at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:249)

</pre>
</div></div>
<p>This results in a failure to reconnect to Zookeeper when the service is restarted (presumably because the old connection was never properly released). </p>

---
<details><summary><i>Originally reported by <a title="Andrew Polack" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alpsmac">alpsmac</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-520" target="_blank">NoSuchMethod Exception on curator.close() in 3.4 compatibility mode</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2019-05-21T21:35:10+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I suspect you are calling <tt>waitForShutdownTimeoutMs</tt> in <tt>CuratorFrameworkFactory</tt>. This is not supported for ZooKeeper 3.4.x. As we document here - <a href="http://curator.apache.org/zk-compatibility.html" class="external-link" target="_blank" rel="nofollow noopener">http://curator.apache.org/zk-compatibility.html</a> - regarding 3.4.x compatibility, <tt>It is up to your application code to "do the right thing" and not use these features.</tt></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alpsmac">alpsmac</a>:</i>
<p>Bingo - so... error between user and keyboard - got it! </p>

<p>I did read the docs about "doing the right thing" and avoiding new features but I didn't realize that waiting for shutdown was a new 3.5.x feature.</p>

<p>Retesting without the <em>waitForShutdownTimeoutMs(...)</em> on the Curator instance builder solved the problem. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Maybe a check in the <tt>waitForShutdownTimeoutMs()</tt> method on 3.4 would be a good idea. I'd approve a PR with that.</p>
