### ISSUE TITLE
[CURATOR-535] TestServer random port selection has a race condition

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1054]
<p>When using one of the constructors for org.apache.curator.test.TestingServer that doesn't take a port number, the org.apache.curator.test.InstanceSpec that is constructed will chose random available ports to use. However, InstanceSpec only binds those ports during construction and then unbinds them so that they can be used when TestingServer.start() is called.</p>

<p>This disconnect between port selection creates a race condition where some other process (or thread) could bind the port before TestingServer is started.</p>

<p>I've seen this very rarely in our integration test suite that spins up and tears down TestingServer many times. I've attached a simple class for reproducing the issue. If you run it in an environment with log4j loaded and the attached log4j.properties, you should see output like the following (though it sometimes takes more iterations):</p>

<p><tt>completed iteration: 0</tt><br/>
 <tt>completed iteration: 500</tt><br/>
 <tt>2019-08-02 09:47:06 ERROR TestingZooKeeperServer:162 - From testing server (random state: false) for instance: InstanceSpec{dataDirectory=/tmp/1564753624792-1, port=34707, electionPort=33621, quorumPort=45995, deleteDataDirectoryOnClose=true, serverId=1286, tickTime=-1, maxClientCnxns=-1, customProperties={}, hostname=127.0.0.1} org.apache.curator.test.InstanceSpec@59c43d10</tt><br/>
 <tt>java.net.BindException: Address already in use</tt><br/>
 <tt>    at sun.nio.ch.Net.bind0(Native Method)</tt><br/>
 <tt>    at sun.nio.ch.Net.bind(Net.java:433)</tt><br/>
 <tt>    at sun.nio.ch.Net.bind(Net.java:425)</tt><br/>
 <tt>    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)</tt><br/>
 <tt>    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)</tt><br/>
 <tt>    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)</tt><br/>
 <tt>    at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:687)</tt><br/>
 <tt>    at org.apache.zookeeper.server.ServerCnxnFactory.configure(ServerCnxnFactory.java:76)</tt><br/>
 <tt>    at org.apache.curator.test.TestingZooKeeperMain.internalRunFromConfig(TestingZooKeeperMain.java:239)</tt><br/>
 <tt>    at org.apache.curator.test.TestingZooKeeperMain.runFromConfig(TestingZooKeeperMain.java:132)</tt><br/>
 <tt>    at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:158)</tt><br/>
 <tt>    at java.lang.Thread.run(Thread.java:748)</tt><br/>
 <tt>java.lang.IllegalStateException: Timed out waiting for watch removal</tt><br/>
 <tt>    at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:146)</tt><br/>
 <tt>    at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:167)</tt><br/>
 <tt>    at org.apache.curator.test.TestingServer.start(TestingServer.java:148)</tt><br/>
 <tt>    at BugReproducer.main(BugReproducer.java:15)</tt></p>

---
<details><summary><i>Originally reported by <a title="Laverne Schrock" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thevern">thevern</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-535" target="_blank">TestServer random port selection has a race condition</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Enrico Olivelli" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-02-21T13:29:51+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul8263">paul8263</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> ,</p>

<p>Have you already solved this issue? Recently I encountered the same problem in Flink tests.</p>

<p>If your were not available, I would like to take a look at this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Please go ahead</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul8263">paul8263</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> and <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thevern" class="user-hover" rel="thevern">Laverne Schrock</a> ,</p>

<p>How about a solution which allows port, quorumPort and electionPort to be lazy initialized with random unused port if not specified in InstanceSpec. Thus, the available port will be allocated when TestingServer actually starts. The race condition among threads can be alleviated. I am currently working on this solution.</p>

<p>For multiple process running TestingServer, I suggest we use an external file lock. The implementation may be cumbersome for TestingServer so it would be better not to integrate it with TestingServer.</p>

<p>Correct me if I am wrong. Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul8263">paul8263</a>:</i>
<p>Could anyone assign this to me?</p>
