### ISSUE TITLE
[CURATOR-561] Race condition preventing reconnection

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1080]
<p>Heavy GC caused several rounds of suspend, lost, reconnected - as you'd expect. But eventually it failed to reconnect, even though ZK was up the entire time. My thread waited on acquireLock until the retry period was up. I believe I've tracked this down to a race condition between the Curator thread which calls ZookKeeperTestable#injectSessionExpiration to post the expiry and death events and the Zookeeper SendThread which posts the same.</p>

<p> </p>

<p>The EventThread is meant to receive the expiry event first so it can set up its replacement, then it receives the death event making it shut down.</p>

<p>The race condition allows these two events to be received in the wrong order so the EventThread shuts down before a replacement can be set up.</p>

<p> </p>

<p>The "Curator-ConnectionStateManager" thread calls injectSessionExpiration which calls EventThread#queueEvent. It goes as far as my comment in the next code snippit, sets the status and let's say it pauses here, for whatever reason.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">private</span> void queueEvent(WatchedEvent event,
Set<Watcher> materializedWatchers) {
    <span class="code-keyword">if</span> (event.getType() == EventType.None
    && sessionState == event.getState()) {
<span class="code-keyword">return</span>;
    }
    sessionState = event.getState();   <span class="code-comment">// The curator thread sets the status here
</span>  <span class="code-comment">// It then goes onto send the expiry event, but <span class="code-keyword">for</span> now it's here..the event has not yet been sent</span></pre>
</div></div>
<p> </p>

<p>The SendThread then goes into the same method with its Expiry message, but the state has already been set to expired by the curator thread so it returns without sending the expiry message. It then sends the event of death:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-comment">// from ClientCnxn#onConnected
</span>eventThread.queueEvent(<span class="code-keyword">new</span> WatchedEvent(
Watcher.Event.EventType.None,
Watcher.Event.KeeperState.Expired, <span class="code-keyword">null</span>));
eventThread.queueEventOfDeath(); </pre>
</div></div>
<p> </p>

<p>The EventThread receives this event of death and shuts down. The curator thread then continues and sends the original expiry message but it's now too late. With no EventThread created it remains in suspended state with any operations just retrying until they give up.</p>

<p> </p>

<p>I find it difficult to explan race conditions, but hopefully that made sense. I can recreate the issue in Intellij using Suspend-All break points to cause the session expiry and Suspend-Thread break points to order the threads in the correct way:</p>

<p> </p>

<p>Run the following and put a suspend-all break point at the System.out</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">package</span> com.gebatech.curator;

<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFramework;
<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFrameworkFactory;
<span class="code-keyword">import</span> org.apache.curator.framework.recipes.locks.InterProcessReadWriteLock;
<span class="code-keyword">import</span> org.apache.curator.retry.BoundedExponentialBackoffRetry;

/**
 *
 */
<span class="code-keyword">public</span> <span class="code-keyword">class </span>GoCurator {
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {

CuratorFramework cf = CuratorFrameworkFactory.builder()
.connectString(<span class="code-quote">"localhost:2181"</span>)
.retryPolicy(<span class="code-keyword">new</span> BoundedExponentialBackoffRetry(200, 10000, 20))
.sessionTimeoutMs(30 * 1000)
.build();

cf.start();

InterProcessReadWriteLock lcok = <span class="code-keyword">new</span> InterProcessReadWriteLock(cf, <span class="code-quote">"/grant/myLock"</span>);

<span class="code-object">System</span>.out.println(<span class="code-quote">"Set a Suspend-ALL <span class="code-keyword">break</span> point here and leave it until the session expires, 30 seconds ish"</span>);

lcok.readLock().acquire();

<span class="code-object">System</span>.out.println();
    }
} </pre>
</div></div>
<p>Whlst suspended here, put a Suspend-Thread break poing in EventThread#queueEvent, on the if statement from the first code snippet.</p>

<p> </p>

<p>When you see the following log line, you can let the program resume;</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
2020-02-20 20:15:05,912 [myid:] - INFO [SessionTracker:ZooKeeperServer@398] - Expiring session 0x1006300f2390000, timeout of 30000ms exceeded </pre>
</div></div>
<p>The SendThread will hit your break point first with a Disconnect event, you can let this run.</p>

<p>Next you'll get the SendThread with the Expiry event, wait here until you get the popup telling you that the Curator thread has hit the same break point. Switch to this and step through until it has set the expiry status, then leave it held there and switch back to the SendThread. Let the sendThread run, then remove break points and let everything else run.</p>

<p> </p>

<p>The program will then be stuck and you'll see this stacktrace for the acquire lock method</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-quote">"main@1"</span> prio=5 tid=0x1 nid=NA waiting<span class="code-quote">"main@1"</span> prio=5 tid=0x1 nid=NA waiting  java.lang.<span class="code-object">Thread</span>.State: WAITING   at java.lang.<span class="code-object">Object</span>.wait(<span class="code-object">Object</span>.java:-1)   at java.lang.<span class="code-object">Object</span>.wait(<span class="code-object">Object</span>.java:502)   at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1499)   at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1487)   at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1547)   at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1180)   at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1156)   at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)   at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)   at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1153)   at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:607)   at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:597)   at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:575)   at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:51)   at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)   at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:225)   at org.apache.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:237)   at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:89)   at com.gebatech.curator.GoCurator.main(GoCurator.java:26) </pre>
</div></div>
<p> </p>

<p>I know this issue falls between Zookeeper and Curator but thought I'd report it in case you can think of a solution. I think ideally they'd send a single expiry event with a death flag set or, performance impact allowing, synchronize that method.</p>

---
<details><summary><i>Originally reported by <a title="Grant Digby" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digbyg">digbyg</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-561" target="_blank">Race condition preventing reconnection</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2021-11-08T20:45:53+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>It's very hard to write a test case for this (I'm not able to reproduce what you have above either). My only thought is to set a flag when <tt>injectSessionExpiration()</tt> is called so that if it's called again Curator will just reset the connection. This would work around the problem.  Thoughts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digbyg">digbyg</a>:</i>
<p>Sounds reasonable, if the flag is associated with the instance of EventThread then we'd know it's not spawned a new one since the last call to inject session so can just call reset directly. I'm not sufficiently familiar with Curator to know the implications but happy to test it and report back for my use case when ready.</p>

<p>Strange you couldn't reproduce it. The key is for the curator inject sesison thread to set the state to expired but not proceed further. Then the SendThread tries to post the expired state but returns when it finds the state is already expired, so it just posts the death event causing the event thread to shut down. After that the curator inject sesson thread can carry on. I could capture a video of the repro and post it somewhere?!</p>

<p>Thanks for looking into this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I'm just trying to reproduce this at the moment. I'm positive that I debugged something very similar to this years ago, but never got to the bottom of it. I think that the proposed solution should work, and agree that the flag should be bound to the EventThread instance.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Getting it into ZooKeeper's EventThread requires a PR and support from them which is always a hit-or-miss. I think just closing the ZooKeeper handle should cover all bases. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I was thinking more that the flag on the curator side would just be associated to a particular ClientCnxn instance (via a Map), but maybe it's an unnecessary complication. It seems like it might avoid some potential race conditions where <tt>injectSessionExpiration()</tt> is called multiple times but the underlying connection changes between invocations.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Feel free to handle this if you have time or I'll get to it when I can. I played around with a few ideas yesterday but I'm not completely happy with it yet.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> Happy to have a look into it once I've got this release done.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scott-kirk">scott-kirk</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> I tried to make a patch for this: <a href="https://github.com/apache/curator/pull/400" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/400</a> . I've been seeing this issue in production every month or so and it's been a real headache. I was able to make a test that reproduced the issue, albeit it relies on some knowledge of the internal code of ZooKeeper.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov">mgrigorov</a>:</i>
<p>The build of current master branch (5.2.1) fails due the changes made with this ticket - <a href="https://github.com/apache/curator/pull/400/files#r814748733" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/400/files#r814748733</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>:</i>
<p>Maybe it is better to revert this patch, or find a way to make it work with zookeeper 3.5</p>

<p> </p>

<p>Good catch <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov" class="user-hover" rel="mgrigorov">Martin Tzvetanov Grigorov</a> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>:</i>
<p>It is better to commit <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mgrigorov" class="user-hover" rel="mgrigorov">Martin Tzvetanov Grigorov</a> 's patch to fix CI</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>:</i>
<p>Because the problem is only in the test</p>
