### ISSUE TITLE
[CURATOR-574] DiscoveryService fatal error on deserializing an empty byte[] as JSON

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1093]
<p>Below you can see the error in 5.0.0 tests, but I have seen this error on a client application. The error seems a blocker for the upgrade to 5.0.0</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
ERROR org.apache.curator.framework.listen.MappingListenerManager  Listener (org.apache.curator.framework.recipes.cache.CuratorCacheListenerBuilderImpl$2@329dbdbf) threw an exception [Curator-SafeNotifyService-0]
java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (<span class="code-object">byte</span>[])""; line: 1, column: 0]
	at org.apache.curator.framework.recipes.cache.PathChildrenCacheListenerWrapper.sendEvent(PathChildrenCacheListenerWrapper.java:75)
	at org.apache.curator.framework.recipes.cache.PathChildrenCacheListenerWrapper.event(PathChildrenCacheListenerWrapper.java:42)
	at org.apache.curator.framework.recipes.cache.CuratorCacheListenerBuilderImpl$2.lambda$event$0(CuratorCacheListenerBuilderImpl.java:149)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.apache.curator.framework.recipes.cache.CuratorCacheListenerBuilderImpl$2.event(CuratorCacheListenerBuilderImpl.java:149)
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$putStorage$7(CuratorCacheImpl.java:279)
	at org.apache.curator.framework.listen.MappingListenerManager.lambda$forEach$0(MappingListenerManager.java:92)
	at org.apache.curator.framework.listen.MappingListenerManager.forEach(MappingListenerManager.java:89)
	at org.apache.curator.framework.listen.StandardListenerManager.forEach(StandardListenerManager.java:89)
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$callListeners$10(CuratorCacheImpl.java:293)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:832)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (<span class="code-object">byte</span>[])""; line: 1, column: 0]
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:209)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.childEvent(ServiceCacheImpl.java:175)
	at org.apache.curator.framework.recipes.cache.PathChildrenCacheListenerWrapper.sendEvent(PathChildrenCacheListenerWrapper.java:71)
	... 13 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (<span class="code-object">byte</span>[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3300)
	at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:86)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:204)
	... 15 more
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Enrico Olivelli" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-574" target="_blank">DiscoveryService fatal error on deserializing an empty byte[] as JSON</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Enrico Olivelli" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-06-23T12:30:16+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=itarakanov">itarakanov</a>:</i>
<p>Hello, </p>

<p>We use Apache Zookeeper 3.6.1 + Apache Curator 5.0.0 and can observe the same error.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a>  It looks like I cannot be assignee of this issue.<br/>
Can you please give me the required permissions ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>done</p>
