### ISSUE TITLE
[CURATOR-595] InterProcessSemaphoreV2 LOST isn't releasing permits for other clients

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1112]
<p>I'm not sure this is the right place to raise this, but I've added this test on TestInterProcessSemaphore:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
    @Test
    <span class="code-keyword">public</span> void testAcquireAfterLostServerOnRestart() <span class="code-keyword">throws</span> Exception {
<span class="code-keyword">final</span> <span class="code-object">int</span> sessionTimout = 4000;
<span class="code-keyword">final</span> <span class="code-object">int</span> connectionTimout = 2000;
<span class="code-keyword">try</span> (CuratorFramework client = CuratorFrameworkFactory.newClient(server.getConnectString(), sessionTimout, connectionTimout, <span class="code-keyword">new</span> RetryNTimes(0, 1))) {
    client.start();
    client.blockUntilConnected();
    <span class="code-keyword">final</span> InterProcessSemaphoreV2 semaphore = <span class="code-keyword">new</span> InterProcessSemaphoreV2(client, <span class="code-quote">"/1"</span>, 1);
    assertNotNull(semaphore.acquire());
    CountDownLatch lost = <span class="code-keyword">new</span> CountDownLatch(1);
    client.getConnectionStateListenable().addListener((client1, newState) -> {
<span class="code-keyword">if</span> (newState == ConnectionState.LOST) {
    lost.countDown();
}
    });
    server.stop();
    lost.await();
}
server.restart();
<span class="code-keyword">try</span> (CuratorFramework client = CuratorFrameworkFactory.newClient(server.getConnectString(), sessionTimout, connectionTimout, <span class="code-keyword">new</span> RetryNTimes(0, 1))) {
    client.start();
    client.blockUntilConnected();
    <span class="code-keyword">final</span> InterProcessSemaphoreV2 semaphore = <span class="code-keyword">new</span> InterProcessSemaphoreV2(client, <span class="code-quote">"/1"</span>, 1);
    <span class="code-keyword">final</span> <span class="code-object">int</span> serverTick = ZooKeeperServer.DEFAULT_TICK_TIME;
    <span class="code-object">Thread</span>.sleep(sessionTimout + serverTick);
    assertNotNull(semaphore.acquire(0, TimeUnit.SECONDS));
}
    }
</pre>
</div></div>
<p>And this is not passing: the doc of InterProcessSemaphoreV2 state that </p>
<blockquote><p>"However, if the client session drops (crash, etc.), any leases held by the client are automatically closed and made available to other clients." </p></blockquote>
<p>maybe I'm missing something obvious on the ZK server config instead.</p>

<p>Just checked out that by running on separated processes the same test:</p>
<ol>
	<li>start server on process A</li>
	<li>start lease acquire on process B, listening for LOST events before suicide</li>
	<li>restart server on Process A cause process B to suicide (as expected)</li>
	<li>start lease acquire on process C, now succeed</li>
</ol>

<p>It seems that there is something going on in the intra-process case that's not working as expected (to me, at least).</p>

<p>NOTE: as written in newer comments, raising the timeout doesn't seems to work too and different boxes are getting different outcomes (making this an intermittent failure).</p>

---
<details><summary><i>Originally reported by <a title="Francesco Nigro" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-595" target="_blank">InterProcessSemaphoreV2 LOST isn't releasing permits for other clients</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Information Provided
<li><b>resolved</b>: 2023-06-16T08:07:18+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a></p>

<p>Thanks for the answer!<br/>
I've tried with that waiting time but is not passing for me:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">

org.opentest4j.AssertionFailedError: expected: not <<span class="code-keyword">null</span>>

	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:36)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:31)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:283)
	at org.apache.curator.framework.recipes.locks.TestInterProcessSemaphore.testAcquireAfterLostServerOnRestart(TestInterProcessSemaphore.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Then try with <tt>*3</tt> or <tt>*4</tt>. The deletion of ephemeral nodes by the ZK server is not exact. There is an internal background thread that does it. When the server is restarted, this background thread needs to get schedule, do its runs, etc. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>:</i>
<p>For me it's failing 100% times (now tried just 3 times eh): </p>

<p>the code I've replaced with is</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
assertNotNull(semaphore.acquire(sessionTimout * 2, TimeUnit.MILLISECONDS));
</pre>
</div></div>

<p>Because sessionTimeout was in ms.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Man - there are a ton of "ephemeral not deleted" bugs in ZooKeeper (<a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2867?jql=project%20%3D%20ZOOKEEPER%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20text%20~%20%22ephemeral%20not%20deleted%22" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-2867?jql=project%20%3D%20ZOOKEEPER%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20text%20~%20%22ephemeral%20not%20deleted%22</a>). I just did some more testing and intermittently the old client's ZNode is still there. There's nothing Curator can do it ZK doesn't delete the ephemeral node.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>:</i>
<p>I see that the thread stack analysis and a dump show a curator issue after the client close;<br/>
the stack trace reveal SendThread to still be alive, trying to call on intervals this:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:330)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)
</pre>
</div></div>

<p>No idea how to fix it</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>:</i>
<p>I've further progressed on this:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
INFO  org.apache.curator.framework.state.ConnectionStateManager  State change: SUSPENDED [main-EventThread]
WARN  org.apache.curator.framework.state.ConnectionStateManager  Session timeout has elapsed <span class="code-keyword">while</span> SUSPENDED. Injecting a session expiration. Elapsed ms: 4001. Adjusted session timeout ms: 4000 [Curator-ConnectionStateManager-0]
WARN  org.apache.curator.ConnectionState  Session expired event received [main-EventThread]
DEBUG org.apache.curator.ConnectionState  reset [main-EventThread]
Breakpoint reached
	at org.apache.zookeeper.ZooKeeperTestable.injectSessionExpiration(ZooKeeperTestable.java:40)
	at org.apache.curator.framework.state.ConnectionStateManager.checkSessionExpiration(ConnectionStateManager.java:321)
	at org.apache.curator.framework.state.ConnectionStateManager.processEvents(ConnectionStateManager.java:285)
	at org.apache.curator.framework.state.ConnectionStateManager.access$000(ConnectionStateManager.java:43)
	at org.apache.curator.framework.state.ConnectionStateManager$1.call(ConnectionStateManager.java:132)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:832)
inject closed on sessionid:0x1000eb508090000 local:/127.0.0.1:58770 remoteserver:localhost/127.0.0.1:36721 lastZxid:9 xid:18 sent:18 recv:18 queuedpkts:1 pendingresp:0 queuedevents:1 with <span class="code-object">Thread</span>[main-SendThread(127.0.0.1:36721),5,main] 1780531211
Breakpoint reached
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1124)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1182)
setting state from CLOSED to CONNECTING on <span class="code-object">Thread</span>[main-SendThread(127.0.0.1:36721),5,main] 1780531211
INFO  org.apache.curator.framework.state.ConnectionStateManager  State change: LOST [main-EventThread]
</pre>
</div></div>

<p>The log shows that a session expired call from curator is injecting a session expiration with ZooKeeperTestable::injectSessionExpiration, that's going to set ClientCnxn::state == CLOSED, but, given that there was already a running client with its own SenderThread duty cycle loop (calling select with a session timeout), trying to reconnect,  SendThread::startConnect set <br/>
 ClientCnxn::state == CONNECTING overwriting the CLOSED state and making the SenderThread to leak.</p>

<p>I still don't know what curator can do in order to save this to happen, I'm going into the rabbit hole of the zookeeper client + curator now.</p>

<p>I just see that org.apache.zookeeper.Testable used by curator to inject the expiration simulation is probably racy (as expected) and meant to be used only for testing purpose, as the ZooKeeper doc states: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
    <span class="code-comment">// VisibleForTesting
</span>    <span class="code-keyword">public</span> Testable getTestable() {
<span class="code-keyword">return</span> <span class="code-keyword">new</span> ZooKeeperTestable(cnxn);
    }
</pre>
</div></div>

<p>Probably using this method needs some extra check to make it works reliably, wdyt <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a>?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nigrofranz">nigrofranz</a>:</i>
<p>I'm sending a PR to fix this, bumping the ZK version on Curator: the issue seems already solved on zookeeper by <br/>
<a href="https://issues.apache.org/jira/browse/ZOOKEEPER-3706" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-3706</a> (and backported with <br/>
<a href="https://issues.apache.org/jira/browse/ZOOKEEPER-4223" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-4223</a>), going to test with my reproducer on curator</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli" class="user-hover" rel="eolivelli">Enrico Olivelli</a> probably need your help on how to safely bump ZK version on Curator to get this fixed</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>I copied the test to local and sleeping with <tt>2 * sessionTimout</tt> results in no failures.</p>
