### ISSUE TITLE
[CURATOR-626] NullPointerException in watcher of nullNamespace

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1143]
<p>NPE processing lock released event:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException: <span class="code-keyword">null</span>
    at java.util.concurrent.CompletableFuture.screenExecutor(CompletableFuture.java:415)
    at java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:1871)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.runSafe(CuratorFrameworkImpl.java:191)
    at org.apache.curator.framework.CuratorFramework.postSafeNotify(CuratorFramework.java:344)
    at org.apache.curator.framework.recipes.locks.LockInternals$2.process(LockInternals.java:69)
    at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:77)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:535)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510) </pre>
</div></div>
<p>Steps to reproduce:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
InterProcessMutex lock = <span class="code-keyword">new</span> InterProcessMutex(curatorFramework.usingNamespace(<span class="code-keyword">null</span>), path);
lock.acquire();</pre>
</div></div>
<p>If lock is holded by another process (at the moment of call) - we will never acquire it (after lock was released by holder) because notification event lost while processing on watcher.</p>

<p>The root cause of bug - is wrong init code of СuratorFrameworkImpl:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> CuratorFrameworkImpl(CuratorFrameworkFactory.Builder builder)
{
    .... 
    failedDeleteManager = <span class="code-keyword">new</span> FailedDeleteManager(<span class="code-keyword">this</span>);
    failedRemoveWatcherManager = <span class="code-keyword">new</span> FailedRemoveWatchManager(<span class="code-keyword">this</span>);
    
    <span class="code-comment">// here you pass not fully initialized instance (<span class="code-keyword">this</span>)
</span>    namespaceFacadeCache = <span class="code-keyword">new</span> NamespaceFacadeCache(<span class="code-keyword">this</span>);

    ensembleTracker = zk34CompatibilityMode ? <span class="code-keyword">null</span> : <span class="code-keyword">new</span> EnsembleTracker(<span class="code-keyword">this</span>, builder.getEnsembleProvider());

    runSafeService = makeRunSafeService(builder);
} </pre>
</div></div>
<p>In NamespaceFacadeCache:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
NamespaceFacadeCache(CuratorFrameworkImpl client)
{
    <span class="code-keyword">this</span>.client = client;
    <span class="code-comment">// here you create facade <span class="code-keyword">for</span> <span class="code-keyword">null</span> namespace based on not fully initialized client 
</span>    nullNamespace = <span class="code-keyword">new</span> NamespaceFacade(client, <span class="code-keyword">null</span>);
} </pre>
</div></div>
<p>NamespaceFacade - clones client fields, but not all fields initialized at this moment (ensembleTracker  and runSafeService - are both nulls).</p>

<p>So then we use null namespace - we use this broken client and get NPE on access this null fields (se stacktrace).</p>

<p>Fix is very easy:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">public</span> CuratorFrameworkImpl(CuratorFrameworkFactory.Builder builder)
{
    ...
    failedDeleteManager = <span class="code-keyword">new</span> FailedDeleteManager(<span class="code-keyword">this</span>);
    failedRemoveWatcherManager = <span class="code-keyword">new</span> FailedRemoveWatchManager(<span class="code-keyword">this</span>);

    ensembleTracker = zk34CompatibilityMode ? <span class="code-keyword">null</span> : <span class="code-keyword">new</span> EnsembleTracker(<span class="code-keyword">this</span>, builder.getEnsembleProvider());

    runSafeService = makeRunSafeService(builder);
    
    <span class="code-comment">// initialization of cache should be the last operation in init method (all fields are initialized)
</span>    namespaceFacadeCache = <span class="code-keyword">new</span> NamespaceFacadeCache(<span class="code-keyword">this</span>);
}  </pre>
</div></div>
<p> </p>

---
<details><summary><i>Originally reported by <a title="Viktor Feklin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tipame">tipame</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-626" target="_blank">NullPointerException in watcher of nullNamespace</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kezhu Wang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-08-13T05:24:44+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tipame" class="user-hover" rel="tipame">Viktor Feklin</a>, would you mind opening a pull request for this ? I could take over this in case you are not available.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>master: 97fe626c25d57d47816f95486be77ef39646ed59</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-718">CURATOR-718</a>]</i>
