### ISSUE TITLE
[CURATOR-638] Curator disconnect from zookeeper when IPs change

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1154]
<p>Blocking usage of Zookeeper in production.   Tried testing a few versions all had the issue.  Effects any recipes that use ephemeral nodes.  Example attached.</p>

<p>We use multiple Apache Curator recipes in our system which is running in Docker and Kubernetes.   The behavior I am seeing is that curator appears to resolve to the IP address of the containers rather than being tied to DNS names.   I have seen old tickets on this, but the behavior is reproducible on the latest code release.    </p>

<p>We are running zookeeper in containers on kubernetes.  In kubernetes many things could cause a container to move hosts, the pod disruption budget ensures that a quorum is always present.   But with this bug if all nodes move for any reason and get new IP addresses clients will disconnect when they shouldn't.  Disconnecting has the bad side effect that all ephemeral nodes are lost.   This effects for us coordination, distributed locking and service discovery.   Causes production downtime so marked as a Blocker.</p>

<p>I have a simple sample which just uses the service discovery recipe to register a bunch of services in zookeeper.  I run the example in docker compose.   It is 100% reproducible.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
# Standup zookeeper and wait <span class="code-keyword">for</span> it to be healthy
docker-compose up -d zookeeper1 zookeeper2 zookeeper3 

# Stand up a server and make sure it is connected and working as expected
docker-compose up -d server1

# Take down a single zookeeper node and stand up another agent.
# The agent will grab the old zookeepers IP address
docker-compose rm -s zookeeper1
docker-compose up -d server2

# Bring the zookeeper node back up.  
# Wait <span class="code-keyword">for</span> it be healthy
docker-compose up -d zookeeper1

# Then take down the next zookeeper node and stand up another agent.
# The agent will grab the old zookeepers IP address
docker-compose rm -s zookeeper2
docker-compose up -d server3

# Bring the zookeeper node back up. 
# Wait <span class="code-keyword">for</span> it be healthy
docker-compose up -d zookeeper2

# Then take down the next zookeeper node and stand up another agent.
# The agent will grab the old zookeepers IP address
docker-compose rm -s zookeeper3 
docker-compose up -d server4 

# Bring the zookeeper node back up. 
# Wait <span class="code-keyword">for</span> it be healthy 
docker-compose up -d zookeeper3</pre>
</div></div>
<p> </p>

<p>At the time of taking down the 3rd zookeeper node, the first server1 that was stood up will now receive a disconnected status because the IP of all three nodes has no changes form the original IP addresses.  </p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
server1_1     | Query instances <span class="code-keyword">for</span> servicetest
server1_1     | Exception in thread <span class="code-quote">"main"</span> java.lang.RuntimeException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss <span class="code-keyword">for</span> /myservices/test/62e23a0b-dfdb-46f5-966f-8dc7a4978c70
server1_1     | 	at org.apache.curator.shaded.com.google.common.base.Throwables.propagate(Throwables.java:241)
server1_1     | 	at org.apache.curator.utils.ExceptionAccumulator.propagate(ExceptionAccumulator.java:38)
server1_1     | 	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.close(ServiceDiscoveryImpl.java:171)
server1_1     | 	at org.apache.curator.shaded.com.google.common.io.Closeables.close(Closeables.java:78)
server1_1     | 	at org.apache.curator.utils.CloseableUtils.closeQuietly(CloseableUtils.java:59)
server1_1     | 	at zkissue.App.main(App.java:72)
server1_1     | Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss <span class="code-keyword">for</span> /myservices/test/62e23a0b-dfdb-46f5-966f-8dc7a4978c70
server1_1     | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
server1_1     | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
server1_1     | 	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:2001)
server1_1     | 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:274)
server1_1     | 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:268)
server1_1     | 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93)
server1_1     | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:265)
server1_1     | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:249)
server1_1     | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:34)
server1_1     | 	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.internalUnregisterService(ServiceDiscoveryImpl.java:520)
server1_1     | 	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.close(ServiceDiscoveryImpl.java:157)
server1_1     | 	... 3 more
</pre>
</div></div>
<p> </p>

<p> This causes it to disconnect and lose its discovery state which can be seen from the other services.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
server2_1     | Query instances <span class="code-keyword">for</span> servicetest
server2_1     | test
server2_1     | 	service description: http:<span class="code-comment">//server-4:57456
</span>server2_1     | 	service description: http:<span class="code-comment">//server-3:37740
</span>server2_1     | 	service description: http:<span class="code-comment">//server-2:40219</span></pre>
</div></div>
<p> </p>

<p>Should mention that the Zookeeper cluster is always happy and healthy.   This is a client side issue.</p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Francis Simon" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fksimon">fksimon</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-638" target="_blank">Curator disconnect from zookeeper when IPs change</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Zili Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-07-17T09:04:28+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>:</i>
<p>IIRc in Pulsar (github.com/pulsar-helm-chart) we use a stateful set and a service for the zookeeper cluster and there are no such problems, we are also sing bookkeeper and Curator with Pulsar.</p>

<p> </p>

<p>It would be better to run this conversion on the <span class="nobr"><a href="mailto:user@zookeeper.apache.org" class="external-link" target="_blank" rel="nofollow noopener">user@zookeeper.apache.org<sup><img class="rendericon" src="https://issues.apache.org/jira/images/icons/mail_small.gif" height="12" width="13" align="absmiddle" alt="" border="0"/></sup></a></span> mailing list if it is not a Curator issue</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER288911">JIRAUSER288911</a>:</i>
<p>I was able to reproduce the issue with a bare bones example which is attached to the ticket.    I took the curator service discovery example and basically just wrapped it in docker.   Again we haven no trouble with zookeeper itself, it is just the curator clients.   In Kubernetes we use the <a href="https://github.com/bitnami/charts/tree/master/bitnami/zookeeper" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/bitnami/charts/tree/master/bitnami/zookeeper</a> which is a statefulset.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289461">JIRAUSER289461</a>:</i>
<p>The issue here appears to be caused or exacerbated by how zookeeper configuration events are handled. When the curator is created against a list of nodes, the underlying zookeeper client is provided the same list of nodes. After connection, the <tt>EnsembleTracker</tt> receives a configuration event with the same list of nodes, but it resolves those names to IPs and sets that as the connection string.</p>

<p>When the zookeeper node the client connected with goes away, the curator connection state becomes SUSPENDED before connecting to another node and changing to RECONNECTED. The original node comes back up on another IP and the other node in the cluster also cycles to a new IP before the node we reconnected to goes down.</p>

<p>At this point zookeeper tries to connect to the IP address for the original node, either from the connection string update or something cached internally. That connection fails, since that IP isn't a zookeeper node. The same is then tried for the original IP of the second node the client had connected with, which is also not a zookeeper node anymore. Followed by an attempt at the IP for the third node, to which the client had never connected and something (curator or zookeeper) had earlier resolved to a now useless IP.</p>

<p>After all this, the client is unable to connect to any zookeeper nodes even though all the requested hosts exist at different IPs. Curator closes the client and creates a new one, but the connection string was changed to IP addresses before any of the nodes changed and that client will never be able to connect to zookeeper.</p>

<p> </p>

<p>Why does curator resolve the hostnames to IPs that will never update?</p>

<p>Is that action on the connection string why zookeeper starts using old IPs after nodes go down, even though it originally used the hostnames?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289461">JIRAUSER289461</a>:</i>
<p>Further debugging indicates that curator updating the connection string is what makes zookeeper stop using the hostnames, as the config event causes a call to <tt>Zookeeper.updateServerList</tt>, which updates the <tt>StaticHostProvider</tt> with a connection string that only contains IPs.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>Reported before as <a href="https://issues.apache.org/jira/browse/CURATOR-578" title="EnsembleTracker replace hostname connectString with wrong ip from zk config" class="issue-link" data-issue-key="CURATOR-578"><del>CURATOR-578</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>:</i>
<p>master via 46e1536d3309adcfc10c072d84d46d6ab24eb4fc</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER297268">JIRAUSER297268</a>:</i>
<p>Is there a feeling about when 5.4.0 might be released including this fix? This obviously has a very significant impact, especially on K8S, and is is hitting us hard in production. Thanks very much for making curator. Please let me me know if there is a more appropriate place for me to ask about this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igable" class="user-hover" rel="igable">Ian Gable</a>, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli" class="user-hover" rel="eolivelli">Enrico Olivelli</a> and <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison" class="user-hover" rel="tison">Zili Chen</a> has discussed this in mailing list <a href="https://lists.apache.org/thread/29gq3k4p2dk4k528p6d5y32jj9t7pk8k" class="external-link" target="_blank" rel="nofollow noopener">https://lists.apache.org/thread/29gq3k4p2dk4k528p6d5y32jj9t7pk8k</a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rstephen">rstephen</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igable" class="user-hover" rel="igable">Ian Gable</a> / <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fksimon" class="user-hover" rel="fksimon">Francis Simon</a> would be interested to hear if 5.4.0 has fixed this for you?<br/>
I tried the update today but am still getting the same issue. Going to try rule out a mistake on my part / post reproduction steps. But would be interested to hear if it also hasnt worked for you.</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-578">CURATOR-578</a>]</i>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-664">CURATOR-664</a>]</i>
