### ISSUE TITLE
[CURATOR-640] IllegalThreadStateException thrown when access PathChildrenCache in different thread groups

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1156]
<p>When we create PathChildrenCache instances without specifying thead factory, the <tt>defaultThreadFactory</tt> will be used to create threads. The <tt>defaultThreadFactory</tt> is typically backed by <tt>java.util.concurrent.DefaultThreadFactory</tt> which will add newly created threads into the thread group where it is instantiated. That is, the <tt>defaultThreadFactory</tt> will always add newly created threads into the first thread group that loads the <tt>PathChildrenCache</tt> class.</p>

<p>In cases where <tt>PathChildrenCache</tt> is accessed in different thread groups, if the first thread group that load the <tt>PathChildrenCache</tt> is destroy, then all attempts to start the <tt>PathChildrenCache</tt> will fail.</p>

<p>The problem can be reproduced using the following code: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-object">ThreadGroup</span> threadGroup1 = <span class="code-keyword">new</span> <span class="code-object">ThreadGroup</span>(<span class="code-quote">"testGroup1"</span>);
<span class="code-object">Thread</span> thread1 = <span class="code-keyword">new</span> <span class="code-object">Thread</span>(threadGroup1, () -> {
PathChildrenCache cache1 =
<span class="code-keyword">new</span> PathChildrenCache(client, <span class="code-quote">"/test1"</span>, <span class="code-keyword">true</span>);
<span class="code-keyword">try</span> {
    cache1.start();
    <span class="code-object">Thread</span>.sleep(1000);
} <span class="code-keyword">catch</span> (Throwable t) {
    t.printStackTrace();
} <span class="code-keyword">finally</span> {
    <span class="code-keyword">try</span> {
cache1.close();
    } <span class="code-keyword">catch</span> (IOException e) {
e.printStackTrace();
    }
}
});

thread1.start();
thread1.join();

<span class="code-comment">// After the thread group is destroyed, all PathChildrenCache instances 
</span><span class="code-comment">// will fail to start due to inability to add <span class="code-keyword">new</span> threads into the first thread group
</span>threadGroup1.destroy();

<span class="code-object">ThreadGroup</span> threadGroup2 = <span class="code-keyword">new</span> <span class="code-object">ThreadGroup</span>(<span class="code-quote">"testGroup2"</span>);
<span class="code-object">Thread</span> thread2 = <span class="code-keyword">new</span> <span class="code-object">Thread</span>(threadGroup2, () -> {
PathChildrenCache cache2 =
    <span class="code-keyword">new</span> PathChildrenCache(client, <span class="code-quote">"/test1"</span>, <span class="code-keyword">true</span>);
<span class="code-keyword">try</span> {
    cache2.start();
    <span class="code-object">Thread</span>.sleep(1000);
} <span class="code-keyword">catch</span> (Throwable t) {
    t.printStackTrace();
} <span class="code-keyword">finally</span> {
    <span class="code-keyword">try</span> {
cache2.close();
    } <span class="code-keyword">catch</span> (IOException e) {
e.printStackTrace();
    }
}
});

thread2.start();
thread2.join();
</pre>
</div></div>

<p>When starting <tt>cache2</tt>, the following exception is thrown:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.IllegalThreadStateException
	at java.base/java.lang.<span class="code-object">ThreadGroup</span>.addUnstarted(<span class="code-object">ThreadGroup</span>.java:892)
	at java.base/java.lang.<span class="code-object">Thread</span>.<init>(<span class="code-object">Thread</span>.java:434)
	at java.base/java.lang.<span class="code-object">Thread</span>.<init>(<span class="code-object">Thread</span>.java:708)
	at java.base/java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:660)
	at org.apache.curator.shaded.com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(ThreadFactoryBuilder.java:163)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:630)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1353)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:721)
	at org.apache.curator.utils.CloseableExecutorService.submit(CloseableExecutorService.java:191)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.submitToExecutor(PathChildrenCache.java:841)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.offerOperation(PathChildrenCache.java:792)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.start(PathChildrenCache.java:300)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.start(PathChildrenCache.java:239)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Xiaogang Shi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shixg">shixg</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-640" target="_blank">IllegalThreadStateException thrown when access PathChildrenCache in different thread groups</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Zili Chen" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-06-17T09:01:43+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>:</i>
<p>Thanks for reporting this issue <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shixg" class="user-hover" rel="shixg">Xiaogang Shi</a>! I've add a test and prepare a patch on it. Also this issue can be reproduced on <tt>TreeCache</tt>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>:</i>
<p>master via 83de54888d39173acd7ddad0435f955e4ba736b1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER292998">JIRAUSER292998</a>:</i>
<p>Although this bug is listed as fixed in 5.3.0 when I attempt to build version 5.3.0 there is an internal test that is failing that looks related to this issue:</p>

<p>```</p>

<p><span class="error">&#91;ERROR&#93;</span> Errors: <br/>
<span class="error">&#91;ERROR&#93;</span> org.apache.curator.framework.recipes.cache.TestTreeCache.testIsolatedThreadGroup<br/>
<span class="error">&#91;ERROR&#93;</span>   Run 1: TestTreeCache.testIsolatedThreadGroup:671 » IllegalThreadState Has threads<br/>
<span class="error">&#91;ERROR&#93;</span>   Run 2: TestTreeCache.testIsolatedThreadGroup:671 » IllegalThreadState Has threads<br/>
<span class="error">&#91;ERROR&#93;</span>   Run 3: TestTreeCache.testIsolatedThreadGroup:671 » IllegalThreadState Has threads<br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;ERROR&#93;</span> Tests run: 125, Failures: 0, Errors: 1, Skipped: 1<br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Reactor Summary:<br/>
<span class="error">&#91;INFO&#93;</span> <br/>
<span class="error">&#91;INFO&#93;</span> Apache Curator ..................................... SUCCESS [  2.011 s]<br/>
<span class="error">&#91;INFO&#93;</span> Curator Testing .................................... SUCCESS [  8.989 s]<br/>
<span class="error">&#91;INFO&#93;</span> Curator Client ..................................... SUCCESS [ 31.152 s]<br/>
<span class="error">&#91;INFO&#93;</span> Curator Framework .................................. SUCCESS <span class="error">&#91;10:45 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> Curator Recipes .................................... SUCCESS <span class="error">&#91;29:38 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> Curator Service Discovery .......................... SUCCESS <span class="error">&#91;01:01 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> Curator Async ...................................... SUCCESS <span class="error">&#91;03:25 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> Curator Examples ................................... SUCCESS [  9.240 s]<br/>
<span class="error">&#91;INFO&#93;</span> Curator Service Discovery Server ................... SUCCESS [ 37.418 s]<br/>
<span class="error">&#91;INFO&#93;</span> curator-test-zk35 .................................. FAILURE <span class="error">&#91;10:48 min&#93;</span><br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> BUILD FAILURE<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;INFO&#93;</span> Total time: 57:08 min<br/>
<span class="error">&#91;INFO&#93;</span> Finished at: 2022-07-18T11:17:06-04:00<br/>
<span class="error">&#91;INFO&#93;</span> Final Memory: 95M/1024M<br/>
<span class="error">&#91;INFO&#93;</span> ------------------------------------------------------------------------<br/>
<span class="error">&#91;ERROR&#93;</span> Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project curator-test-zk35: There are test failures.</p>

<p>```</p>
