### ISSUE TITLE
[CURATOR-678] InterProcessMutex#release caused inconsistency between zk node and local cache if encountering zk connection lost

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1193]
<p>We experienced a problem that</p>

<p>an InterProcessMutex participant acquired the lock -> when release() was running, it encountered zk connection lost, then there was inconsistency as in codes <a href="https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessMutex.java#L139" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessMutex.java#L139</a></p>

<p>to line 143, that the zk node deletion threw exception for connection lost, but the local cached `threadData` still removed it.</p>

<p>As a result, even when the zk connection recovered later, ALL following acquire() failed due to the inconsistency (not present in local `threadData` but the OLD zk node were still present).</p>

<p> </p>

<p>Please help confirm this behavior. I think it is bug and curator should fix the inconsistency, a suggestion is to remove the local data ONLY after znode deletion is a success. Also, the same problematic code seems appearing in many other similar recipes such as `InterProcessSemaphore`.</p>

<p> </p>

<p>Stacktrace:</p>

<p>```</p>

<p>Failed to release mutex for xxxxxxxxxxxxx org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /xxxx/_c_65fb02ef-9b1d-4c8c-b715-5c97f82ae0d3-lock-0000000000 at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~<span class="error">&#91;zookeeper-3.6.3.jar:3.6.3&#93;</span> at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~<span class="error">&#91;zookeeper-3.6.3.jar:3.6.3&#93;</span> at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:2001) ~<span class="error">&#91;zookeeper-3.6.3.jar:3.6.3&#93;</span> at org.apache.curator.framework.imps.DeleteBuilderImpl$6.call(DeleteBuilderImpl.java:313) ~<span class="error">&#91;curator-framework-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.imps.DeleteBuilderImpl$6.call(DeleteBuilderImpl.java:301) ~<span class="error">&#91;curator-framework-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:93) ~<span class="error">&#91;curator-client-5.3.0.jar:?&#93;</span> at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:298) ~<span class="error">&#91;curator-framework-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:282) ~<span class="error">&#91;curator-framework-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35) ~<span class="error">&#91;curator-framework-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:347) ~<span class="error">&#91;curator-recipes-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124) ~<span class="error">&#91;curator-recipes-5.3.0.jar:5.3.0&#93;</span> at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154) ~<span class="error">&#91;curator-recipes-5.3.0.jar:5.3.0&#93;</span> at </p>

<p>... ...</p>

<p>```</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Ken Huang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rikimberley">rikimberley</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-678" target="_blank">InterProcessMutex#release caused inconsistency between zk node and local cache if encountering zk connection lost</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Enrico Olivelli" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eolivelli">eolivelli</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p><a href="https://github.com/apache/curator/blob/apache-curator-5.3.0/curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/LockInternals.java#L343-L353" class="external-link" target="_blank" rel="nofollow noopener"><tt>LockInternals::deleteOurPath</tt></a> uses <tt>Guaranteeable::guaranteed</tt> to delete lock path. If the session is repaired before expired, it <a href="https://github.com/apache/curator/blob/apache-curator-5.3.0/curator-framework/src/main/java/org/apache/curator/framework/imps/DeleteBuilderImpl.java#L345-L354" class="external-link" target="_blank" rel="nofollow noopener">was supposed to delete that path  in background</a>.</p>

<p>Did you configure the retry policy ? <tt>CONNECTIONLOSS</tt> has to be retriable for this to function.</p>

<p>PS: I replied similar in <a href="https://issues.apache.org/jira/browse/CURATOR-486" title="InterProcessMutex.release fails to remove a lock on retries." class="issue-link" data-issue-key="CURATOR-486"><del>CURATOR-486</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<blockquote><p>but we don't retry forever, we set a limit for number of retries</p></blockquote>

<p>That is ok. <tt>guaranteed</tt> is supposed to <a href="https://github.com/apache/curator/blob/apache-curator-5.3.0/curator-framework/src/main/java/org/apache/curator/framework/imps/DeleteBuilderImpl.java#L252-L263" class="external-link" target="_blank" rel="nofollow noopener">ignore retry limit</a>.</p>

<blockquote>
<p>As a result, even when the zk connection recovered later, ALL following acquire() failed due to the inconsistency (not present in local `threadData` but the OLD zk node were still present).</p></blockquote>

<p>Any possibility for an reproducible test case ?</p>

<blockquote><p>a suggestion is to remove the local data ONLY after znode deletion is a success.</p></blockquote>
<p>A client "failure" could be a success in server side. This will introduce double-leader.</p>
