### ISSUE TITLE
[CURATOR-728] ServiceCache fails to start if base path is read-only

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#1243]
<p>Up from Curator 5.7.1 calling start() on a ServiceCacheImpl instance fails with a NoAuthException if the base path of the ServiceDiscovery is read-only (e.g. world:anyone:r).</p>

<p>The reason for this problem is the following commit: <a href="https://github.com/apache/curator/commit/9fe79d81a8c5f2484bc29087024b5d65c8fba37f" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/commit/9fe79d81a8c5f2484bc29087024b5d65c8fba37f</a></p>

<p>Before, there has been an if-condition, checking with zookeeper.exists(...) if the  path exists or not. Only if the path was not existing, zookeeper.create() was called. Now, zookeeper.create() is always called and the NoAuthException is not catched, resulting in the following stack trace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Exception in thread <span class="code-quote">"main"</span> org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth <span class="code-keyword">for</span> /test/service
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:53)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:331)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:218)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:214)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:88)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:214)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:202)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:35)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.createContainers(CuratorFrameworkImpl.java:302)
	at org.apache.curator.framework.EnsureContainers.internalEnsure(EnsureContainers.java:63)
	at org.apache.curator.framework.EnsureContainers.ensure(EnsureContainers.java:50)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.startImmediate(ServiceCacheImpl.java:110)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:103)
</pre>
</div></div>
<p> </p>

<p>Steps to reproduce:</p>

<p>In Zookeeper create the node /test/service where /test serves as base path for the service discovery.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
create /test
create /service
setAcl /test world:anyone:r </pre>
</div></div>
<p>Use the following java code to reproduce the issue:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">import</span> java.util.Map;

<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFramework;
<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFrameworkFactory;
<span class="code-keyword">import</span> org.apache.curator.retry.ExponentialBackoffRetry;
<span class="code-keyword">import</span> org.apache.curator.x.discovery.ServiceCache;
<span class="code-keyword">import</span> org.apache.curator.x.discovery.ServiceDiscovery;
<span class="code-keyword">import</span> org.apache.curator.x.discovery.ServiceDiscoveryBuilder;

<span class="code-keyword">class </span>Scratch {
    <span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {
CuratorFramework curatorFramework = CuratorFrameworkFactory.builder()
.connectString(<span class="code-quote">"localhost:2181"</span>)
.retryPolicy(<span class="code-keyword">new</span> ExponentialBackoffRetry(1000, 3))
.build();
curatorFramework.start();

ServiceDiscovery<Map> discovery = ServiceDiscoveryBuilder.builder(Map.class)
.basePath(<span class="code-quote">"/test"</span>)
.client(curatorFramework)
.build();
discovery.start();

ServiceCache<Map> serviceCache = discovery.serviceCacheBuilder().name(<span class="code-quote">"service"</span>).build();
serviceCache.start();

serviceCache.close();
discovery.close();
curatorFramework.close();
    }
} </pre>
</div></div>
<p>The code will fail on serviceCache.start() with the exception shown above.</p>

---
<details><summary><i>Originally reported by <a title="Matthias Kiefer" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kiefermat">kiefermat</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-728" target="_blank">ServiceCache fails to start if base path is read-only</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Kezhu Wang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2025-01-09T02:19:52+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>master: 476268a68d307b6fa989a5314eacd9345bedfc58</p>
