### ISSUE TITLE
[CURATOR-10] NPE from JMX infrastructure in curator-test

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#531]
<p>QuorumPeer.java contains this:</p>

<p>finally </p>
{ MBeanRegistry.getInstance().unregisterAll(); }

<p>Since MBeanRegistry is static, this unregisters all MBeans from ALL QuorumPeers in a TestingCluster.</p>

<p>This causes:</p>

<p><span class="error">&#91;ERROR&#93;</span> NIOServerCnxnFactory - Thread Thread[QuorumPeer<span class="error">&#91;myid=1&#93;</span>/0:0:0:0:0:0:0:0:41733,5,main] died <java.lang.AssertionError>java.lang.AssertionError<br/>
at org.apache.zookeeper.jmx.MBeanRegistry.register(MBeanRegistry.java:89)<br/>
at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:771)<br/>
at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:912)</p>

<p>and similar when connecting a new client to a server after killing another in a test suite.</p>

<p>Looking for a workaround, but bringing this to your attention early.</p>

<p>Note: Code against ZK 3.5.x library, although that unregisterAll() call seems to predate that by a long way, so this is presumably valid throughout?</p>

---
<details><summary><i>Originally reported by <a title="Shevek" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-10" target="_blank">NPE from JMX infrastructure in curator-test</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-06-10T23:37:51+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>:</i>
<p>Possibly need an update of ByteCodeRewrite for v3.5.x - working on it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>:</i>
<p>Proposed solution: ByteCodeRewrite patches out MBeanRegistry.getInstance().register() and unregister() instead of ZooKeeperServer.registerJMX().</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>:</i>
<p>Apache hates my whitespace conventions, but here's a working patch. Mangle to taste.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Please re-do the patch against the Apache source.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The patch worked with some simple search/replace</p>
