### ISSUE TITLE
[CURATOR-12] java.io.IOException: ZooKeeperServer not running after server.kill()

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#533]
<p><span class="error">&#91;DEBUG&#93;</span> NIOServerCnxn - IOException stack trace <java.io.IOException: ZooKeeperServer not running>java.io.IOException: ZooKeeperServer not running<br/>
at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:936)<br/>
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:328)<br/>
at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:530)<br/>
at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:152)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:722)</p>

<p>Preceding election seemed successful.</p>

<p>ZK 3.5.0. Tracking my work.</p>

---
<details><summary><i>Originally reported by <a title="Shevek" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-12" target="_blank">java.io.IOException: ZooKeeperServer not running after server.kill()</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Incomplete
<li><b>resolved</b>: 2013-09-25T04:24:47+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I'm not sure what this is or what can be done about it.</p>
