### ISSUE TITLE
[CURATOR-15] LeaderSelector may (undetectably) fail to elect

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#536]
<p>In LeaderSelector, if mutex.acquire() throws an Exception, for example because CuratorFramework.getZooKeeper() threw a previously-enqueued background exception, then that failure will propagate out of doWork and doWorkLoop, and kill the background submission onto the executor service.</p>

<p>This means that a leaderselector which was start()ed will NEVER elect, and this situation is NOT DETECTABLE externally, since that exception happens on a private executorservice thread and is not client visible. It's impossible to look at a LeaderSelector and decide whether it is still "viable".</p>

<p>This can leave a machine/process "hung" and not automatically recoverable within curator.</p>

<p>Either isQueued() needs to be exposed, which means that a leader is either elected or queued; or the finally{} block which calls clearIsQueued() needs also to set state to CLOSED or FAILED, so that we can query this failure externally.</p>

---
<details><summary><i>Originally reported by <a title="Shevek" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-15" target="_blank">LeaderSelector may (undetectably) fail to elect</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2023-05-23T03:57:27+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juliolopez">juliolopez</a>:</i>
<p>We are running into a slight variation / narrower case of the issue reported here (filed <a href="https://issues.apache.org/jira/browse/CURATOR-16" title="LeaderSelector does not (auto)requeue on session expired" class="issue-link" data-issue-key="CURATOR-16"><del>CURATOR-16</del></a> for it), and thus the solutions may be slightly different.  The issues are that:</p>

<p>a. LeaderSelector fails under certain circumstances, and there's no way of either getting a notification or querying the selector to know whether there was an unrecoverable failure.  Perhaps this needs a notification mechanism.</p>

<p>b. LeaderSelector should re-attempt when auto-requeue is true (for certain types of failures).  Perhaps this needs proper handling of those specific failures (and would take care of <a href="https://issues.apache.org/jira/browse/CURATOR-16" title="LeaderSelector does not (auto)requeue on session expired" class="issue-link" data-issue-key="CURATOR-16"><del>CURATOR-16</del></a>).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juliolopez">juliolopez</a>:</i>
<p>Here is an occurrence, caused by UnknownHostException.  Perhaps, either LeaderSelector or InterProcessMutex should handle these cases and retry.</p>

<p>E 06-23 03:30:07.106 LeaderSelector-0 c.n.c.f.r.l.LeaderSelector:349 |::] mutex.acquire() threw an exception<br/>
java.net.UnknownHostException: xyz.example.com<br/>
at java.net.InetAddress.getAllByName0(Unknown Source) ~<span class="error">&#91;...&#93;</span><br/>
at java.net.InetAddress.getAllByName(Unknown Source) ~<span class="error">&#91;...&#93;</span><br/>
at java.net.InetAddress.getAllByName(Unknown Source) ~<span class="error">&#91;...&#93;</span><br/>
at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:60) ~<span class="error">&#91;...&#93;</span><br/>
at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:27) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:166) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.ConnectionState.getZooKeeper(ConnectionState.java:112) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:107) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:448) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:625) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:609) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:106) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:605) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:428) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:41) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:218) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:218) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:74) ~<span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:313) <span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:374) <span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:45) <span class="error">&#91;...&#93;</span><br/>
at com.netflix.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:194) <span class="error">&#91;...&#93;</span><br/>
at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) <span class="error">&#91;na:1.6.0_32&#93;</span><br/>
at java.util.concurrent.FutureTask.run(Unknown Source) <span class="error">&#91;na:1.6.0_32&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source) <span class="error">&#91;na:1.6.0_32&#93;</span><br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) <span class="error">&#91;na:1.6.0_32&#93;</span></p>
