### ISSUE TITLE
[CURATOR-34] CuratorFramework.create().creatingParentsIfNeeded().forPath() throws NodeExistsException if node exists

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#555]
<p>I think that NodeExistsException should be ignored in CreateBuilderImpl. In the try and in the NoNodeException catch block as well.</p>

<p>org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /examples/something<br/>
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)<br/>
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)<br/>
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:626)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:610)<br/>
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:606)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:429)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:409)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:317)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:253)</p>

---
<details><summary><i>Originally reported by <a title="Nandor Kracser" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bonifaido">bonifaido</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-34" target="_blank">CuratorFramework.create().creatingParentsIfNeeded().forPath() throws NodeExistsException if node exists</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2023-08-07T08:15:16+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vines">vines</a>:</i>
<p>Sounds like this is actually a case for EnsurePath?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bonifaido">bonifaido</a>:</i>
<p>I agree, but the a name suggests that it creates parents if needed, which (for me at least) doesn't necessarily mean that it will throw an exception if they already exist.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cheddar">cheddar</a>:</i>
<p>I'm confused.  If you call</p>

<p>framework.create.creatingParentsIfNeeded.forPath("/examples/something");</p>

<p>And </p>

<p>/examples/something</p>

<p>already exists, I believe the correct behavior is to throw a NodeExistsException, that seems correct to me.  </p>

<p>The "creatingParentsIfNeeded()" is just making sure that the parents exist, not handling the case where the child node might already exist.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vines">vines</a>:</i>
<p>Perhaps there should be ignoreIfExists() and/or setDataIfExists flag(s) that can be used? I can understand where Nandor is coming from, as this request and createParentsIfNeeded are in the same family of "I just want this node to exist (optionally with this data) now".</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Seems like it would be: <tt>create.ifNotExists().forPath(...)</tt>. It would chain with other builder methods so you could do: <tt>create.creatingParentsIfNeeded().ifNotExists().forPath(...)</tt>, etc.</p>

<p>Technically, though, as is pointed out above, this can be accomplished with <tt>EnsurePath</tt>. Is this API really needed?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vines">vines</a>:</i>
<p>Well, based on our previous email discussion about possibly deprecating EnsurePath, this may be something still worth investigating. Being able to do this type of check inline of the create really helps streamline code, IMO.</p>

<p>I actually think there need to be 2 seperate flags though, ignoreIfExists and setDataIfExists (or something along those lines). Personally, there are a flew blocks of code I have that are basically<br/>
if checkExists==null<br/>
  create<br/>
else<br/>
  setData</p>

<p>That I would LOVE to flatten to a single call.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p><tt>setDataIfExists</tt> would be part of the <tt>setData</tt> chain then. Something like: </p>

<p>    <tt>client.setData().ifNodeExists().forPath()</tt></p>

<p>Is <tt>ignoreIfExists</tt> the same as <tt>create.creatingParentsIfNeeded().ifNotExists()</tt> in my example above? Would both of these APIs need an option to return a boolean indicating whether the operation occurred or not?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vines">vines</a>:</i>
<p>Well, in the create() chain, I see two different scenarios based on the node already existing.</p>

<p>Either you want have the final forPath()'s arguments set or not set, and that's where I see the need for two different flags. Basically, if the node you're trying to create exists, then ignore this call OR setData. Honestly, where I sorta see this discussion going is blurring the line between create() and setData() to sort of flatten them into a single family with some different behaviors depending on existence.</p>



<p>ignoreIfExists is equivalent to ifNotExists. A boolean is nice, but I can see that worked around in client code if people need feedback since I imagine that sort of change isn't quite feasible. I mean, they could just not use that method and catch the exception if they're trying to figure that sort of thing out.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I wonder, then, if this should be a new type of builder: ifNode. i.e.</p>

<p><tt>client.ifNode().exists().setData().forPath()</tt><br/>
<tt>client.ifNode().doesntExist().create().forPath()</tt></p>

<p>What other apis could this chain have?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vines">vines</a>:</i>
<p>I think anything that falls under a write category-<br/>
delete()<br/>
setACL()</p>

<p>Though having the ability for get*() methods to just return null if things don't exist could be useful, but that may be a case of abusing return values.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mridulv09">mridulv09</a>:</i>
<p>Instead of format specified above, i think , the format should be something like:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">client.ifNodeExists().then(setData()).<span class="code-keyword">else</span>(create()).forPath()
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>Curator has <tt>CreateBuilder.orSetData</tt> now.</p>
