### ISSUE TITLE
[CURATOR-39] ServiceProvider thread is not closed during ServiceDiscovery close

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#560]
<p>I'm using 2.0.1-incubating, using the following to build a ServiceProvider:</p>

<p>serviceProvider = serviceDiscovery.serviceProviderBuilder()<br/>
    .serviceName(name)<br/>
    .providerStrategy(new RoundRobinStrategy<DiscoverableService>())<br/>
    .build();<br/>
serviceProvider.start();</p>

<p>I have a name => ServiceProvider map that stores all my service providers. During shutdown, I call:</p>

<p>for (ServiceProvider serviceProvider : serviceProviderMap.values()) </p>
{
    serviceProvider.close();
}

<p>serviceDiscovery.close();</p>

<p>Which is redundant, it seems, because serviceDiscovery itself appears to shutdown the providers. However, I still end up with a dangling "ServiceProvider-0" thread that keeps Tomcat open.</p>

<p>If I start the container up, without making a service call (so I don't allocate any ServiceProviders), Tomcat shuts down cleanly. As soon as a ServiceProvider is allocated (by making a service call) Tomcat hangs during shutdown, and informs me of the remaining thread. I will try to provide more information as it becomes available to me.</p>

---
<details><summary><i>Originally reported by <a title="Colin Morelli" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cmorelli">cmorelli</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-39" target="_blank">ServiceProvider thread is not closed during ServiceDiscovery close</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ioannis Canellos" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iocanel">iocanel</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2013-10-07T09:05:55+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cmorelli">cmorelli</a>:</i>
<p>This is the thread dump after the application is shut down:</p>

<p>"ServiceProvider-0@20902" daemon prio=5 tid=0x7a nid=NA waiting<br/>
  java.lang.Thread.State: WAITING<br/>
	  at sun.misc.Unsafe.park(Unsafe.java:-1)<br/>
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)<br/>
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)<br/>
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)<br/>
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)<br/>
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)<br/>
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
	  at java.lang.Thread.run(Thread.java:722)</p>

<p>The thread simply has nothing to process. The fix seems pretty simple to me, inside CloseableExecutorService, the close() method should call the shutdown() method of the ExecutorService, which it doesn't do currently.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iocanel">iocanel</a>:</i>
<p>Agree,</p>

<p>I think that the root cause falls back to the PatchChildrenCache issue with the ClosingExecutorService aka <a href="https://issues.apache.org/jira/browse/CURATOR-27" title="PathChildrenCache creates but doesn&#39;t shut down Executors" class="issue-link" data-issue-key="CURATOR-27"><del>CURATOR-27</del></a>.</p>

<p>Since, <a href="https://issues.apache.org/jira/browse/CURATOR-27" title="PathChildrenCache creates but doesn&#39;t shut down Executors" class="issue-link" data-issue-key="CURATOR-27"><del>CURATOR-27</del></a> is now resolved, I think that we need to resolve this one too as duplicate.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=weigao">weigao</a>:</i>
<p>I don't think this bug is fixed by <a href="https://issues.apache.org/jira/browse/CURATOR-27" title="PathChildrenCache creates but doesn&#39;t shut down Executors" class="issue-link" data-issue-key="CURATOR-27"><del>CURATOR-27</del></a>.</p>

<p>ServiceProviderImpl constructor accept threadFactory only, and it will use ServiceCacheBuilder to build cache (with threadFactory). In ServiceCacheImpl constructor, if thread factory provided, it call "convertThreadFactory" to create CloseableExecutorService, but this will create CloseableExecutorService with default value of "shutdownOnClose", which is false.</p>

<p>So, even close ServiceProvider, it will not shutdown cache's thread pool, which cause thread leak.</p>

<p>Any idea why builder pattern not accept ExecutorService, so we can manage lifecycle of thread pool, and use real thread pool instead of single thread?</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-27">CURATOR-27</a>]</i>
