### ISSUE TITLE
[CURATOR-45] LeaderSelector threw exception, but still created ephemeral node, breaking everything

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#566]
<p>ZooKeeper hiccupped, and then this happened:</p>

<p>    2013-06-19 02:23:35,561 DEBUG <span class="error">&#91;LeaderSelector-1&#93;</span> com.netflix.curator.RetryLoop.takeException (RetryLoop.java:184) - Retry-able exception received<br/>
    org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /<span class="error">&#91;REMOVED&#93;</span>/election/_c_1ccdb2b9-7f9a-4570-9555-201c91ec2dcb-lock-</p>

<p>    at org.apache.zookeeper.KeeperException.create(KeeperException.java:99) ~<span class="error">&#91;zookeeper-3.5.0.jar:3.5.0--1&#93;</span></p>

<p>    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~<span class="error">&#91;zookeeper-3.5.0.jar:3.5.0--1&#93;</span></p>

<p>    at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:876) ~<span class="error">&#91;zookeeper-3.5.0.jar:3.5.0--1&#93;</span></p>

<p>    at com.netflix.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:625) ~<span class="error">&#91;curator-framework-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.imps.CreateBuilderImpl$10.call(CreateBuilderImpl.java:609) ~<span class="error">&#91;curator-framework-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:106) <span class="error">&#91;curator-client-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:605) <span class="error">&#91;curator-framework-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:428) <span class="error">&#91;curator-framework-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:41) <span class="error">&#91;curator-framework-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:218) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:218) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:74) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:314) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:373) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:46) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at com.netflix.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:195) <span class="error">&#91;curator-recipes-1.3.5-SNAPSHOT.jar:?&#93;</span></p>

<p>    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) <span class="error">&#91;?:1.6.0_27&#93;</span></p>

<p>    at java.util.concurrent.FutureTask.run(FutureTask.java:166) <span class="error">&#91;?:1.6.0_27&#93;</span></p>

<p>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) <span class="error">&#91;?:1.6.0_27&#93;</span></p>

<p>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) <span class="error">&#91;?:1.6.0_27&#93;</span></p>

<p>    at java.lang.Thread.run(Thread.java:679) <span class="error">&#91;?:1.6.0_27&#93;</span></p>

<p>However, the ephemeral node got created, and this hung leader election for this path.</p>

<p>I'm investigating to work out where to put an extra guaranteed-delete. I see the case in LockInternals, which sometimes triggers to do this cleanup, but it didn't trigger in this case.</p>

<p>You must really love our bugs by now.</p>

---
<details><summary><i>Originally reported by <a title="Shevek" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-45" target="_blank">LeaderSelector threw exception, but still created ephemeral node, breaking everything</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-09-25T17:10:12+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arren">arren</a>:</i>
<p>The extra doDelete flag cleans up messes from LockInternals.internalLockLoop() but does not clean up if the initial attemptLock() fails.</p>

<p>It may be a false assumption in curator that ZooKeeper either succeeds OR throws an exception. In this case, ZooKeeper did both, leaving the client in some doubt about the server's state.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>I can reproduce the issue in a unit test, i'm working on a fix.<br/>
Basically If the retry policy expires before the session and in the mean time the connection is back then the ephemeral node is never deleted.<br/>
The tricky part is that we don't know the name of the znode that has been created so i think we have to use the UUID created by the withProtection(), keep it in memory and when the connection is back do the clean up.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>Here's a first draft, the patch uses FailedDeleteManager to ensure that the znode is deleted once the connection is back.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>znode lookup is done in background<br/>
fix some typo</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Thank you for the patch - I'll look at it as soon as I can (or one of the other committers will)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Patch looks great. This is the right solution. I'm constantly amazed at how many edge cases there are when using ZK.</p>

<p>Comments:</p>

<ul>
	<li>Please add support for background operations - i.e. the same protection should be added to inBackground() operations</li>
	<li>The cast in FindProtectedNodeCB.processResult() is unnecessary. Instead call client.delete().guaranteed().inBackground().forPath(...)</li>
	<li>The bodies of findProtectedNodeInForeground() (which should probably be renamed) and FindProtectedNodeCB.findNode() can be shared/merged via refactoring</li>
	<li>Is the call in protectedPathInForeground's catch to setProtected() meant to reset the protectedId? I'd rather see that done explicitly than calling setProtected(). It's clearer to my eye.</li>
	<li>In FindProtectedNodeCB.processResult() - the case where "event.getResultCode() == KeeperException.Code.CONNECTIONLOSS.intValue()" can call findAndDeleteProtectedNodeInBackground() instead of "client.getChildren()...". This way, the client state (isStarted()) gets rechecked. Further, any additional future checks get re-used.</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>Thanks for your feedback, i will update the patch according to your comments</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Any update on this <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay" class="user-hover" rel="barkbay">Michael Morello</a>?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>I'm sorry, I've been very busy the last few days, I will review <a href="https://issues.apache.org/jira/browse/CURATOR-52" title="Retry issues with background operations" class="issue-link" data-issue-key="CURATOR-52"><del>CURATOR-52</del></a> and update the patch asap.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>Add support for background operation</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Patch accept and applied. Thank you!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sasvaritoni">sasvaritoni</a>:</i>
<p>Was this patch also tested with autoRequeue enabled?</p>

<p>I have changed TestLeaderSelectorEdges.flappingTest() to enable autoRequeue() for leaderSelector1, and it seems that more and more ephemeral nodes keep getting created and the deleted (with increasing sequence numbers), and leaderSelector1 is getting and loosing leadership all the time.</p>

<p>It looks like the new LE ephemeral node would be constantly deleted in the background, and then recreated again because of autoRequeue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sasvaritoni">sasvaritoni</a>:</i>
<p>I checked this again, and just realized that the test what I made makes no sense at all, as the TestLeaderSelectorListener.takeLeadership() exits immediately.<br/>
So please ignore my previous comment, sorry ...</p>
