### ISSUE TITLE
[CURATOR-63] ServiceCacheImpl doesn't check if service name is null

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#584]
<p>If not giving a service name with ServiceCacheBuilder.name() the ServiceCache throws a weird Exception later on, because it wants to fetch data from the service group node instead of the service instance node:</p>

<p>Exception in thread "main" java.io.EOFException: No content to map to Object due to end of input<br/>
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2766)<br/>
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)<br/>
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1964)<br/>
	at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:50)<br/>
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:178)<br/>
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:81)</p>

---
<details><summary><i>Originally reported by <a title="Nandor Kracser" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bonifaido">bonifaido</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-63" target="_blank">ServiceCacheImpl doesn't check if service name is null</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2013-10-08T20:46:38+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Might as well check not-null for the discovery arg too</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bonifaido">bonifaido</a>:</i>
<p>Why not, patch updated.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Patched applied and pushed.</p>
