### ISSUE TITLE
[CURATOR-72] Background operations don't wait for connection timeout

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#593]
<p>Background operations don't wait for the configured connection timeout before failing. Attached test shows the problem.</p>

---
<details><summary><i>Originally reported by <a title="Evaristo Camarero" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristo-jose.camarero@ericsson.com">evaristo-jose.camarero@ericsson.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-72" target="_blank">Background operations don't wait for connection timeout</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-02-05T18:42:08+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Background operations were not checking if the client was connected. Further, the connection timeout was not being respected as it is in foreground operations.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Not sure if the comments arrive to the list</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>The problem is not the initial LOST. What is suspicious for me is having having another LOST after CONNECTED and before SUSPENDED. Somehow the natural ordering of the events is broken</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Still trying to iron out connection state transitions.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristo-jose.camarero%40ericsson.com" class="user-hover" rel="evaristo-jose.camarero@ericsson.com">Evaristo Camarero</a>, can you test branch "<a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a>"? I've worked on state changes in the background so that they match foreground operations. Please let me know.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>I attach a test that show the LOST event is not fired.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Were you able to check the last test I provided?</p>

<p>Anyyway I am thinking that probably a good regression for ConnectionStateListener is missing in the project and that I could code a complete regression for that mixing CuratorFramework clients and some recipes.</p>

<p>For doing that, probably I would need your help to define the spec of the API: when listeners are fired, events ordering, timings and so on. So if you provide me some guidelines about that I can build a regression that will help to check listeners behavior between releases. What do you think?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Yes, I did. There's a real problem. I haven't had time to look at yet though. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>OK - holidays and moving are done I'm back on Curator...</p>

<p>I just pushed what I think is the ultimate fix for this. Both of your tests now pass. Please validate when you can.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>I have run the regression of my app, and I think there is an issue with the patch</p>

<p>I describe the use case:<br/>
1.- CuratorFramework connected to healthy ZK ensemble with several recipes related (leader election, nodeCache, pathchildrencache)<br/>
2.- Stop all ZK server from the ensemble<br/>
3.- CuratorFramework triggers SUSPENDED (As expected)<br/>
4.- CuratorFramework triggers LOST (As expected)<br/>
5.- Starting all ZK servers from the ensemble again<br/>
7.- CuratorFramework triggers RECONNECTED (As expected)<br/>
8.- After step 7, CuratorFramework triggers LOST (NOT EXPECTED)</p>

<p>I will try to provide a test that shows the issue asap</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Thanks again - a test case would be appreciated. This has been one of the thorniest issues in Curator.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Finally I have a test that shows the problem (TestListenerWithLeaderSelector.java). The test shows a CF client with a LeaderSelector, and a ZK server that is started and stopped. The listeners sequence is broken with <a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a> in some runs of the test</p>

<p>I have made 10 runs of test with <a href="https://issues.apache.org/jira/browse/CURATOR-2" title="OSGi-friend distribution" class="issue-link" data-issue-key="CURATOR-2"><del>CURATOR-2</del></a>.1.0 (all passed) and 10 runs with CURATOR_72 (5 passed and 5 failed with listener sequence CONNECTED-SUSPENDED-LOST-RECONNECTED-LOST)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay">barkbay</a>:</i>
<p>There's a kind of race condition :</p>

<p>First CuratorFramework-0-EventThread  sets connection state to RECONNECTED because Zookeeper told it to do so</p>
<blockquote>
<p>	at org.apache.curator.framework.state.ConnectionStateManager.addStateChange(ConnectionStateManager.java:159)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.validateConnection(CuratorFrameworkImpl.java:757)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processEvent(CuratorFrameworkImpl.java:717)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$000(CuratorFrameworkImpl.java:56)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$1.process(CuratorFrameworkImpl.java:133)<br/>
	at org.apache.curator.ConnectionState.process(ConnectionState.java:145)<br/>
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:519)<br/>
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495)</p></blockquote>

<p>Right after CuratorFramework-0 sets connection state to LOST because of a background retry that is still in the pipeline :</p>
<blockquote>
<p>	at org.apache.curator.framework.state.ConnectionStateManager.addStateChange(ConnectionStateManager.java:168)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.logError(CuratorFrameworkImpl.java:517)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:593)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:699)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:665)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:56)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$3.call(CuratorFrameworkImpl.java:244)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)<br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)<br/>
	at java.lang.Thread.run(Thread.java:662)</p></blockquote>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I see the issue. As <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=barkbay" class="user-hover" rel="barkbay">Michael Morello</a> points out, there's a race. When Curator goes to SUSPENDED, it starts a background sync() call to check if it needs to go to LOST. During this, Curator might reset the connection. The new reset connection will succeed, but the previous connection fails. What needs to happen is Curator needs to make note that the connection got reset and ignore the background sync() failure which is now for a no longer used ZooKeeper instance.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>OK - I've just pushed a fix for this edge case. Please verify.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Previous test work fine now, but<br/>
now fails a different thing, a SUSPENDED is fired after RECONNECTED. You can easily check that with TestListenerWithLeaderSelectorBis</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Hi there:</p>

<p>I have been comparing code in <a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a> (current code) and CURATOR 2.1.0, and these are my conclussions:</p>

<ul class="alternate" type="square">
	<li>In both releases  there is race condition between background and foreground errors  and KeeperState events that can break the ConnectionState listener statusm (as demonstrated by attached tests</li>
	<li><a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a> (I think from Curator 2.3.0) there is an issue and the number of retries in some cases is huge and out of control and therefore the previous race condition is much more evident. (Can be also seen with attached tests using LeaderElection)</li>
</ul>


<p>So in fact there are 2 issues here. The first one (the race condition I think was already there before 2.3) and the second one is new.</p>

<p>On the other hand, I suggest to have a clear defintion of the different values for ConnectionState and when they are triggered, because implementations in CUARTOR 2.1 and CURATOR 72 are different and in my opinion they follow a different specification (e.g. how ConnectionLoss exceptions are managed)</p>

<p>In <a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a> this is the logic:</p>
<ul class="alternate" type="square">
	<li>CONNECTED AND RECONNECTED are clear for me (they only depend on KeepState events)</li>
	<li>SUSPENDED can be triggered by KeeperState.Disconnected event or by a ConnectionLoss or OperationTimeout operation (whatever happens first)</li>
	<li>LOST can be triggered directly by KeeperState.Expired and SessionExpired exceptions and when received a ConnectionLost or OperationTimeout a background operation is started to check if it is possible to connect to other ZK server and in that case LOST is also triggered</li>
</ul>


<p>In <a href="https://issues.apache.org/jira/browse/CURATOR-2" title="OSGi-friend distribution" class="issue-link" data-issue-key="CURATOR-2"><del>CURATOR-2</del></a>.1.0 the logic is:</p>
<ul class="alternate" type="square">
	<li>CONNECTED AND RECONNECTED are clear for me (they only depend on KeepState events)</li>
	<li>SUSPENDED can be only triggered by KeeperState.Disconnected</li>
	<li>LOST is triggered by any ConnectionLoss exception</li>
</ul>


<p>I am trying to provide a patch for the code but I am struggling, but if we agree on definition I can help with test cases</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Hi there,</p>

<p>TestListenerWithLeaderSelectorBis shows a snow ball effect with ConnectionLossExceptions</p>

<p>One of the issues that I have found with <a href="https://issues.apache.org/jira/browse/CURATOR-72" title="Background operations don&#39;t wait for connection timeout" class="issue-link" data-issue-key="CURATOR-72"><del>CURATOR-72</del></a> code is that callBack for retriesExhausted in background operations is called twice (once by checkBackgroundRetry and another one by handleBackgroundOperationException). This generates an snow fall effect if you are using for instance a guaranted delete like is used by the leader selector to delete lock nodes when the connection is suspended.</p>

<p>Even fixing that, I am pretty sure there is more issues  because the ConnectionLoss exceptions storm still grows</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>Hi there,</p>

<p>I think I got it. I attach a patch. Please take a look and provide comments</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Looks good. Why the removal of "handleBackgroundOperationException(operationAndData, e);" in favor of just logging the error?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evaristojosec@yahoo.es">evaristojosec@yahoo.es</a>:</i>
<p>The code is basically redundant with checkBackgroundRetry(operationAndData, event). If you also maintain handleBackgroundOperationException(operationAndData, e) you are for instance calling twice the retriesExhausted callback. In some cases this has a snow ball effect (e.g. guaranteed deletes grows exponentially because retries exhausted callback generates a new background operation).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>There's still a problem. TestBackgroundStates.testConnectionStateListener() is failing. I'll look into it. You can too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>OK - I just pushed a change that makes testConnectionStateListener() and all the background state change tests work. I hate how complicated this code is getting but I'm not sure what else to do.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zerd">zerd</a>:</i>
<p>Seems like this is not completely fixed. We run curator 2.4.1, and we got 22 million of these in one day:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2014-05-26 14:50:59,062 ERROR [main-EventThread    ] o.a.c.f.imps.CuratorFrameworkImplT: S: U: - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:99) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:666) [curator-framework-2.4.1.jar:na]
at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:479) [curator-framework-2.4.1.jar:na]
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166) [curator-framework-2.4.1.jar:na]
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590) [zookeeper-3.4.5.jar:3.4.5-1392090]
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495) [zookeeper-3.4.5.jar:3.4.5-1392090]
2014-05-26 14:50:59,063 ERROR [main-EventThread    ] o.a.c.f.imps.CuratorFrameworkImplT: S: U: - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:99) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:666) [curator-framework-2.4.1.jar:na]
at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:479) [curator-framework-2.4.1.jar:na]
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166) [curator-framework-2.4.1.jar:na]
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590) [zookeeper-3.4.5.jar:3.4.5-1392090]
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495) [zookeeper-3.4.5.jar:3.4.5-1392090]
</pre>
</div></div>

<p>Two other related messages, but with normal amounts of logging:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2014-05-26 01:35:39,899 WARN  [read(localhost:2181)] org.apache.zookeeper.ClientCnxn  T: S: U: - Session 0x0 <span class="code-keyword">for</span> server <span class="code-keyword">null</span>, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_51]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_51]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
2014-05-26 01:35:41,004 INFO  [read(localhost:2181)] org.apache.zookeeper.ClientCnxn  T: S: U: - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Were the times all nearly the same? Or is there a reasonable distribution? Was the ZK ensemble down for an extended period?</p>
