### ISSUE TITLE
[CURATOR-85] curator-client ConnectionState uses deprecated Closeables method

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#606]
<p>Tried to upgrade to guava-16 and started getting these errors from Curator on exit:</p>

<p>Exception in thread "Thread-1" java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/Closeable;)V<br/>
	at org.apache.curator.ConnectionState.close(ConnectionState.java:109)<br/>
	at org.apache.curator.CuratorZookeeperClient.close(CuratorZookeeperClient.java:196)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.close(CuratorFrameworkImpl.java:284)<br/>
	at com.virident.fmc.service.AbstractService.closeCF(AbstractService.java:199)<br/>
	at com.virident.fmc.service.AbstractService.shutdown(AbstractService.java:215)<br/>
	at com.virident.fmc.service.AbstractService.access$000(AbstractService.java:31)<br/>
	at com.virident.fmc.service.AbstractService$1.run(AbstractService.java:98)<br/>
tail: /var/lib/vgccluster/manager.out: file truncated</p>

<p>Investigation shows this code:</p>

<p>    public void close() throws IOException<br/>
    {<br/>
log.debug("Closing");</p>

<p>Closeables.closeQuietly(ensembleProvider);</p>

<p>This closeQuietly() method is deprecated as of guava 14, and it gone in guava 16.  The 2-parameter closeQuietly() needs to be called, eg:</p>

<p>Closeables.closeQuietly(ensembleProvider, true);</p>

<p>Curator master source still seems to have this bug.  The 2-parameter closeQuietly is already be available in guava-14 and the 1-parameter version is marked decorated as deprecated in that release which should have generated deprecation warnings.</p>

<p>A visual inspection of the various curator projects shows that this deprecated API is used in many places.  They all should be corrected to use the 2-parameter Closeables.closeQuietly().</p>

---
<details><summary><i>Originally reported by <a title="Dave Cohrs" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davecohrs">davecohrs</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-85" target="_blank">curator-client ConnectionState uses deprecated Closeables method</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-02-03T18:57:01+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>A patch would be appreciated. Suggestion: Just move the Closeables.closeQuietly() method to a top level class like was done with DirectoryUtils.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sigpwned">sigpwned</a>:</i>
<p>Thanks for the quick response, Jordan. I'll see if I can't get a patch turned around in the next day or two.</p>

<p>To be minimally disruptive to projects currently using Curator, it looks like The Right Thing is not to bump the version of the guava dependency, but rather to port calls from Closeables#closeQuietly(Closeable) to Closeables#close(Closeable,boolean), which is already available in 14.1 and still available (and not @deprecated) in 16.0. </p>

<p>However, if you'd prefer I bump to 15.0 or 16.0, it shouldn't be hard to do that, either. I see an issue (<a href="https://issues.apache.org/jira/browse/CURATOR-69" title="update guava to 15,the version 14 can&#39;t deploy in glassfish" class="issue-link" data-issue-key="CURATOR-69"><del>CURATOR-69</del></a>) to bump to 15.0; it'd be pretty easy to handle that in this patch, too.</p>

<p>Unless you say otherwise, I'll keep to 14.0.1.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The problem with Closeables#close(Closeable,boolean) is that it's marked to throw an exception. So, the change will be disruptive. What I planned to do was write a new class that has the old code (frankly, I can't understand why they're removing it):</p>

<p>public class CloseQuietly {<br/>
  public static void closeQuietly(Closeable closeable) {<br/>
    try </p>
{
      close(closeable, true);
    }
<p> catch (IOException e) </p>
{
      logger.log(Level.SEVERE, "IOException should not have been thrown.", e);
    }
<p>  }<br/>
}</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sigpwned">sigpwned</a>:</i>
<p>Got it. Thanks for the clarification. I'll plan to keep guava at its current version and create a class called CloseableUtils (to match DirectoryUtils, per your original comment) containing the method you gave above, and replace all calls to Closeables#closeQuietly(Closeable) to CloseableUtils#closeQuietly(Closeable).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sigpwned">sigpwned</a>:</i>
<p>Here's the patch we discussed (curator-85.diff). It creates a class <tt>org.apache.curator.utils.CloseableUtils</tt> in <tt>curator-client</tt>, since that's the common dependency for all other Curator modules. The class creates a method <tt>closeQuietly()</tt>, which has the implementation Jordan provided yesterday. The patch then replaces all references to <tt>Closeables#closeQuietly()</tt> in master with references to <tt>CloseableUtils#closeQuietly()</tt>. The patch was tested with <tt>mvn clean compile test</tt> with the guava dependency set to 14.0.1 and 16.0 in the parent POM, and succeeded both times. (This patch leaves the guava dependency at 14.0.1.)</p>

<p>This should be the final patch, but of course all feedback is welcome and I'm happy to make any changes you need!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sigpwned">sigpwned</a>:</i>
<p>Hi Jordan, just checking in on this patch. Not trying to rush you &#8211; I'm sure you're busy above and beyond everything you already do on this project &#8211; just trying to see if the patch is acceptable, and if there's anything I can do to make the patch easier for you to work with.</p>

<p>Thanks again for Curator! It's a wonderful addition to ZooKeeper, and I never use ZooKeeper without it. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Sorry - I'll look at it in the next day or so. Curator really needs more active committers. If you'd like to take a stab at any other open issues, it would be appreciated.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sigpwned">sigpwned</a>:</i>
<p>Jordan, no worries at all! Appreciate the response! Just trying to see if I can lighten the load.</p>

<p>I'll thumb through the other open issues over the next couple of days and see if I can't take a whack at a few more.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Patch accepted, merged and pushed. Thank you!</p>
