### ISSUE TITLE
[CURATOR-101] ServiceDiscoveryImpl.close() fails if the service was never started

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#622]
<p>the <tt>close()</tt> operator of ServiceDiscoveryImpl raises an <tt>IllegalStateException</tt> if you attempt to call it -this is a runtime exception and somewhat drastic on an operation that should be robust against odd states.</p>

---
<details><summary><i>Originally reported by <a title="Steve Loughran" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-101" target="_blank">ServiceDiscoveryImpl.close() fails if the service was never started</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2015-04-19T18:36:04+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>:</i>
<p>stack. </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IllegalStateException: instance must be started before calling <span class="code-keyword">this</span> method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:327)
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.unregisterService(ServiceDiscoveryImpl.java:198)
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.close(ServiceDiscoveryImpl.java:129)
	at org.apache.hadoop.io.IOUtils.cleanup(IOUtils.java:237)
	at org.apache.hadoop.io.IOUtils.closeStream(IOUtils.java:254)
	at org.apache.slider.server.services.curator.RegistryBinderService.serviceStop(RegistryBinderService.java:81)
	at org.apache.hadoop.service.AbstractService.stop(AbstractService.java:221)
	at org.apache.hadoop.service.ServiceOperations.stop(ServiceOperations.java:52)
	at org.apache.hadoop.service.ServiceOperations.stopQuietly(ServiceOperations.java:80)
	at org.apache.hadoop.service.CompositeService.stop(CompositeService.java:158)
	at org.apache.hadoop.service.CompositeService.serviceStop(CompositeService.java:131)
	at org.apache.hadoop.service.AbstractService.stop(AbstractService.java:221)
	at org.apache.hadoop.yarn.service.launcher.ServiceShutdownHook.run(ServiceShutdownHook.java:70)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>:</i>
<p>Looking at it more, to create this stack trace you have to call <tt>CuratorFramework.stop()</tt> ahead of <tt>ServiceDiscovery.stop()</tt> -its triggered by the ordering of shutdown -this may mean that it's the correct behaviour, but callers do need to plan for it</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>It's a user error to close the Curator connection while it's still being used elsewhere.</p>
