### ISSUE TITLE
[CURATOR-103] NPE in PathChildrenCache

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#624]
<p>On ConnectionLoss, PathChildrenCache cannot recover the connection with the following NPE</p>

<p>ERROR 2014-04-09 17:48:15,231 <span class="error">&#91;DaemonThreadFactory-2-thread-2&#93;</span> org.apache.curator.framework.imps.CuratorFrameworkImpl: Background retry gave up<br/>
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:766)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:749)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:56)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl$3.call(CuratorFrameworkImpl.java:244)<br/>
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:166)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:724)</p>

<p>INFO  2014-04-09 17:48:15,276 <span class="error">&#91;ServerInventoryView-0-EventThread&#93;</span> org.apache.curator.framework.state.ConnectionStateManager: State change: RECONNECTED<br/>
INFO  2014-04-09 17:48:15,382 <span class="error">&#91;ServerInventoryView-0-EventThread&#93;</span> org.apache.curator.framework.state.ConnectionStateManager: State change: SUSPENDED<br/>
ERROR 2014-04-09 17:48:15,748 <span class="error">&#91;DaemonThreadFactory-2-thread-2&#93;</span> org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up<br/>
java.lang.NullPointerException<br/>
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)<br/>
at com.google.common.collect.Lists$TransformingSequentialList.<init>(Lists.java:527)<br/>
at com.google.common.collect.Lists.transform(Lists.java:510)<br/>
at org.apache.curator.framework.recipes.cache.PathChildrenCache.processChildren(PathChildrenCache.java:635)<br/>
at org.apache.curator.framework.recipes.cache.PathChildrenCache.access$200(PathChildrenCache.java:68)<br/>
at org.apache.curator.framework.recipes.cache.PathChildrenCache$4.processResult(PathChildrenCache.java:476)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:686)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:659)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:783)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:749)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:56)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl$3.call(CuratorFrameworkImpl.java:244)<br/>
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:166)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:724)</p>

---
<details><summary><i>Originally reported by <a title="Jae Hyeon Bae" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=metacret">metacret</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-103" target="_blank">NPE in PathChildrenCache</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-04-12T21:55:07+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Fixed some places where background callbacks weren't checking the event result code</p>
