### ISSUE TITLE
[CURATOR-115] delayeddistributedqueue failed to sort children

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#636]
<p>i have a delayeddistributed queues to store some jobs, on startup, sometimes this issue come up:</p>

<p>recipes.queue.DistributedDelayQueue$1-QueueBuilder-5 <span class="error">&#91;ERROR&#93;</span> Exception caught in background handler<br/>
java.lang.IllegalArgumentException: Comparison method violates its general contract!<br/>
at java.util.TimSort.mergeLo(TimSort.java:747)<br/>
at java.util.TimSort.mergeAt(TimSort.java:483)<br/>
at java.util.TimSort.mergeCollapse(TimSort.java:408)<br/>
at java.util.TimSort.sort(TimSort.java:214)<br/>
at java.util.TimSort.sort(TimSort.java:173)<br/>
at java.util.Arrays.sort(Arrays.java:659)<br/>
at java.util.Collections.sort(Collections.java:217)<br/>
at org.apache.curator.framework.recipes.queue.DistributedDelayQueue$1.sortChildren(DistributedDelayQueue.java:89)<br/>
at org.apache.curator.framework.recipes.queue.DistributedQueue.runLoop(DistributedQueue.java:551)<br/>
at org.apache.curator.framework.recipes.queue.DistributedQueue.access$000(DistributedQueue.java:65)<br/>
at org.apache.curator.framework.recipes.queue.DistributedQueue$1.call(DistributedQueue.java:196)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/>
at java.lang.Thread.run(Thread.java:744)</p>

---
<details><summary><i>Originally reported by <a title="kimi" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khiemu@googlemail.com">khiemu@googlemail.com</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-115" target="_blank">delayeddistributedqueue failed to sort children</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2023-05-10T16:01:01+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Pretty sure this is occurring because the sortChildren() method does a comparison using the current time which will change as the sort is occurring. This means that it will be possible for the Comparator implementation to break it's transitivity contract (i.e If A > B and B > C then A > C). I haven't managed to reproduce the problem though, so I can't confirm that this is indeed the issue. If it is, determining the current time at the start of the sort and then using that for all comparisons should fix it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Also seems likely that this has not been noticed before because Curator is built against Java 6, and the TimSort implementation of Collections.sort() didn't come in until Java 7 (I think). So, this would not be an issue. As a work around, you can set the java.util.Arrays.useLegacyMergeSort system property to "true", and it will use a merge sort which silently ignores these inconsistencies.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khiemu@googlemail.com">khiemu@googlemail.com</a>:</i>
<p>thanx for the hint, i'll try the useLegacyMergeSort() and see if it happens</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Can you see if you can reproduce this against Curator 1.6.0? I believe that <a href="https://issues.apache.org/jira/browse/CURATOR-116" title="Ordering of delayed distributed queue is inconsistent" class="issue-link" data-issue-key="CURATOR-116"><del>CURATOR-116</del></a> should fix this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>After a look for the pr <a href="https://github.com/apache/curator/pull/13/files" class="external-link" target="_blank" rel="nofollow noopener">apache/curator#13</a>, I think it is fixed.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-116">CURATOR-116</a>]</i>
