### ISSUE TITLE
[CURATOR-117] TestingServer to detect failures of ZooKeeperMainFace to start

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#638]
<p><tt>TestingServer</tt> blocks until the ZK server is started. But if it doesn't start for some reason, the block lasts until the test run times out -which then fails the test with little in terms of meaningful messages.</p>

---
<details><summary><i>Originally reported by <a title="Steve Loughran" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-117" target="_blank">TestingServer to detect failures of ZooKeeperMainFace to start</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2015-04-20T11:09:44+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>:</i>
<p>Stack</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-quote">"main"</span> prio=5 tid=0x00007fcd5b017800 nid=0x1903 waiting on condition [0x000000010c8ff000]
   java.lang.<span class="code-object">Thread</span>.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait <span class="code-keyword">for</span>  <0x00000007ec01ab90> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
	at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:81)
	at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:144)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:75)
	at org.apache.curator.test.TestingServer.<init>(TestingServer.java:68)
	at org.apache.hadoop.yarn.registry.AbstractZKRegistryTest.createZKServer(AbstractZKRegistryTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.jav
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>:</i>
<p>This could be done with the countdown latch waiting for a time period, but better may be for the ZK startup thread to signal the service as started even when it throws an exception -and then for <tt>TestingServer.start()</tt> to pick that up and relay it to the JUnit thread.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Is this still an issue?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stevel@apache.org">stevel@apache.org</a>:</i>
<p>Not been doing builds which come up against it; I'll close as CannotReproduce until it surfaces again</p>
