### ISSUE TITLE
[CURATOR-121] PathChildrenCache is throwing an InterruptedException when being closed

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#642]
<p>I have a server which is using the PathChildrenCache with the LeaderSelector so that I can keep track of changes in leadership for a particular znode. Upon closing the PathChildrenCache, I intermittently receive an InterruptedException like the following:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.InterruptedException

at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1038)

at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)

at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:282)

at org.apache.curator.CuratorZookeeperClient.internalBlockUntilConnectedOrTimedOut(CuratorZookeeperClient.java:324)

at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:105)

at org.apache.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:140)

at org.apache.curator.utils.EnsurePath.ensure(EnsurePath.java:99)

at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:481)

at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35)

at org.apache.curator.framework.recipes.cache.PathChildrenCache$10.run(PathChildrenCache.java:762)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)

at java.util.concurrent.FutureTask.run(FutureTask.java:166)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)

at java.util.concurrent.FutureTask.run(FutureTask.java:166)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:724)

</pre>
</div></div>

<p>It doesn't happen all the time but it does happen about 2-3 times in a test suite that's creating and stopping the server about 60 times total.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> mentioned on the mailing list that this may be a bug in the framework.</p>

---
<details><summary><i>Originally reported by <a title="Corey J. Nolet" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sonixbp">sonixbp</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-121" target="_blank">PathChildrenCache is throwing an InterruptedException when being closed</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Cam McKenzie" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-07-21T01:43:14+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>When you say 'I intermittently receive an InterruptedException like the following', you mean that this is appearing in your logs? Or that your code is receiving the exception.</p>

<p>I presume that it's the former. It appears to be because the PathChildrenCache's offerOperation method interprets all exceptions in the same manner (just logs them).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/18" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/18</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-121" title="PathChildrenCache is throwing an InterruptedException when being closed" class="issue-link" data-issue-key="CURATOR-121"><del>CURATOR-121</del></a> - Modified exception handling on the operation queue</p>

<p>    Modified exception handling on the operation queue to ignore InterruptedException during shutdown. Added additional unit test for this case.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-121" title="PathChildrenCache is throwing an InterruptedException when being closed" class="issue-link" data-issue-key="CURATOR-121"><del>CURATOR-121</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/18.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/18.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #18</p>

<hr />
<p>commit 51109813ebd3104b74181be26532c3692f41bb02<br/>
Author: Cam McKenzie <cammckenzie@apache.org><br/>
Date:   2014-07-19T18:10:32Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-121" title="PathChildrenCache is throwing an InterruptedException when being closed" class="issue-link" data-issue-key="CURATOR-121"><del>CURATOR-121</del></a> - Modified exception handling on the operation queue to<br/>
    ignore InterruptedException during shutdown. Added additional unit test<br/>
    for this case.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/18#discussion_r15152791" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/18#discussion_r15152791</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java &#8212;<br/>
    @@ -761,6 +761,15 @@ public void run()<br/>
 operationsQuantizer.remove(operation);<br/>
 operation.invoke();<br/>
     }<br/>
    +catch ( InterruptedException e )<br/>
    +{<br/>
    +    //We expect to get interrupted during shutdown,<br/>
    &#8212; End diff &#8211;</p>

<p>    when catching InterruptedException, the thread interrupted status must be reset via:</p>

<p>    ```java<br/>
    Thread.currentThread().interrupt()<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/18#issuecomment-49563625" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/18#issuecomment-49563625</a></p>

<p>    Other than my comment, LGTM</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/18" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/18</a></p>
