### ISSUE TITLE
[CURATOR-149] ChildData's path check prevents the initialization of PathChildrenCache class

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#670]
<p>PathChildrenCache has a static field:</p>

<p>    private static final ChildData NULL_CHILD_DATA = new ChildData(null, null, null);</p>

<p>But this can't be created because of:</p>

<p>Caused by: java.lang.IllegalArgumentException: Path cannot be null<br/>
    at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:48)<br/>
    at org.apache.curator.framework.recipes.cache.ChildData.<init>(ChildData.java:34)<br/>
    at org.apache.curator.framework.recipes.cache.PathChildrenCache.<clinit>(PathChildrenCache.java:90)<br/>
    ... 31 more</p>

---
<details><summary><i>Originally reported by <a title="Nandor Kracser" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bonifaido">bonifaido</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-149" target="_blank">ChildData's path check prevents the initialization of PathChildrenCache class</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2014-10-14T04:11:49+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>This has been fixed independently as part of <a href="https://issues.apache.org/jira/browse/CURATOR-136" title="Invalid LeaderLatch path never errors" class="issue-link" data-issue-key="CURATOR-136"><del>CURATOR-136</del></a>. Commit is 63444f6a2273bd910b33ecb10d1106cb2225e4fb</p>
