### ISSUE TITLE
[CURATOR-157] Avoid stack traces closing PathChildrenCache followed by closing CuratorFramework

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#678]
<p>When closing PathChildrenCache, and immediately afterwards closing CuratorFramework, some ERROR-level stack traces are logged.</p>

<p>This was previously reported on the mailing list: <a href="http://curator.markmail.org/thread/bmfr62ekx5p2vv7f" class="external-link" target="_blank" rel="nofollow noopener">http://curator.markmail.org/thread/bmfr62ekx5p2vv7f</a></p>

<p>The cause is that the BackgroundCallback defined in PathChildrenCache.refresh() will, when triggered, perform some more ZooKeeper operations.</p>

<p>Thus one can get in sequences such as:</p>
<ul>
	<li>operation with BackgroundCallback is submitted</li>
	<li>processResult of the BackgroundCallback is called</li>
	<li>PathChildrenCache is closed</li>
	<li>CuratorFramework is closed</li>
	<li>processResult, which is running on another thread, comes to the point it does operations on ZooKeeper, which fail because ZooKeeper is closed.</li>
</ul>

<p>There is no real impact on the application, it is just for log-esthetical reasons that I'd like to avoid it.</p>

<p>In the more common case, the processResult will receive an IllegalStateException, which could be easily catched and ignored in PathChildrenCache if the PathChildrenCache is closed:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>14/10/30 11:24:51 ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:360)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.getDataAndStat(PathChildrenCache.java:545)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.processChildren(PathChildrenCache.java:668)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.access$200(PathChildrenCache.java:68)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$4.processResult(PathChildrenCache.java:490)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:715)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:502)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
</pre>
</div></div>

<p>But sometimes it also fails with other async operations deeper down:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>14/10/30 11:24:51 ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: Client is not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:113)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:474)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.performBackgroundOperation(GetDataBuilderImpl.java:263)
	at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:65)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:789)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:487)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:275)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:41)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.getDataAndStat(PathChildrenCache.java:545)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.processChildren(PathChildrenCache.java:668)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.access$200(PathChildrenCache.java:68)
	at org.apache.curator.framework.recipes.cache.PathChildrenCache$4.processResult(PathChildrenCache.java:490)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:715)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:502)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
</pre>
</div></div>

<p>Therefore I have created a patch where PathChildrenCache.close() will wait until the possibly running BackgroundCallback is finished.</p>

<p>I will also attach a small class that illustrates the problem.</p>

---
<details><summary><i>Originally reported by <a title="Bruno Dumon" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bruno">bruno</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-157" target="_blank">Avoid stack traces closing PathChildrenCache followed by closing CuratorFramework</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bruno">bruno</a>:</i>
<p>While adapting my patch for master (I was working on 2.6.0), I see the current code already contains a change that makes the situation somewhat less likely, as it checks this in processResult:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>    if (PathChildrenCache.this.state.get().equals(State.CLOSED)) {
// This ship is closed, don't handle the callback
return;
    }
</pre>
</div></div>

<p>this makes it occure less often, but doesn't avoid the problem entirely.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user bdumon opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-157" title="Avoid stack traces closing PathChildrenCache followed by closing CuratorFramework" class="issue-link" data-issue-key="CURATOR-157">CURATOR-157</a> Avoid stack traces on close</p>

<p>    Avoid error-level stack traces closing PathChildrenCache followed by closing CuratorFramework</p>

<p>    See details in jira: <a href="https://issues.apache.org/jira/browse/CURATOR-157" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-157</a></p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/bdumon/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/bdumon/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-157" title="Avoid stack traces closing PathChildrenCache followed by closing CuratorFramework" class="issue-link" data-issue-key="CURATOR-157">CURATOR-157</a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/51.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #51</p>

<hr />
<p>commit 5ca022d2196f1b763043235fbdec439c1769fa9d<br/>
Author: Bruno Dumon <bruno@ngdata.com><br/>
Date:   2014-10-30T11:05:51Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-157" title="Avoid stack traces closing PathChildrenCache followed by closing CuratorFramework" class="issue-link" data-issue-key="CURATOR-157">CURATOR-157</a> Avoid stack traces on close</p>

<p>    Avoid error-level stack traces closing PathChildrenCache followed by closing CuratorFramework</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bruno">bruno</a>:</i>
<p>Patch submitted via github: <a href="https://github.com/apache/curator/pull/51" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#discussion_r19606266" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#discussion_r19606266</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java &#8212;<br/>
    @@ -382,6 +383,11 @@ public void close() throws IOException<br/>
 connectionStateListener = null;<br/>
 childrenWatcher = null;<br/>
 dataWatcher = null;<br/>
    +<br/>
    +    synchronized (backgroundTaskMonitor) {<br/>
    &#8212; End diff &#8211;</p>

<p>    Can you explain why this works in a little bit more detail? My immediate intuition is that the compiler/JIT would optimize an empty synchronized block out of the code.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user bdumon commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#discussion_r19611104" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#discussion_r19611104</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java &#8212;<br/>
    @@ -382,6 +383,11 @@ public void close() throws IOException<br/>
 connectionStateListener = null;<br/>
 childrenWatcher = null;<br/>
 dataWatcher = null;<br/>
    +<br/>
    +    synchronized (backgroundTaskMonitor) {<br/>
    &#8212; End diff &#8211;</p>

<p>    An empty synchronized block is not like an empty if statement or such, since "getting the lock" is a meaningful operation by itself. This being said, I could rewrite it to use an java.util.concurrent Lock object, or maybe something else?</p>

<p>    At a high level, my change will make the close() method wait until a potentially running background refresh operation has finished (and it also assures that no new refresh can start after the close method has returned). I guess this should be fine, though it could cause some delay on the close() in case of very large caches. This could be avoided by extra is-closed checks in the for-loop in processChildren(). I didn't consider this earlier, I can add it to my patch.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#discussion_r19614037" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#discussion_r19614037</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java &#8212;<br/>
    @@ -382,6 +383,11 @@ public void close() throws IOException<br/>
 connectionStateListener = null;<br/>
 childrenWatcher = null;<br/>
 dataWatcher = null;<br/>
    +<br/>
    +    synchronized (backgroundTaskMonitor) {<br/>
    &#8212; End diff &#8211;</p>

<p>    I'm still not sure I follow the logic, sorry. What is the benefit of making the close method wait before returning? It seems like you would need to acquire the lock earlier in the method to have an impact on control flow.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user bdumon commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#discussion_r19621734" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#discussion_r19621734</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java &#8212;<br/>
    @@ -382,6 +383,11 @@ public void close() throws IOException<br/>
 connectionStateListener = null;<br/>
 childrenWatcher = null;<br/>
 dataWatcher = null;<br/>
    +<br/>
    +    synchronized (backgroundTaskMonitor) {<br/>
    &#8212; End diff &#8211;</p>

<p>    No problem, there might a problem in my reasoning, which is as follows: a refresh might be going on when PathChildrenCache.close() is called. The refresh runs on a background thread, the ZK event thread if I'm not mistaken. Since the processResult will be running within a synchronized block, the PathChildrenCache.close() method will not be able to return until the processResult is finished, since it tries to acquire the same lock.</p>

<p>    The second synchronized block in refresh(), around the statements "if-closed-return, getChildren()..." is for similar reasons: the if-closed in that block might be called before the closed state is set, while the getChildren might be launched afterwards, but by then zookeeper might already be closed as well. By putting it in a synchronized block, we are sure no ZooKeeper operation is going on after returning from the close() method, and CuratorFramework/ZooKeeper can be closed without causing errors to be logged.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-73259604" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-73259604</a></p>

<p>    Looks like I neglected to respond to this for a while. Here is why I think the logic is faulty.</p>

<p>    T2: `processResult()` method entry<br/>
    T2: `synchronized (backgroundTaskMonitor)` acquire lock<br/>
    T2: `if (state.get().equals(State.CLOSED)) { }` evaluates false<br/>
    T1: `close()` method entry<br/>
    T1: `if ( state.compareAndSet(State.STARTED, State.CLOSED) )` evaluates true<br/>
    T1: `listeners.clear()`<br/>
    T1:  `client.getConnectionStateListenable().removeListener(connectionStateListener)`<br/>
    T1 suspends waiting for the lock<br/>
    T2: `processBackgroundResult(event)` gets called on a closed connection</p>

<p>    I think the solution is to put all of the `close()` method into the `synchronized` block, but that is not a super appealing answer. Maybe it will be fine though.</p>

<p>    The other concern is that now we can only process a single background event at a time, which seems like it could be a pretty high price to pay.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user bdumon commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-74473597" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-74473597</a></p>

<p>    I follow your reasoning, until the last event:</p>

<p>    T2: processBackgroundResult(event) gets called on a closed connection</p>

<p>    There is no connection closed by NodeCache or PathChildrenCache. The point of the patch is that after NodeCache/PathChildrenCache.close() returns, they won't be making use of the ZK connection anymore, so that CuratorFramework.close() can be called without causing stacktraces.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user bdumon commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-74829158" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-74829158</a></p>

<p>    Hmm, I don't see any such check? Is this in NodeCache or PathChildrenCache?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-74895065" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-74895065</a></p>

<p>    In the JIRA issue, the example trace came from `GetChildrenBuilderImpl` line 166.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user bdumon commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-75036380" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-75036380</a></p>

<p>    In those stack traces, it is CuratorFramework/CuratorZookeeperClient which check if their state is started (which is stil true, since we have not closed them, we have closed the cache), not NodeCache/PathChildrenCache.</p>

<p>    Or are you referring to something else?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hdeadman commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/51#issuecomment-173025262" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/51#issuecomment-173025262</a></p>

<p>    What's the status on this pull request? It looks like @bdumon added a test. Is the issue that there are branch conflicts? Does the error not happen in 3.0? I am getting it on 2.9.1 if I use a try block that relies on the Closable interface. </p>

**Comment by linghengqian** [comment]
- So, what happened to the PR for the original issue? It seems the bot lost the PR while migrating the Jira issue?
- I noticed this issue at https://github.com/apache/shardingsphere-elasticjob/pull/2544 .
- Update: Aha, I noticed https://github.com/apache/curator/pull/51 .
