### ISSUE TITLE
[CURATOR-165] LeaderLatch.checkLeadership(LeaderLatch.java:478) will throw a exception, then no leader will be elected.

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#686]
<p>We use curator for leader election within our 2 clients, sometimes none of the 2 clients was a leader.<br/>
We checked the log and found this caused by a exception which was being throwed in method LeaderLatch.checkLeadership(), after throwing this exception the curator won't do the leader election. Here is error log:</p>

<p>ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | java.lang.IllegalArgumentException: Path must start with / character<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:53)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.utils.ZKPaths.getNodeFromPath(ZKPaths.java:56)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:478)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch.access$500(LeaderLatch.java:60)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch$6.processResult(LeaderLatch.java:536)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:730)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:516)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)</p>

---
<details><summary><i>Originally reported by <a title="zhaogang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang">zhaogang</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-165" target="_blank">LeaderLatch.checkLeadership(LeaderLatch.java:478) will throw a exception, then no leader will be elected.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-04-21T02:18:48+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I think this might be the same issue as described in <a href="https://issues.apache.org/jira/browse/CURATOR-136" title="Invalid LeaderLatch path never errors" class="issue-link" data-issue-key="CURATOR-136"><del>CURATOR-136</del></a>. <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang" class="user-hover" rel="zhaogang">zhaogang</a> - is there any chance you can upgrade to 2.7.0 and see if that fixes your problem?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang">zhaogang</a>:</i>
<p>Our path is "/api/leaders", our leader launch was being created under this path which start with "/" indeed, i don't know why its exception prompted "Path must start with / character".<br/>
If you can help me i will appreciate greatly, thaks! </p>

<p>Here is our code:</p>

<p>String     leadersPath = "/api/leaders";<br/>
CuratorFramework  client = getCuratorClient();<br/>
String serverId = "1";</p>

<p>LeaderLatch leaderLatch =  new LeaderLatch(client,leadersPath,serverId);<br/>
		LeaderLatchListener latchListener = new LeaderLatchListener() {  <br/>
		    @Override  <br/>
		    public void isLeader() </p>
{  
		    	clusterCallbackService.onBecameLeader(basePath, serverId);
		    }
<p>  </p>

<p>		    @Override  <br/>
		    public void notLeader() </p>
{  
		    	clusterCallbackService.onLoseLeader(basePath, serverId);
		    }
<p>  <br/>
		};  <br/>
leaderLatch.addListener(latchListener);<br/>
leaderLatch.start();</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang">zhaogang</a>:</i>
<p>This error occured at the time when the client lost connection and reconnected to the zookeeper again, here is detail logs:</p>

<p>sing socket connection and attempting reconnect<br/>
INFO   | jvm 1    | 2014/10/30 00:24:38 | 30 Oct 2014 00:24:38 INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED<br/>
INFO   | jvm 1    | 2014/10/30 00:24:38 | 30 Oct 2014 00:24:38 INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | 30 Oct 2014 00:24:39 INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.67.90.141/10.67.90.141:2181. Will not attempt to authenticate using SASL (unknown error)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | 30 Oct 2014 00:24:39 WARN  org.apache.zookeeper.ClientCnxn - Session 0x1489e3e9cce0011 for server null, unexpected error, closing socket connection and attempting reconnect<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | java.net.ConnectException: Connection refused<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:701)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | 30 Oct 2014 00:24:39 INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.67.90.141/10.67.90.141:2181. Will not attempt to authenticate using SASL (unknown error)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | 30 Oct 2014 00:24:39 WARN  org.apache.zookeeper.ClientCnxn - Session 0x2487088d7080011 for server null, unexpected error, closing socket connection and attempting reconnect<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 | java.net.ConnectException: Connection refused<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:701)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:39 |       at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.67.90.142/10.67.90.142:2181. Will not attempt to authenticate using SASL (unknown error)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 10.67.90.142/10.67.90.142:2181, initiating session<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 10.67.90.142/10.67.90.142:2181, sessionid = 0x1489e3e9cce0011, negotiated timeout = 40000<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: RECONNECTED<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.67.90.142/10.67.90.142:2181. Will not attempt to authenticate using SASL (unknown error)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 10.67.90.142/10.67.90.142:2181, initiating session<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 10.67.90.142/10.67.90.142:2181, sessionid = 0x2487088d7080011, negotiated timeout = 40000<br/>
INFO   | jvm 1    | 2014/10/30 00:24:40 | 30 Oct 2014 00:24:40 INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: RECONNECTED<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:42 | send a packet PING : ping 00fc2c4f<br/>
INFO   | jvm 1    | 2014/10/30 00:24:42 | WrapperManager Debug: Received a packet PING : ping 00fc2c4f<br/>
INFO   | jvm 1    | 2014/10/30 00:24:42 | WrapperManager Debug: Send a packet PING : ping 00fc2c4f<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:42 | read a packet PING : ping 00fc2c4f<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:46 | send a packet PING : ping 00fc2c78<br/>
INFO   | jvm 1    | 2014/10/30 00:24:46 | WrapperManager Debug: Received a packet PING : ping 00fc2c78<br/>
INFO   | jvm 1    | 2014/10/30 00:24:46 | WrapperManager Debug: Send a packet PING : ping 00fc2c78<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:46 | read a packet PING : ping 00fc2c78<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 | 30 Oct 2014 00:24:49 ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 | java.lang.IllegalArgumentException: Path must start with / character<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:53)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.utils.ZKPaths.getNodeFromPath(ZKPaths.java:56)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:478)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.recipes.leader.LeaderLatch.access$500(LeaderLatch.java:60)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.recipes.leader.LeaderLatch$6.processResult(LeaderLatch.java:536)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:730)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:516)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)<br/>
INFO   | jvm 1    | 2014/10/30 00:24:49 |       at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:50 | send a packet PING : ping 00fc2ca1<br/>
INFO   | jvm 1    | 2014/10/30 00:24:50 | WrapperManager Debug: Received a packet PING : ping 00fc2ca1<br/>
INFO   | jvm 1    | 2014/10/30 00:24:50 | WrapperManager Debug: Send a packet PING : ping 00fc2ca1<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:50 | read a packet PING : ping 00fc2ca1<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:54 | send a packet PING : ping 00fc2cca<br/>
INFO   | jvm 1    | 2014/10/30 00:24:54 | WrapperManager Debug: Received a packet PING : ping 00fc2cca<br/>
INFO   | jvm 1    | 2014/10/30 00:24:54 | WrapperManager Debug: Send a packet PING : ping 00fc2cca<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:54 | read a packet PING : ping 00fc2cca<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:58 | send a packet PING : ping 00fc2cf3<br/>
INFO   | jvm 1    | 2014/10/30 00:24:59 | WrapperManager Debug: Received a packet PING : ping 00fc2cf3<br/>
INFO   | jvm 1    | 2014/10/30 00:24:59 | WrapperManager Debug: Send a packet PING : ping 00fc2cf3<br/>
DEBUG  | wrapperp | 2014/10/30 00:24:59 | read a packet PING : ping 00fc2cf3<br/>
DEBUG  | wrapperp | 2014/10/30 00:25:03 | send a packet PING : ping 00fc2d1c<br/>
INFO   | jvm 1    | 2014/10/30 00:25:03 | WrapperManager Debug: Received a packet PING : ping 00fc2d1c<br/>
INFO   | jvm 1    | 2014/10/30 00:25:03 | WrapperManager Debug: Send a packet PING : ping 00fc2d1c<br/>
DEBUG  | wrapperp | 2014/10/30 00:25:03 | read a packet PING : ping 00fc2d1c<br/>
DEBUG  | wrapperp | 2014/10/30 00:25:07 | send a packet PING : ping 00fc2d45<br/>
INFO   | jvm 1    | 2014/10/30 00:25:07 | WrapperManager Debug: Received a packet PING : ping 00fc2d45<br/>
INFO   | jvm 1    | 2014/10/30 00:25:07 | WrapperManager Debug: Send a packet PING : ping 00fc2d45</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-168">CURATOR-168</a>]</i>
