### ISSUE TITLE
[CURATOR-167] All registered watchers should be cleared on close

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#688]
<p>There's a memory leak in NodeCache.  I was able to reliably reproduce the problem using a very simple test that performs the following:</p>

<p>1) Creates a CuratorFramework instance and starts it.<br/>
2) in a loop:  Creates a NodeCache and starts it, then closes it.</p>

<p>Eventually you get a java.lang.OutOfMemoryError:  Java heap space.  This happens regardless of the heap size, though it happens much faster with a small heap.</p>

<p>Upon furher investigation w/ a profiler, I can see that each NodeCache is being referenced by the NamespaceWatcherMap.</p>

<p>Here's the test code:</p>

<div class="code panel" style="border-style: solid;border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;border-bottom-style: solid;"><b>NodeCacheLeakTest.java</b></div><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">import</span> java.util.Date;

<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFramework;
<span class="code-keyword">import</span> org.apache.curator.framework.CuratorFrameworkFactory;
<span class="code-keyword">import</span> org.apache.curator.framework.recipes.cache.NodeCache;
<span class="code-keyword">import</span> org.apache.curator.retry.ExponentialBackoffRetry;

<span class="code-keyword">public</span> <span class="code-keyword">class </span>NodeCacheLeakTest {

	<span class="code-keyword">public</span> <span class="code-keyword">static</span> void main(<span class="code-object">String</span>[] args) <span class="code-keyword">throws</span> Exception {

		<span class="code-object">String</span> zkConnect;
		<span class="code-keyword">if</span> (args.length > 0 && args[0] != <span class="code-keyword">null</span>)
			zkConnect = args[0];
		<span class="code-keyword">else</span>
			zkConnect = <span class="code-quote">"localhost:2181/test"</span>;

		CuratorFramework curator = CuratorFrameworkFactory.newClient(zkConnect,
				<span class="code-keyword">new</span> ExponentialBackoffRetry(500, 10));
		curator.start();

		<span class="code-object">int</span> count = 0;
		<span class="code-keyword">while</span> (<span class="code-keyword">true</span>) {
			<span class="code-object">String</span> nodePath = <span class="code-quote">"/foo/node-"</span> + (count);

			NodeCache cache = <span class="code-keyword">new</span> NodeCache(curator, nodePath);
			cache.start(<span class="code-keyword">true</span>);
			cache.close();

			count++;

			<span class="code-keyword">if</span> (count % 1000 == 0)
				<span class="code-object">System</span>.out.println(<span class="code-keyword">new</span> Date() + <span class="code-quote">" Started and Closed "</span> + count
						+ <span class="code-quote">" NodeCache instances"</span>);
		}
	}
}
</pre>
</div></div>

<p>And here's the output/OOM Error when using (-Xms10m -Xmx10m -XX:+UseG1GC):</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>log4j:WARN No appenders could be found for logger (org.apache.curator.framework.imps.CuratorFrameworkImpl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tue Nov 18 15:59:12 GMT+00:00 2014 Started and Closed 1000 NodeCache instances
Tue Nov 18 15:59:16 GMT+00:00 2014 Started and Closed 2000 NodeCache instances
Tue Nov 18 15:59:20 GMT+00:00 2014 Started and Closed 3000 NodeCache instances
Tue Nov 18 15:59:23 GMT+00:00 2014 Started and Closed 4000 NodeCache instances
Tue Nov 18 15:59:27 GMT+00:00 2014 Started and Closed 5000 NodeCache instances
Tue Nov 18 15:59:31 GMT+00:00 2014 Started and Closed 6000 NodeCache instances
Tue Nov 18 15:59:36 GMT+00:00 2014 Started and Closed 7000 NodeCache instances
Tue Nov 18 15:59:40 GMT+00:00 2014 Started and Closed 8000 NodeCache instances
Tue Nov 18 15:59:45 GMT+00:00 2014 Started and Closed 9000 NodeCache instances
Tue Nov 18 15:59:49 GMT+00:00 2014 Started and Closed 10000 NodeCache instances
Tue Nov 18 16:00:01 GMT+00:00 2014 Started and Closed 11000 NodeCache instances
java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88)
	at java.io.PrintStream.<init>(PrintStream.java:112)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at org.apache.jute.CsvOutputArchive.<init>(CsvOutputArchive.java:57)
	at org.apache.zookeeper.proto.RequestHeader.toString(RequestHeader.java:62)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:815)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88)
	at java.io.PrintStream.<init>(PrintStream.java:112)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at org.apache.jute.CsvOutputArchive.<init>(CsvOutputArchive.java:57)
	at org.apache.zookeeper.proto.RequestHeader.toString(RequestHeader.java:62)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:815)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88)
	at java.io.PrintStream.<init>(PrintStream.java:112)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at org.apache.jute.CsvOutputArchive.<init>(CsvOutputArchive.java:57)
	at org.apache.zookeeper.proto.RequestHeader.toString(RequestHeader.java:62)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:815)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88)
	at java.io.PrintStream.<init>(PrintStream.java:112)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at org.apache.jute.CsvOutputArchive.<init>(CsvOutputArchive.java:57)
	at org.apache.zookeeper.proto.RequestHeader.toString(RequestHeader.java:62)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:308)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:815)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
</pre>
</div></div>

<p>Additional Notes:</p>
<ul>
	<li>When I don't specify the G1 collector I still get OutOfMemoryErrors, only the cause is "GC overhead limit exceeded".  
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88)
	at java.io.PrintStream.<init>(PrintStream.java:112)
	at java.io.PrintStream.<init>(PrintStream.java:175)
	at org.apache.jute.CsvOutputArchive.<init>(CsvOutputArchive.java:57)
	at org.apache.zookeeper.proto.GetDataRequest.toString(GetDataRequest.java:62)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$Packet.toString(ClientCnxn.java:310)
	at java.lang.String.valueOf(String.java:2854)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:815)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:94)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)</pre>
</div></div></li>
	<li>This has been around for a while as I first noticed it with v1.3.3.  I upgraded to v2.6.0 and re-ran the test, but as you can see this still appears to be an issue.</li>
	<li>I ran this test on a x86_64 Ubuntu 10.043 system and observed the same behavior</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Craig McNally" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcnallyc">mcnallyc</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-167" target="_blank">All registered watchers should be cleared on close</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Cam McKenzie" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-08-26T06:34:07+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Thanks for the report!  Do you have / are you working on a fix already?  If not I can take a look.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcnallyc">mcnallyc</a>:</i>
<p>Unfortunately I do not have a fix.  Thanks in advance for your help.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I just tried running this as a JUnit test against the latest trunk, and did not see the same behaviour.</p>

<p>I am running on a Ubuntu 14.04 system, with Java 7. I set the heap size to 32m because Maven and Surefire needed a bit more room to start up, and monitoring via JVisualVM I saw cyclical heap growth and then GC returning the heap size to the normal level.</p>

<p>Looks like you've got your work cut out for you, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth" class="user-hover" rel="dragonsinth">Scott Blum</a>. Let me know if I can help with testing in any way.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I can reproduce the problem on a WIndows 7 box running Java 1.6</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Looking briefly at the code, it would seem that this is probably just because the NamespaceWatcherMap is holding references to all of the Watcher references that are created by the NodeCache (which being an inner class will hold a reference to the NodeCache itself). This means that a bunch of objects are not going to be cleaned up the GC. I'm not sure what the solution is though. Maybe the NodeCache needs to keep track of all of its Watcher references and ask for them to be removed from the NamespaceWatcherMap when it closes. The NamespaceWatcherMap is hidden under a few layers of abstraction though, so it's not going to be very clean!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>We can try adding a call to clearWatcherReferences()</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Yep, had a brief look through the ZK client code, it would seem that data, exists and child watches are stored in a series of HashMap's in the client. So, this test is possibly a bit bogus, because there's no chance of any of the watches firing which would result in them being removed (because the NodeCache has been closed and won't reregister the watch). I'll make sure that if the watches fire that they do get cleared.</p>

<p>This may be something that needs to be fixed as part of the Curator support for ZK 3.5.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Ok, so if I modify the test slightly to make sure that the watches fire, then they get cleared as expected. This issue is not specific to NodeCache (there are already 2 other memory related issues <a href="https://issues.apache.org/jira/browse/CURATOR-14" title="Memory leak in Curator watches" class="issue-link" data-issue-key="CURATOR-14">CURATOR-14</a> and <a href="https://issues.apache.org/jira/browse/CURATOR-105" title="Memory leak when using PathChildrenCache" class="issue-link" data-issue-key="CURATOR-105"><del>CURATOR-105</del></a>). The issue could be minimized (which I believe <a href="https://issues.apache.org/jira/browse/CURATOR-14" title="Memory leak in Curator watches" class="issue-link" data-issue-key="CURATOR-14">CURATOR-14</a> was trying to do) by caching identical watches in Curator), but for the pathological case (like this test exhibits) where a new node is used for each watch, a watcher cache would not work.</p>

<p>I think that we need to fix this with ZK 3.5 where we can actually remove watches.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Still seems like we could clean up unreferenced client side watches, to solve the case of starting and stopping caches that look at the same paths.  For that case, the server will limit you to 1 watch per client per node anyway.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth" class="user-hover" rel="dragonsinth">Scott Blum</a> good point. We should still fix the close() method to call into clearWatcherReferences() to clean up the Curator side of things. This will require a small amount of shenanigans though, as the watcher used by NodeCache is a CuratorWatcher and the clearWatcherReferences() call exposed by the CuratorFramework interface currently only supports ZK Watcher objects (which share no base class with CuratorWatcher).</p>

<p>So, do we expose a second clearWatcherReferences() method? Or does anyone have another suggestion? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I would just change the watcher to a normal Watcher.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Ok. Will sort out a fix</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user cammckenzie opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/55" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-167" title="All registered watchers should be cleared on close" class="issue-link" data-issue-key="CURATOR-167"><del>CURATOR-167</del></a> - Partial fix to clean up Curator managed watch objects</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-167" title="All registered watchers should be cleared on close" class="issue-link" data-issue-key="CURATOR-167"><del>CURATOR-167</del></a> - Partial fix to clean up Curator managed watch objects whenthe cache closes. A full fix requires the ability to cancel watches in ZK which is not available until ZK 3.5</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-167" title="All registered watchers should be cleared on close" class="issue-link" data-issue-key="CURATOR-167"><del>CURATOR-167</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/55.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #55</p>

<hr />
<p>commit 44c3891e3e1633e456c530165513fff50a52a8b4<br/>
Author: Cameron McKenzie <cameron@unico.com.au><br/>
Date:   2014-11-19T03:23:24Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-167" title="All registered watchers should be cleared on close" class="issue-link" data-issue-key="CURATOR-167"><del>CURATOR-167</del></a> - Partial fix to clean up Curator managed watch objects when<br/>
    the cache closes. A full fix requires the ability to cancel watches in<br/>
    ZK which is not available until ZK 3.5</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/55#issuecomment-63597770" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55#issuecomment-63597770</a></p>

<p>    No unit tests yet, couldn't think of a good way of testing without having a test that ran for a long time. I guess an option is to look at the size of the watcher cache, but it's not super accessible (I guess you could get at it with some reflection shenanigans).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dragonsinth commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/55#issuecomment-63598493" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55#issuecomment-63598493</a></p>

<p>    BTW: do PathChildrenCache and TreeCache have similar issues?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcnallyc">mcnallyc</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth" class="user-hover" rel="dragonsinth">Scott Blum</a>, looks like a similar problem was already identified and fixed for PathChildrenCache.  See <a href="https://issues.apache.org/jira/browse/CURATOR-105" class="external-link" rel="nofollow">CURATOR-105</a>.  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dragonsinth commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/55#issuecomment-63698639" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55#issuecomment-63698639</a></p>

<p>    It looks like TreeCache might be fine here.<br/>
    ```<br/>
    TreeCache.close() -> TreeCacheNode.wasDeleted() <span class="error">&#91;recursively&#93;</span> -> client.clearWatcherReferences(this)<br/>
    ```</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/55#issuecomment-63719163" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55#issuecomment-63719163</a></p>

<p>    Yep, I think you're right, should be ok.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcnallyc">mcnallyc</a>:</i>
<p>Just curious if there's been any progress on this...  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I've lost track of this. This is marked as being for Curator 3.0 but it's not ZK 3.5.x dependent is it? Also, the PR looks like it can be merged. What's left here?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I made some changes that minimised the memory leaking as much as possible, but it can't stop it completely because we can't clear watches until ZK 3.5. What's there can be merged though once it's been reviewed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I'll create a new issue for using the 3.5.x clear watchers API.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Are we going to drop this in favor of the complete solution for 3.5?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>+1 on that. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> - Can you make sure that the PR is current and then merge what we can fix?</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> - What is the JIRA for the fix using the clear watchers API?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p><a href="https://issues.apache.org/jira/browse/CURATOR-217" title="Use new Watcher Removal APIs in Curator Recipes" class="issue-link" data-issue-key="CURATOR-217"><del>CURATOR-217</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Sorry for being dumb, can someone give me the short version of why NodeCache would have this problem, but TreeCache and PathChildrenCache would not?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth" class="user-hover" rel="dragonsinth">Scott Blum</a> <a href="https://issues.apache.org/jira/browse/CURATOR-105" title="Memory leak when using PathChildrenCache" class="issue-link" data-issue-key="CURATOR-105"><del>CURATOR-105</del></a> was raised against PathChildrenCache which has been fixed.</p>

<p>TreeCache is ok because it calls clearWatcherReferences when close() is called. (close() calls wasDeleted() which calls clearWatcherReferences).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Gotcha.  Does that mean there's a tactical fix to NodeCache that doesn't need to wait for 3.0?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Nevermind, just saw your branch.  Cool!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>So, can this be closed now?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I still need to merge it into master. Running the unit tests broke (though<br/>
not due to this merge), so I haven't pushed the merge yet. Should I just<br/>
merge regardless, since the errors are unrelated?</p>

<p>On Wed, Aug 26, 2015 at 2:46 PM, Jordan Zimmerman (JIRA) <jira@apache.org></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>If the test breakage is unrelated to this then, yes. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/55" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/55</a></p>
