### ISSUE TITLE
[CURATOR-168] Background protected mode incorrectly sets Event name to just ZNode name. Should be full path.

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#689]
<p>We use LeaderLatch for leader election within our several zookeeper clients,but sometimes our leaderLatch stopped to work due to a error "Background exception was not retry-able or retry gave up java.lang.IllegalArgumentException: Path must start with / characte".</p>

<p>To found the reason we tracked the execution of program in class LeaderLatch with debug mode,we found the code "setNode(event.getName());"  in line 487 of LeaderLatch.class in which "event.getName()" code sometimes didn't return the full path of the znode but only return the last part of the full path,like "_c_b1097329-4a77-493b-806c-5c888067eeab-latch-0000004068", but the full path should be "/api1/leaders/_c_b1097329-4a77-493b-806c-5c888067eeab-latch-0000004068".</p>

<p>So  the when event.getName()=="_c_b1097329-4a77-493b-806c-5c888067eeab-latch-0000004068", the program will fail to go through the codes below:<br/>
1.LeaderLatch.checkLeadership()  line 526<br/>
2.ZKPaths.getNodeFromPath()      line 61<br/>
3.PathUtils.validatePath(path)line 46<br/>
And then the LeaderLatch stopped to work. </p>

---
<details><summary><i>Originally reported by <a title="zhaogang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang">zhaogang</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-168" target="_blank">Background protected mode incorrectly sets Event name to just ZNode name. Should be full path.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-04-21T02:17:07+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=osmanscam">osmanscam</a>:</i>
<p> getting the same issue with curator version 4.6 as well, so highlighting that none of the fixes from 4.6 to 4.7 is causing that, here is the full stack trace</p>

<p> <span class="error">&#91;CuratorFramework-0-EventThread&#93;</span> ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up<br/>
java.lang.IllegalArgumentException: Path must start with / character<br/>
at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:53) <br/>
at org.apache.curator.utils.ZKPaths.getNodeFromPath(ZKPaths.java:56) <br/>
at org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:523)<br/>
at org.apache.curator.framework.recipes.leader.LeaderLatch.access$700(LeaderLatch.java:62) <br/>
at org.apache.curator.framework.recipes.leader.LeaderLatch$7.processResult(LeaderLatch.java:581)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:715)<br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:502)<br/>
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)<br/>
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590) <br/>
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) </p>

<p>(as it is happening quite seldom there is no testcase to reproduce this)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=osmanscam">osmanscam</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang" class="user-hover" rel="zhaogang">zhaogang</a>;</p>

<p>Could you reproduce this issue with an unit test? Do you know exactly in which use case this is happening?</p>

<p>Regards.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang" class="user-hover" rel="zhaogang">zhaogang</a>, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=osmanscam" class="user-hover" rel="osmanscam">Osman Sebati Cam</a> - Can either of you try applying the patch that I have uploaded to this JIRA and see if you get a different stack trace? I have not been able to reproduce, but this patch adds some validation earlier in the execution so we might get a better idea of where things fail.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Is this the same issue as <a href="https://issues.apache.org/jira/browse/CURATOR-165" title="LeaderLatch.checkLeadership(LeaderLatch.java:478) will throw a exception, then no leader will be elected." class="issue-link" data-issue-key="CURATOR-165"><del>CURATOR-165</del></a>?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I finally found this. It's a very very old bug indeed. It's caused by a mistake in background protected mode for node creation. If the server successfully creates a Curator-protected node by crashes before returning to the client, Curator will incorrectly set the wrong value for the name field in the background Event causing this problem.</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-165">CURATOR-165</a>]</i>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20SPARK-20884">SPARK-20884</a>]</i>
