### ISSUE TITLE
[CURATOR-172] Deadlock when performing background operation

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#693]
<p>Had a box get into a state where our ZK connections were all deadlocked, waiting on an object monitor. jstack shows that our background thread that was creating a node was waiting on a lock that was held by the CuratorFramework thread, who was waiting on an object monitor that looks like it couldn't be completed until our other write was finished (packet.finish would never return true.) </p>

<p>We have seen this happen twice, but don't notice it until afterwards, and don't have enough logging to know what's triggering it (possible ZK connections going away?) </p>

<p>Rest of the box is fine, network connections are not flapping, main IO threads continue to accept and process connections, until we get backed up waiting for ZK. </p>

<p>Here are the two stack traces:<br/>
"ZooChangeWatcher-BackgroundReader--2-1-SendThread()" daemon prio=10 tid=0x00007fcf64108000 nid=0x88d waiting for monitor entry <span class="error">&#91;0x00007fcbf5d16000&#93;</span><br/>
   java.lang.Thread.State: BLOCKED (on object monitor)<br/>
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:177)</p>
<ul class="alternate" type="square">
	<li>waiting to lock <0x00000000d526bcc8> (a org.apache.curator.ConnectionState)<br/>
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)<br/>
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:763)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:470)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInBackground(CreateBuilderImpl.java:648)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:427)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)<br/>
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.createNode(PersistentEphemeralNode.java:340)<br/>
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode.access$000(PersistentEphemeralNode.java:52)<br/>
	at org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode$4.processResult(PersistentEphemeralNode.java:224)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:686)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:659)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:479)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.sendBackgroundResponse(CreateBuilderImpl.java:526)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl.access$600(CreateBuilderImpl.java:44)<br/>
	at org.apache.curator.framework.imps.CreateBuilderImpl$6.processResult(CreateBuilderImpl.java:485)<br/>
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:602)<br/>
	at org.apache.zookeeper.ClientCnxn$EventThread.queuePacket(ClientCnxn.java:475)</li>
	<li>locked <0x00000000fa8e16f8> (a java.util.concurrent.LinkedBlockingQueue)<br/>
	at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:627)<br/>
	at org.apache.zookeeper.ClientCnxn.conLossPacket(ClientCnxn.java:645)<br/>
	at org.apache.zookeeper.ClientCnxn.access$2400(ClientCnxn.java:85)<br/>
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1160)</li>
	<li>locked <0x00000000fa8e1380> (a java.util.LinkedList)<br/>
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1109)</li>
</ul>

<p>"CuratorFramework-0" daemon prio=10 tid=0x00007fd02cb57800 nid=0x4425 in Object.wait() <span class="error">&#91;0x00007fcfc507e000&#93;</span><br/>
   java.lang.Thread.State: WAITING (on object monitor)<br/>
	at java.lang.Object.wait(Native Method)<br/>
	at java.lang.Object.wait(Object.java:503)<br/>
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1309)</p>
<ul class="alternate" type="square">
	<li>locked <0x00000000fa8e6750> (a org.apache.zookeeper.ClientCnxn$Packet)<br/>
	at org.apache.zookeeper.ClientCnxn.close(ClientCnxn.java:1281)<br/>
	at org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:677)</li>
	<li>locked <0x00000000fa8e0948> (a org.apache.zookeeper.ZooKeeper)<br/>
	at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:139)<br/>
	at org.apache.curator.HandleHolder.closeAndReset(HandleHolder.java:77)<br/>
	at org.apache.curator.ConnectionState.reset(ConnectionState.java:218)</li>
	<li>locked <0x00000000d526bcc8> (a org.apache.curator.ConnectionState)<br/>
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:194)</li>
	<li>locked <0x00000000d526bcc8> (a org.apache.curator.ConnectionState)<br/>
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)<br/>
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:763)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:749)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:56)<br/>
	at org.apache.curator.framework.imps.CuratorFrameworkImpl$3.call(CuratorFrameworkImpl.java:244)<br/>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<br/>
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)<br/>
	at java.lang.Thread.run(Thread.java:722)</li>
</ul>

<p>Help me Obi-Wan Kenobi, you're my only hope. </p>

---
<details><summary><i>Originally reported by <a title="Tom Byrne" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-172" target="_blank">Deadlock when performing background operation</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2016-10-26T18:35:43+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>Session timeout is 5s, <br/>
connection timeout is 3s</p>

<p>ZK cluster was still responding to other clients inflight, but I don't know if it would/was accepting new connections. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Tom - what is your retry policy? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>If looks like ZooChangeWatcher makes additional Curator/ZooKeeper calls, right? This could be the problem. ZooKeeper watchers and background operations are single threaded (see here: <a href="https://cwiki.apache.org/confluence/display/CURATOR/TN1" class="external-link" target="_blank" rel="nofollow noopener">https://cwiki.apache.org/confluence/display/CURATOR/TN1</a>). When you register your ZooChangeWatcher try passing in a thread pool so that the watchers can execute in separate threads.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>ZooChangeWatcher doesn't get any watches. During some events (internal server events, not ZK), we go and read a set of child nodes from a well-known location. Then we notify different listeners, which then can do things like update other state in ZK, etc. </p>

<p>Are there good docs on ZK's threading model and suggested usage? We're using multiple threads to make concurrent calls on a regular basis.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>OK, I think I might have a line on what's happening. </p>

<p>Thread A is making a call. It gets a CuratorZKClient, which calls checkTimeouts (getting the ConnectionState monitor). The connection is gone, and so reset() gets called, then HandleHolder calls ZK.close, which then calls ZKClientCnxn.close. </p>

<p>This calls submitRequest which queues a "disconnect" packet, then wait()'s on the packet object. </p>

<p>This wait() will only get notified when the packet is dequeued and notifyAll() is called in finishPacket(). When this thread calls wait(), it releases the monitor lock on the Packet object, but keeps the other two monitors that it has, one on the ConnectionState object, and another on the Zookeeper object itself. </p>

<p>During this wait, the SendThread (either already running or wakes up, whatever). Throws an exception, which trickles through to cleanup().</p>

<p>inside cleanup(), the pending queue is drained, calling conLossPacket, then finishPacket(). </p>

<p>Because they're pending aysnc packets, eventThread.queuePacket() is called on the pending async packet. We call the callback, which in turn trickles back up to (in this case) the CreateBuilderImpl AsyncCallback.StringCallback's processResult, which then tries to submit another event, which will never get processed, because in order to get the ZKClient again, we call getZookeeperClient, which will try to get the ConnectionState monitor lock that Thread A has.  </p>

<p>It will wait for that, never dequeuing, processing and notifying the "disconnect" packet that Thread A is waiting on.</p>

<p>So this would only happen if there was a pending async packet in the queue when disconnect happened, AND the async callback tries to make another ZK call.</p>

<p>I think I can reproduce this with a small test, I'll see what I can come up with in the next day or two.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>In my case, I think Thread A might be the Background thread. It's so hard to catch in this state. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>I still can't reproduce it with a simple test, but it still occasionally occurs under load. And it's definitely a problem with the synchronization between Curator and ZK.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>I think this will solve the problem:</p>

<p>azkaban:nodes kylar$ diff /source/curator-2.4.2/curator-apache-curator-2.4.2/curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentEphemeralNode.java PersistentEphemeralNode.java <br/>
224c224,227<br/>
<     createNode();<br/>
&#8212;<br/>
>     if(event.getResultCode() != KeeperException.Code.CONNECTIONLOSS.intValue() &&<br/>
>     event.getResultCode() != KeeperException.Code.SESSIONEXPIRED.intValue()) </p>
{
> createNode();
>     }

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mumrah">mumrah</a>:</i>
<p>Any updates on this? Are there any possible workarounds?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kylar">kylar</a>:</i>
<p>We made a change by changing the way we queue zk calls for execution. Any callback from ZK always delegates to a different thread, so that way the callback thread can't ever get into this state.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shahrs87">shahrs87</a>:</i>
<p>Encountered similar deadlock in our production env.</p>

<p> </p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>
Found one Java-level deadlock:

=============================

"Curator-Framework-0":

  waiting to lock monitor 0x00005601714db280 (object 0x00007f462c96f438, a java.util.LinkedList),
  which is held by "Curator-Framework-0-SendThread(<zk-server>:2181)"
"Curator-Framework-0-SendThread(<zk-server>:2181)":
  waiting to lock monitor 0x00007f321e7da400 (object 0x00007f368f014e18, a org.apache.curator.ConnectionState),

  which is held by "Curator-Framework-0"

 
Java stack information for the threads listed above:

===================================================

"Curator-Framework-0":
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1244)
        - waiting to lock <0x00007f462c96f438> (a java.util.LinkedList)
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanAndNotifyState(ClientCnxn.java:1174)
        at org.apache.zookeeper.ClientCnxn$SendThread.access$2300(ClientCnxn.java:700)
        at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1420)
        at org.apache.zookeeper.ClientCnxn.close(ClientCnxn.java:1373)
        at org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:788)
        - locked <0x00007f462c96e6b0> (a org.apache.zookeeper.ZooKeeper)
        at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:139)
        at org.apache.curator.HandleHolder.closeAndReset(HandleHolder.java:77)
        at org.apache.curator.ConnectionState.reset(ConnectionState.java:217)
        - locked <0x00007f368f014e18> (a org.apache.curator.ConnectionState)
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:193)
        - locked <0x00007f368f014e18> (a org.apache.curator.ConnectionState)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
        at java.util.concurrent.FutureTask.run(java.base@11.0.15/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.15/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.15/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.15/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)

"Curator-Framework-0-SendThread(hbase1a-mnds5-1-ia2.ops.sfdc.net:2181)":

        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:176)
        - waiting to lock <0x00007f368f014e18> (a org.apache.curator.ConnectionState)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.doSyncForSuspendedConnection(CuratorFrameworkImpl.java:701)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$700(CuratorFrameworkImpl.java:64)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$7.retriesExhausted(CuratorFrameworkImpl.java:697)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:516)
        at org.apache.curator.framework.imps.BackgroundSyncImpl$1.processResult(BackgroundSyncImpl.java:50)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:611)
        at org.apache.zookeeper.ClientCnxn$EventThread.queuePacket(ClientCnxn.java:462)
        - locked <0x00007f462c96f9f8> (a java.util.concurrent.LinkedBlockingQueue)
        at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:632)
        at org.apache.zookeeper.ClientCnxn.conLossPacket(ClientCnxn.java:650)
        at org.apache.zookeeper.ClientCnxn.access$2100(ClientCnxn.java:94)
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1246)
        - locked <0x00007f462c96f438> (a java.util.LinkedList)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1159)



Found 1 deadlock.

</pre>
</div></div>

<p> </p>

<p>We are using very old version of zk: some version of 3.4.13<br/>
We are using 2.10.0 curator version.</p>

<p>In the above stack trace I don't see any curator user related code. Can someone please help?<br/>
 </p>
