### ISSUE TITLE
[CURATOR-179] Sequential path creation of /somepath/N throws exception

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#700]
<p>A new error is thrown when attempting to run one of our scala services with Curator 2.7.0. The error does not throw in 2.6.0 (or in 2.5.0, which is when the original code was written. We were updating to 2.7.0).</p>

<p>Stack trace:<br/>
<span class="error">&#91;error&#93;</span> Exception in thread "main" java.lang.IllegalArgumentException: Path must not end with / character<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:61)<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.utils.ZKPaths.fixForNamespace(ZKPaths.java:44)<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:82)<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:589)<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.framework.imps.CreateBuilderImpl$1.forPath(CreateBuilderImpl.java:112)<br/>
<span class="error">&#91;error&#93;</span> 	at org.apache.curator.framework.imps.CreateBuilderImpl$1.forPath(CreateBuilderImpl.java:76)<br/>
<span class="error">&#91;error&#93;</span> 	at com.box.<application code>.scala:175)<br/>
...</p>

<p>This happens when we try to create node /somepath/N (where N is sequential zk node).</p>

<p>In Curator, PathUtils.validatePath has two signatures:<br/>
1. public static void validatePath(String path, boolean isSequential) throws IllegalArgumentException </p>
{
     validatePath(isSequential? path + "1": path);
   }
<p>2. public static String validatePath(String path) throws IllegalArgumentException {<br/>
  ...<br/>
  throws if path ends in '/'<br/>
  ...<br/>
}</p>

<p>In our case, path /somepath/ does end in '/'</p>

<p>The way #1 calls #2 appears to be a hack (appending "1" to path in order to validate). This would have caused path validation to <b>succeed</b> for our case - however, the caller MUST call this #1 signature of validatePath. The code calls actually calls #2 instead.</p>

<p>2.5.0 released May 28, 2014<br/>
2.6.0 released July 11, 2014</p>
<ul>
	<li>issue introduced<br/>
2.7.0 released November 3, 2014</li>
</ul>

<p>I believe the issue was introduced on July 29 2014, when a call to #2 above was added to fixForNamespace(String namespace, String path) in<br/>
<a href="https://github.com/apache/curator/commit/96d2a55a03f8d0357f8f8cfa80a39a095d70667c" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/commit/96d2a55a03f8d0357f8f8cfa80a39a095d70667c</a></p>

<p>We've decided to workaround the issue at the moment. Our workaround is straightforward:<br/>
Change our sequential node path from /somepath/N<br/>
to /somepath/entry_N</p>

<p>Please get in touch if you need additional information to solve this issue. Thanks!</p>

---
<details><summary><i>Originally reported by <a title="Ryan Luecke" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rluecke">rluecke</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-179" target="_blank">Sequential path creation of /somepath/N throws exception</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-01-12T23:05:32+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>You're correct about where the issue was introduced. So, this forces you to have a prefix for your sequential nodes.</p>

<p>The issue is that the ZKPaths.fixForNamespace() has no context as to whether the node being created is sequential or not.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth" class="user-hover" rel="dragonsinth">Scott Blum</a>, I believe that you added this fix. Any suggestions? We could just remove the validatePath() call from ZKPaths.fixForNamespace(), but it is arguably nice to have that validation there. Changing the fixForNamespace() stuff to be aware of the fact that the node being created is sequential is another option, but this will have a reasonably large impact as it's used in quite a number of places.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Yeah, I think I was trying to bring some sanity to String based path handling, it's been kind of a mess in the past, leading to situations where trying to combine path parts wound up with too many or not enough slashes in the right places</p>

<p>Is there any semantic different between "/foo" and "/foo/"?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>In the path validation code in ZK itself (where I believe the Curator PathUtils class was borrowed from) "/foo/" is illegal. The exception is for sequential paths because they get a number appended to them which is what's happening in this case.</p>

<p>In the context of the fixForNamespace() method, there's no difference between "/foo/" and "/foo" because I believe that the call to makePaths() fixes the path even if it ends with a "/", though this would only happen if a namespace was active, so this is a bit inconsistent. I don't know if we could just make fixForNamespace() remove any trailing slash, it might break the sequential stuff.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>I think what would be useful is a test case demonstrating the problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I reproduced the problem with a quick test (that I haven't committed), I will check it in on a <a href="https://issues.apache.org/jira/browse/CURATOR-179" title="Sequential path creation of /somepath/N throws exception" class="issue-link" data-issue-key="CURATOR-179"><del>CURATOR-179</del></a> branch when I get a minute.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I have added a simple test case to the <a href="https://issues.apache.org/jira/browse/CURATOR-179" title="Sequential path creation of /somepath/N throws exception" class="issue-link" data-issue-key="CURATOR-179"><del>CURATOR-179</del></a> branch that reproduces the problem. Removing the PathUtils.validatPath() from ZKPaths fixes the issue, but obviously we lose the advantages of this validation.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> i pushed a commit on your branch, see what you think.  Feel free to drop it if you don't like.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Thanks Scott,<br/>
Looks good to me. I won't be able to merge until early next week, so feel free to merge away if you like.<br/>
cheers</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rluecke">rluecke</a>:</i>
<p>Thank you both for working on this - very appreciated! <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>
