### ISSUE TITLE
[CURATOR-200] Proposal: Remove references to guava library from public APIs

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#721]
<p>There was a good discussion on the mailing list: <a href="http://curator.markmail.org/thread/yjete2ozm32jmz5u" class="external-link" target="_blank" rel="nofollow noopener">http://curator.markmail.org/thread/yjete2ozm32jmz5u</a></p>

<p>The critical portion copied here:</p>
<blockquote>
<p>The problem classes that I have found are:</p>
<ul>
	<li>curator-framework: org.apache.curator.framework.listen.ListenerContainer : method forEach takes a parameter of type com.google.common.base.Function</li>
	<li>curator-framework: org.apache.curator.framework.api.transaction.CuratorTransactionResult : method ofTypeAndPath returns com.google.common.base.Predicate</li>
	<li>curator-x-discovery-server: org.apache.curator.x.discovery.server.contexts.GenericDiscoveryContext : constructor takes param of type com.google.common.reflect.TypeToken</li>
	<li>curator-x-discovery: org.apache.curator.x.discovery.InstanceFilter : inherits from com.google.common.base.Predicate</li>
</ul>
</blockquote>

<p>In the ensuing discussion, it sounded like we'd need to get started on an implementation before we had enough information to determine whether the changes are too intrusive or not.</p>

---
<details><summary><i>Originally reported by <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-200" target="_blank">Proposal: Remove references to guava library from public APIs</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-01-16T18:27:58+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>If we move up to Java 8, then we can replace Function and Predicate with the matching classes in <tt>java.util.function</tt>:</p>
<ul>
	<li><a href="https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html</a></li>
	<li><a href="https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html</a></li>
</ul>


<p>I have not found an easy alternative for TypeToken.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I don't think ZooKeeper is moving to Java 8. I'd vote to match their JVM choice. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>TypeToken is a big problem. I'm not sure what the solution is.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Since Guava is Apache licensed, we can always just copy a few classes over to 1) ensure API stability, 2) drop the external dependency.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>That's probably the only way to handle the TypeToken issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Let's have this conversation on the other JIRA, please.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-200" title="Proposal: Remove references to guava library from public APIs" class="issue-link" data-issue-key="CURATOR-200"><del>CURATOR-200</del></a> Shade Guava into Curator</p>

<p>    Shaded Guava into Curator Client (and Curator Test) so that it's no longer an issue for users. This should have been done a long time ago. Unfortunately, com.google.common.base.Function, com.google.common.base.Predicate and com.google.common.reflect.TypeToken are in Curator's public API so those 3 classes are NOT shaded. However, this won't be a problem because there's no reason to think that Guava will change or remove these basic interfaces.</p>

<p>    NOTE: I've tested this by creating a temp project that uses Guava 21.0-rc2. When used with Curator 2.11.1 I get a NoSuchMethodError. When used with this new shaded version of Curator there are no errors. </p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-200" title="Proposal: Remove references to guava library from public APIs" class="issue-link" data-issue-key="CURATOR-200"><del>CURATOR-200</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/190.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #190</p>

<hr />
<p>commit fb277f9601411427dee7d26dd2be76941d38c0c3<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-01-08T00:59:07Z</p>

<p>    Shaded Guava into Curator Client (and Curator Test) so that it's no longer an issue for users. This should have been done a long time ago. Unfortunately, com.google.common.base.Function, com.google.common.base.Predicate and com.google.common.reflect.TypeToken are in Curator's public API so those 3 classes are NOT shaded. However, this won't be a problem because there's no reason to think that Guava will change or remove these basic interfaces</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I think we also need to relocate that classes, otherwise they're still present on the classpath and could cause conflicts.</p>

<p><a href="https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html" class="external-link" target="_blank" rel="nofollow noopener">https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The problem is that those 3 classes are part of Curator's public API - so we can't move them. The good news is that it's very unlikely that Guava will move these. Even if they do we can shade them into one of the Curator JARs at the same FQPN. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user oza commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>    Thanks for taking this big issue. It must be helpful for Curator's users. Do you think that this change must be done with source-level compatibility? If the answer is positive, it looks good to me.</p>

<p>    > However, this won't be a problem because there's no reason to think that Guava will change or remove these basic interfaces.</p>

<p>    It's realistic decision, especially for Function and Predicate interfaces. About <span class="error">&#91;TypeToken&#93;</span>(<a href="https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/reflect/TypeToken.html" class="external-link" target="_blank" rel="nofollow noopener">https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/reflect/TypeToken.html</a>), however, it is marked with <span class="error">&#91;Beta annotation&#93;</span>(<a href="https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/annotations/Beta.html" class="external-link" target="_blank" rel="nofollow noopener">https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/annotations/Beta.html</a>). Hence, I think the interface can be changed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Ah! I misread the diff and see this now. Thank you for clarifying. Big +1 to merge this!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kscarr73 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>    One problem I see, is that if someone has already included guava in their project, or like me, use curator-client in an OSGI environment that already has guava installed, this could cause conflicts.</p>

<p>    I see 2 options:</p>

<p>    1. Use Shade to change the package name for the guava stuff, so it doesn't conflict.<br/>
    2. Create a different client project that is client-core or something similar, and then build the client shade with guava from this.</p>

<p>    Thoughts? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user kscarr73 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>    Ahh, I looked for them, but didn't see them before my comment.  That works then.  Not sure how much bigger the jar is, yet, but I see about doing a build later.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>FYI - the curator-client JAR grows by about 5.5M</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user oza commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

<p>    LGTM from license's point of view. Guava doesn't have its own NOTICE file, so we don't need to add the file to our jar.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/196" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/196</a></p>

<p>    this is already addressed by <a href="https://issues.apache.org/jira/browse/CURATOR-200" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-200</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/199" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/199</a></p>

<p>    Guava has been shaded into the Curator code so staying in sync with Guava versions is no longer necessary. <a href="https://issues.apache.org/jira/browse/CURATOR-200" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-200</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user lucasmo opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/212" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/212</a></p>

<p>    Fix guava version incompatibility with MoreExecutors.sameThreadExecutor()</p>

<p>    Before I went to create this PR, I see similar ones have been closed several times, suggesting that it was addressed in <a href="https://github.com/apache/curator/pull/190" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/190</a> as part of <a href="https://issues.apache.org/jira/browse/CURATOR-200" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-200</a></p>

<p>    This doesn't appear to actually address the issue, as this error occurs:</p>

<p>    ```<br/>
    java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;<br/>
    at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:40)<br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:256)<br/>
    at XXX.start(XXX.java:88)<br/>
    ```</p>

<p>    I'm not familiar with shading, but it appears it's either not implemented or not working properly in this case (does shading rewrite the curator source files?). This error occurs with both 2.12.0 and 3.3.0.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/lucasmo/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/lucasmo/curator</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/212.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/212.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #212</p>

<hr />
<p>commit cf40b506470930f71eb1f47a210a9d5fb9fc0b60<br/>
Author: Lucas Fairchild-Madar <lfairchildmadar@conducivetech.com><br/>
Date:   2017-04-10T18:12:31Z</p>

<p>    Replace calls to MoreExecutors.sameThreadExecutor() with MoreExecutors.directExecutor()</p>

<p>commit 612dde623f6c6443616ee963aef82d331782479c<br/>
Author: Lucas Fairchild-Madar <lfairchildmadar@conducivetech.com><br/>
Date:   2017-04-10T18:14:35Z</p>

<p>    Bump to minimum guava version that has MoreExecutors.directExecutor()</p>

<p>commit 6d050b8ec694861336aa6620f9ca8b3aa06dc605<br/>
Author: lucasmo <lucas.madar@gmail.com><br/>
Date:   2017-04-10T18:16:58Z</p>

<p>    Update QueueBuilder.java</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/212" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/212</a></p>

**Comment by jira-importer** [comment]
<i>[Originally blocks: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20YARN-3774">YARN-3774</a>]</i>
