### ISSUE TITLE
[CURATOR-218] Race condition in client.blockUntilConnected()

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#738]
<p>I'm implementing a Guava service relying on the startAsync feature. I'm using a listener to wait for the INITIALIZED event to fire the guava service notifyStarted method, but sometimes the listener never receives the event if the root path does not exist.</p>

<p>I've created a repository with a failing test (looping over the failing test to force it).</p>

<p>repo with tests: <a href="https://github.com/samuelgmartinez/curator-treecache-tests.git" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/samuelgmartinez/curator-treecache-tests.git</a><br/>
failing test: mvn -Dtest=TreeCacheTest#testListenerNonExistentRootLoop test</p>

---
<details><summary><i>Originally reported by <a title="Samuel García Martínez" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuelgmartinez">samuelgmartinez</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-218" target="_blank">Race condition in client.blockUntilConnected()</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-08-24T13:24:48+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuelgmartinez">samuelgmartinez</a>:</i>
<p>I've attached the failing test output log</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>I can't repro this on master, I've run it several times.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuelgmartinez">samuelgmartinez</a>:</i>
<p>I will spin up an ec2 machine with everything set up and try it with the latest master build. If the error persist I can give you access to debug it.</p>

<p>news asap</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I can kind of reproduce this on my local machine. Had to massage the code you provided a little bit...</p>

<p>I'll put up a patch with the failing test at a minimum, might get a chance to investigate more properly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>So, I've continued digging into this, and I have good news! It has nothing to do with the TreeCache!</p>

<p>Unfortunately, it looks like there might be a bug in blockUntilConnected. I can file a new JIRA, or rescope this one; whichever people prefer.</p>

<p>Given the following test code:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">CuratorFramework client;
<span class="code-keyword">for</span>(<span class="code-object">int</span> i = 0 ; i < 50 ; i++)
{
    client = CuratorFrameworkFactory.newClient(server.getConnectString(), <span class="code-keyword">new</span> RetryOneTime(100));
    <span class="code-keyword">try</span> 
    {
client.start();
client.blockUntilConnected();

Assert.assertTrue(client.getZookeeperClient().isConnected(), <span class="code-quote">"Not connected after blocking <span class="code-keyword">for</span> connection #"</span> + i);
    }
    <span class="code-keyword">finally</span>
    {
client.close();
    }
}
</pre>
</div></div>

<p>I'll get an assertion failure fairly regularly. Here's the output in my logs from the test run -</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.AssertionError: Not connected after blocking for connection #3 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.apache.curator.framework.imps.TestBlockUntilConnected.testBlockUntilConnectedTightLoop(TestBlockUntilConnected.java:251)


INFO  org.apache.curator.framework.imps.CuratorFrameworkImpl  Starting [main]
DEBUG org.apache.curator.CuratorZookeeperClient  Starting [main]
DEBUG org.apache.curator.ConnectionState  Starting [main]
DEBUG org.apache.curator.ConnectionState  reset [main]
INFO  org.apache.curator.framework.state.ConnectionStateManager  State change: CONNECTED [main-EventThread]
DEBUG org.apache.curator.framework.imps.CuratorFrameworkImpl  Closing [main]
DEBUG org.apache.curator.CuratorZookeeperClient  Closing [main]
DEBUG org.apache.curator.ConnectionState  Closing [main]
</pre>
</div></div>

<p>I understand that connections are a transient and finicky thing, like gold dust or rainbows, they are apt to disappear when you least expect them to. However, I don't see anything given by the CSM to indicate that we would <em>not</em> be connected... no connection loss, no session loss, nothing...</p>

<p>Anybody have a pointer on where to look next? I suspect that there is a synchronization issue where the method returns before the state on CuratorZookeeperClient is updated, but I'm not sure how to prove that yet.</p>

<p>Anyway, the TreeCache never sees that INITIALIZED event as the issue reported describes because of the connection issue I described.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I just had a quick look, and this is pretty strange indeed!</p>

<p>blockUntilConnected() returns a boolean indicating whether a connection was established or not, but I think that this is only relevant if you use the version that passes in a maximum waiting time (which you're not).</p>

<p>I reckon that you're probably right and that it's a race condition between the currentConnectionState being set in the ConnectionStateManager class, and the ConnectionState isConnected flag being set in the CuratorZookeeperClient class.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>It seems that client.blockUntilConnected() (no args version) isn't doing what it's contract indicates. I don't know if the code cares though. I'll look as well, but please continue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I think that the blockUntilConnected() no args version is returning when it thinks it has a connection, it's just that it's using the ConnectionStateManager to infer this, and the CuratorZookeeperClient's state does not match the ConnectionStateManager.</p>

<p>So, maybe we need to look at only having a single source of truth for whether a connection is present or not. I imagine this is probably a fair bit of work though.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The tests never fail for me. Do I have to run multiple times to see failure?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>FYI - using git bisect I found out that this version of blockUntilConnected is relatively new:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>commit 04cefb47f18c9d4bd3a0eb897563dd5abb7c89c8
Author: randgalt <randgalt@apache.org>
Date:   Mon Jun 16 14:35:54 2014 -0500

    Moved the connection blocking code into ConnectionManager. It's cleaner and doesn't require a connection state listener
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<blockquote><p>The tests never fail for me. Do I have to run multiple times to see failure?</p></blockquote>
<p>Since the loop is creating connections 50 times, I tend to see a true failure every time I run. Try increasing the count to 500, if you want? Might be a hardware issue, or software version issue, too? I'm on maven 3.2.3, Java8u45, Ubuntu 14.04.</p>

<blockquote><p>FYI - using git bisect I found out that this version of blockUntilConnected is relatively new:</p></blockquote>
<p>Hmm, I might have found a different issue then? Or it's possible that a different race condition existed before as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Changed to 500 iterations and it succeeds every time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Ok, so it's a race condition exposed by some combination of </p>
{JVM, OS, Kernel, CPU}
<p>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Progress!</p>

<p>In <tt>ConnectionState.process</tt>, we call all the <tt>parentWatcher.process</tt> before setting our own connected state. One of the parent watchers is from <tt>CuratorFrameworkImpl</tt> and that's the one that triggers <tt>ConnectionStateManager</tt> to stop blocking. I <em>think</em> that we can swap the order of those operations, but I'm not 100% sure it won't impact reconnect or connection loss somewhere else. Anyway, running the full test suite now and if that passes then I will put up a PR.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dragonsinth">dragonsinth</a>:</i>
<p>Very cool.  Seems like I should reassign this issue to you <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob" class="user-hover" rel="mdrob">Mike Drob</a>?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I'm happy to work the issue, but my understanding is that assignment only happens to the committer who ultimately pushes a fix and I am not a committer.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user madrob opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/88" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/88</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-218" title="Race condition in client.blockUntilConnected()" class="issue-link" data-issue-key="CURATOR-218"><del>CURATOR-218</del></a> Reorder ConnectionState process event</p>

<p>    Address a race condition in ConnectionState.process where it will<br/>
    trigger watchers first before updating its own state. This can lead to<br/>
    inconsistencies when blocking until connected.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/madrob/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/madrob/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-218" title="Race condition in client.blockUntilConnected()" class="issue-link" data-issue-key="CURATOR-218"><del>CURATOR-218</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/88.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/88.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #88</p>

<hr />
<p>commit 4d9eace865d88d0213b07e3c22ae93d36bcdf84e<br/>
Author: Mike Drob <mdrob@apache.org><br/>
Date:   2015-07-08T16:04:30Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-218" title="Race condition in client.blockUntilConnected()" class="issue-link" data-issue-key="CURATOR-218"><del>CURATOR-218</del></a> Reorder ConnectionState process event</p>

<p>    Address a race condition in ConnectionState.process where it will<br/>
    trigger watchers first before updating its own state. This can lead to<br/>
    inconsistencies when blocking until connected.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I get some test failures locally when running with the patch, but I also get them without the patch. See <a href="https://issues.apache.org/jira/browse/CURATOR-231" title="TestDistributedQueue.testRetryAfterFailure_Curator56 fails" class="issue-link" data-issue-key="CURATOR-231"><del>CURATOR-231</del></a>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user dragonsinth commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/88#issuecomment-119695849" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/88#issuecomment-119695849</a></p>

<p>    Remove the TreeCache changes?  Seems unrelated to the underlying bug in retrospect.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/88#discussion_r34185266" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/88#discussion_r34185266</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestBlockUntilConnected.java &#8212;<br/>
    @@ -232,4 +232,30 @@ public void run()<br/>
 CloseableUtils.closeQuietly(client);<br/>
     }<br/>
 }<br/>
    +<br/>
    +    /**<br/>
    +     * Test that we are actually connected every time that we block until connection is established in a tight loop.<br/>
    +     */<br/>
    +    @Test<br/>
    &#8212; End diff &#8211;</p>

<p>    ~10 seconds on my laptop.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/88#issuecomment-122622144" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/88#issuecomment-122622144</a></p>

<p>    Agree that this is old code that should be stable. Do you have a specific scenario/test case that you think this would cause issue with, or is it "gut feeling?"</p>
