### ISSUE TITLE
[CURATOR-229] No retry on DNS lookup failure

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#749]
<p>Our environment is setup so that host names (rather than IP addresses) are used when registering services.</p>

<p>When disconnecting a node from the network, it will attempt to reconnect and - in order to do this - attempts to resolve a host name, which fails (since we have no network connectivity and a DNS server is used).</p>

<p>It appears this type of exception is not retryable, and the node simply gives up and never reconnects, even when the network connectivity is back.</p>

<p>Is this the expected behavior? Is there any way to configure Curator so that this type of exception is retryable? I had a look at <tt>CuratorFrameworkImpl.java</tt> around line 768 but there doesn't seem to be anything configurable.</p>

<p>If this is not the expected behavior (or if it is but you don't mind making it configurable), I should be able to provide a patch via a pull request.</p>

---
<details><summary><i>Originally reported by <a title="Michael Putters" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mput">mput</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-229" target="_blank">No retry on DNS lookup failure</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2023-05-17T11:59:12+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mput">mput</a>:</i>
<p>The stacktrace:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
java.net.UnknownHostException: host.name.here
  at java.net.InetAddress.getAllByName0(InetAddress.java:1250) ~[na:1.7.0_67]
  at java.net.InetAddress.getAllByName(InetAddress.java:1162) ~[na:1.7.0_67]
  at java.net.InetAddress.getAllByName(InetAddress.java:1098) ~[na:1.7.0_67]
  at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
  at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
  at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:160) ~[curator-framework-2.7.0.jar:na]
  at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.ConnectionState.reset(ConnectionState.java:218) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:193) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) ~[curator-client-2.7.0.jar:na]
  at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:816) [curator-framework-2.7.0.jar:na]
  at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:802) [curator-framework-2.7.0.jar:na]
  at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$400(CuratorFrameworkImpl.java:61) [curator-framework-2.7.0.jar:na]
  at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:272) [curator-framework-2.7.0.jar:na]
  at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
  at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.7.0_67]
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=asloane">asloane</a>:</i>
<p>Seconding this.</p>

<p>What's super annoying is that the background thread just dies, and yet no API calls ever throw any exceptions or ever indicate anything is wrong. If <tt>CuratorFramework.start()</tt> or <tt>LeaderLatch.await()</tt> threw an exception then we'd be fine since we'd just die and restart, but instead everything is just stuck.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I don't believe there's a way of configuring Curator to modify the exceptions that it considers retryable currently.</p>

<p>I'm not sure if changing Curator to retry on the UnknownHostException would do much anyway. The exception is being thrown by the underlying ZK client. Every time Curator tried to create a new ZK client while the hostname was unresolvable, the error would occur.</p>

<p>I guess if your DNS outage is only for a short period (or you have a long retry period defined) then it would be recoverable.</p>

<p>I think that possibly the best generic fix is to make the RetryLoop code have a default set of error codes that are retryable and then allow that to be overridden. I think that this is a bit of effort due to the way that RetryLoop is currently accessed (statically), but I will have a look into it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>My concern with modifying the start() method functionality is that it breaks the current contract. The current start() method definition contains no throws clause.</p>

<p>We could possibly introduce a separate start() method that explicitly fails if no connection to Zookeeper can be established. Would that in conjunction with having control over which exceptions / errors are retryable solve your respective problems?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=asloane">asloane</a>:</i>
<p>Yeah, that's what I was thinking. No throws clause on start, so there's no API-compatible way to fix that...</p>

<p>I think that sounds like a reasonable solution.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a>, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lvfangmin" class="user-hover" rel="lvfangmin">Fangmin Lv</a></p>

<p>Any thoughts on this approach? If everyone is happy with this, I'll have a look at implementing it.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>You can always wrap the exception in RuntimeException and put the work in the existing start(). </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>So you're saying just add an unhandled exception handler and have it throw a Runtime exception if it encounters an UnknownHostException (in this case)?</p>

<p>That doesn't handle the case where we've already connected and want to allow reconnection does it?</p>

<p>We would need to implement a way of programatically defining retryable errors as well.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igstan">igstan</a>:</i>
<p>We've bumped into the same issue. Our DNS server was temporarily down and Curator stopped retrying to connect because ZooKepper threw a non-retryable exception: (<tt>UnknownHostException</tt>). In ZooKepper >= 3.4.11 it will throw an <tt>IllegalArgumentException</tt>. This behaviour has changed as a result of these:</p>

<ul class="alternate" type="square">
	<li><a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1576" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-1576</a></li>
	<li><a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2614" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-2614</a></li>
</ul>


<p>What we've ended up doing is to register a custom <tt>ZookeeperFactory</tt> with<br/>
<tt>CuratorFrameworkFactory.builder()</tt>. That factory is responsible for creating new <tt>ZooKeeper</tt> instances when retrying. So we're just catching <tt>UnknownHostException</tt> and <tt>IllegalArgumentException</tt> there and then throw a <tt>ConnectionLossException</tt>, which is retry-able as far as Curator is concerned.</p>

<p>In case anyone's interested, here's the code, in Scala:</p>

<div class="code panel" style="border-style: solid;border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;border-bottom-style: solid;"><b>ZookeeperFactory.scala</b></div><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">import</span> java.net.UnknownHostException
<span class="code-keyword">import</span> com.typesafe.scalalogging.LazyLogging
<span class="code-keyword">import</span> org.apache.zookeeper.KeeperException.ConnectionLossException
<span class="code-keyword">import</span> org.apache.zookeeper.{Watcher, ZooKeeper}

/** ZooKeeper client factory that's resilient to hostname lookup errors.
  *
  * The purpose of <span class="code-keyword">this</span> wrapper is to handle hostname errors encountered
  * <span class="code-keyword">while</span> creating ZooKeeper client instances. It works around these issues:
  *
  *   - https:<span class="code-comment">//issues.apache.org/jira/browse/ZOOKEEPER-1576
</span>  *   - https:<span class="code-comment">//issues.apache.org/jira/browse/ZOOKEEPER-2614
</span>  *   - https:<span class="code-comment">//issues.apache.org/jira/browse/CURATOR-229
</span>  *
  * Curator knows how to retry a finite and predefined set of exceptions. What
  * <span class="code-keyword">this</span> custom factory does is to map hostname-related exceptions into one
  * that Curator interprets as a retry-able exception. So it will keep trying
  * to establish a connection to ZooKeeper even in the face of such errors.
  *
  * @param servers The list of ZooKeeper hostnames or addresses.
  */
<span class="code-keyword">class </span>ZookeeperFactory(servers: Seq[<span class="code-object">String</span>])
  <span class="code-keyword">extends</span> org.apache.curator.utils.ZookeeperFactory
    with LazyLogging {

  override def newZooKeeper(connectString: <span class="code-object">String</span>, sessionTimeout: Int, watcher: Watcher, canBeReadOnly: <span class="code-object">Boolean</span>): ZooKeeper = {
    def retry(servers: Seq[<span class="code-object">String</span>]): ZooKeeper = {
      servers match {
<span class="code-keyword">case</span> Nil =>
  <span class="code-comment">// All server hostnames have failed. Tell Curator to retry later.
</span>  <span class="code-keyword">throw</span> <span class="code-keyword">new</span> ConnectionLossException()
<span class="code-keyword">case</span> remainingServers =>
  val connectString = remainingServers.mkString(<span class="code-quote">","</span>)

  <span class="code-keyword">try</span> {

    <span class="code-keyword">new</span> ZooKeeper(connectString, sessionTimeout, watcher, canBeReadOnly)

  } <span class="code-keyword">catch</span> {
    <span class="code-comment">// Apache ZooKeeper <= 3.4.10 will <span class="code-keyword">throw</span> an UnknownHostException at
</span>    <span class="code-comment">// the first hostname which it can't resolve, instead of trying the
</span>    <span class="code-comment">// following hostnames in the list. So, we just drop the offending
</span>    <span class="code-comment">// hostnames from the servers list and <span class="code-keyword">try</span> again.
</span>    <span class="code-keyword">case</span> e: UnknownHostException =>
      logger.warn(s<span class="code-quote">"ZooKeeper client creation failed <span class="code-keyword">for</span> server list: $connectString"</span>, e)
      retry(remainingServers.drop(1))

    <span class="code-comment">// Apache ZooKeeper >= 3.4.11, will <span class="code-keyword">try</span> all hostnames, but we still
</span>    <span class="code-comment">// want to retry <span class="code-keyword">if</span> all of them fail right now.
</span>    <span class="code-keyword">case</span> EmptyHostProvider(e) =>
      logger.warn(s<span class="code-quote">"ZooKeeper client creation failed <span class="code-keyword">for</span> server list: $connectString"</span>, e)
      <span class="code-keyword">throw</span> <span class="code-keyword">new</span> ConnectionLossException()
  }
      }
    }

    retry(servers)
  }
}

object EmptyHostProvider {
  <span class="code-keyword">private</span> <span class="code-keyword">final</span> val MESSAGE = <span class="code-quote">"A HostProvider may not be empty!"</span>

  def unapply(e: Throwable): Option[IllegalArgumentException] = {
    e match {
      <span class="code-keyword">case</span> e: IllegalArgumentException <span class="code-keyword">if</span> e.getMessage == MESSAGE => Some(e)
      <span class="code-keyword">case</span> _ => None
    }
  }
}
</pre>
</div></div>

<p>And its usage:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">val zk = CuratorFrameworkFactory.builder()
    .connectString(config.servers)
    .sessionTimeoutMs(...)
    .connectionTimeoutMs(...)
    .zookeeperFactory(<span class="code-keyword">new</span> ZookeeperFactory(config.servers.split(<span class="code-quote">','</span>)))
    .retryPolicy(<span class="code-keyword">new</span> RetryForever(1000))
    .build()
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jugosag">jugosag</a>:</i>
<p>I would like to second the request to fix this problem. While DNS outages might be rare in classical deployment scenarios, they are much more likely in Docker-based environments: Docker containers can be given DNS names, but this name is only resolvable once the containers is actually started. During startup of our stack, often not all Zookeeper containers of our cluster are started yet (because fixing a certain startup order is hard to do and an anti-pattern anyway), but some Zookeeper clients containing curator are already starting up, trying to connect to the ensemble, and failing due to UnknownHostException (which, as was already mentioned below, is not even thrown but a background exception, making it even more convoluted to do one's own retry loop).</p>

<p>So (maybe optionally)= making a DNS lookup error (UnknownHostException) a retryable error (not only during curator startup, but also during failover situations when Curator/ZookeeperClient switches from one Zookeeper instance that failed to another of the zookeeper connect string) would be really helpful here.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cablespaghetti">cablespaghetti</a>:</i>
<p>Has there been any progress on this issue? We are admittedly still running Curator 2.12 and I've run into this a few times recently due to DNS blips in our Kubernetes cluster. It basically brings down our entire system until I restart all our services. <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cablespaghetti">cablespaghetti</a>:</i>
<p>I made a Java version of <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igstan" class="user-hover" rel="igstan">Ionuț G. Stan</a>'s code and it mostly resolved my issue but <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2184" title="Zookeeper Client should re-resolve hosts when connection attempts fail" class="issue-link" data-issue-key="ZOOKEEPER-2184"><del>ZOOKEEPER-2184</del></a> caused me problems if the IP of my Zookeeper nodes changed. </p>

<p>In 2.12, if I pull in Zookeeper 3.4.13 which fixes <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2184" title="Zookeeper Client should re-resolve hosts when connection attempts fail" class="issue-link" data-issue-key="ZOOKEEPER-2184"><del>ZOOKEEPER-2184</del></a> instead of 3.4.8, it changes the exception to UnresolvedAddressException and I don't seem to need the new ZookeeperFactory anymore.</p>

<p>So I just did an exclusion for Zookeeper for all of my curator dependencies and then pulled in Zookeeper 3.4.13 with the same exclusions as in the Curator pom: <a href="https://github.com/apache/curator/blob/apache-curator-2.12.0/pom.xml" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/apache-curator-2.12.0/pom.xml</a></p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-293">CURATOR-293</a>]</i>
