### ISSUE TITLE
[CURATOR-242] TestDistributedQueue.testCustomExecutor() is failing

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#762]
<p><a href="https://builds.apache.org/job/Curator/940/org.apache.curator$curator-recipes/testReport/org.apache.curator.framework.recipes.queue/TestDistributedQueue/testCustomExecutor/" class="external-link" target="_blank" rel="nofollow noopener">https://builds.apache.org/job/Curator/940/org.apache.curator$curator-recipes/testReport/org.apache.curator.framework.recipes.queue/TestDistributedQueue/testCustomExecutor/</a></p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.apache.curator.framework.recipes.queue.TestDistributedQueue.testCustomExecutor(TestDistributedQueue.java:203)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-242" target="_blank">TestDistributedQueue.testCustomExecutor() is failing</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2015-08-24T14:13:37+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The job has subsequently passed. The tests are, in general, flakey due to timing issues that are difficult to resolve. We should use a single, general, Jira to track this. <a href="https://issues.apache.org/jira/browse/CURATOR-26" title="Make the tests more resliant" class="issue-link" data-issue-key="CURATOR-26"><del>CURATOR-26</del></a> is an example.</p>
