### ISSUE TITLE
[CURATOR-243] TestDistributedIdQueue.testRequeuingWithLock is failing

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#763]
<p><a href="https://builds.apache.org/job/Curator/940/org.apache.curator$curator-recipes/testReport/org.apache.curator.framework.recipes.queue/TestDistributedIdQueue/testRequeuingWithLock/" class="external-link" target="_blank" rel="nofollow noopener">https://builds.apache.org/job/Curator/940/org.apache.curator$curator-recipes/testReport/org.apache.curator.framework.recipes.queue/TestDistributedIdQueue/testRequeuingWithLock/</a></p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at org.apache.curator.framework.recipes.queue.TestDistributedIdQueue.testRequeuingWithLock(TestDistributedIdQueue.java:165)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-243" target="_blank">TestDistributedIdQueue.testRequeuingWithLock is failing</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-08-21T18:35:29+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>The logs from this test make me think that it is related to <a href="https://issues.apache.org/jira/browse/CURATOR-231" title="TestDistributedQueue.testRetryAfterFailure_Curator56 fails" class="issue-link" data-issue-key="CURATOR-231"><del>CURATOR-231</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The test was too timing-dependent. Most of the time, the code would be inside of consumeMessage and the queue's lock would be unavailable causing the remove() method to fail. I added a new debug method to verify that the item is still queued.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>Does this need to be merged into 3.0?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>done - I did it as "merge master". That's the recommended method I hope.</p>
