### ISSUE TITLE
[CURATOR-252] TestLeaderSelectorEdges::createProtectedNodeInBackgroundTest failed

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#772]
<p>Running the full test suite locally, this test failed for me ~20% of the time.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>java.lang.AssertionError: Callback has not been called expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:94)
at org.testng.Assert.failNotEquals(Assert.java:494)
at org.testng.Assert.assertTrue(Assert.java:42)
at org.apache.curator.framework.recipes.leader.TestLeaderSelectorEdges.createProtectedNodeInBackgroundTest(TestLeaderSelectorEdges.java:189)
</pre>
</div></div>

<p>Unfortunately, I do not have full logs available at this time.</p>

---
<details><summary><i>Originally reported by <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-252" target="_blank">TestLeaderSelectorEdges::createProtectedNodeInBackgroundTest failed</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-09-08T19:42:23+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The tests are, in general, flakey due to timing issues that are difficult to resolve. We should use a single, general, Jira to track this. <a href="https://issues.apache.org/jira/browse/CURATOR-26" title="Make the tests more resliant" class="issue-link" data-issue-key="CURATOR-26"><del>CURATOR-26</del></a> is an example.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>When there are timing related failures, then we can simulate the relevant sequencing by adding strategically placed debug latches. I think it's still a good idea to have separate issues for separate tests, and we can close them as duplicates later if they turn out to have the same cause.</p>

<p>Using a parent JIRA and creating sub-tasks makes sense too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>That's the genesis of the Timing class. I've been trying to get the tests repeatable for years. The problem is ZooKeeper itself. It simply doesn't behave predictably. Getting more testing hooks into ZooKeeper would be good too. It turns out that one of the hooks I wrote myself is going to be in 3.5. Hopefully we can get more in.</p>
