### ISSUE TITLE
[CURATOR-268] Curator client doesn't behave well when it loses connection: CRUD operation fail

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#788]
<p>I am doing a basic stress test :</p>
<ul class="alternate" type="square">
	<li>a TestingServer that keeps restarting in one thread</li>
	<li>a Curator client that keeps creating/deleting a node in another</li>
</ul>

<p>After a few seconds, ether the create or the delete fail:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Thu Oct 01 15:35:10 PDT 2015 - Node /test has successfully been removed.
Thu Oct 01 15:35:10 PDT 2015 - Recreating /test
Thu Oct 01 15:35:10 PDT 2015 - Restarting server...
Thu Oct 01 15:35:14 PDT 2015 - Restarting server...
Thu Oct 01 15:35:15 PDT 2015 - ERROR: node should be removed.
Thu Oct 01 15:35:15 PDT 2015 - Data of node is: test
Node has been mysteriously created...
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists <span class="code-keyword">for</span> /test
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:123)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1209)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:700)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at TestCuratorSaveConnLoss$3.run(TestCuratorSaveConnLoss.java:87)</pre>
</div></div>

<p>The create shouldn't fail, we're within 5 seconds of the create and the connection timeout is 10 secs.</p>

<p>This is surprising as this basic scenario is - AFAIK - the reason Curator exists in the first place.</p>

---
<details><summary><i>Originally reported by <a title="Benjamin Jaton" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-268" target="_blank">Curator client doesn't behave well when it loses connection: CRUD operation fail</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-10-06T02:43:05+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>:</i>
<p>The Test</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I created a version of your test that uses raw ZooKeeper instead of Curator: <a href="https://gist.github.com/Randgalt/c3358b740f7f09d47bb0" class="external-link" target="_blank" rel="nofollow noopener">https://gist.github.com/Randgalt/c3358b740f7f09d47bb0</a> - please double check it. The problem still shows. So either it's a) a bug in TestingServer or b) a bug in ZooKeeper itself or c) both. Thoughts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>BTW - if you replace TestingServer with TestingCluster the test works. There must be something about standalone mode.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>:</i>
<p>Thanks Jordan, you appear to be right.<br/>
I reproduce the bug without any Curator code, using the client thread and a fresh ZK server 3.5.1-alpha.<br/>
I will reach out to the ZK community.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>:</i>
<p>From the ZK developers:</p>

<p>"The behavior is expected. If your client loses its connection, then you don't know if the operation has gone through or not. When it reconnects, you can check if it exists and possibly delete it, depending on the behavior you want for you application."</p>

<p>Since Curator reason to exist is to shield the user from the disconnections/retries, shouldn't Curator handle this scenario?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>We've talked about this kind of thing before. What about this...</p>

<p>Add quietly() to the delete() chain, and orSetData() to the create() chain so you could do:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">client.delete().quietly().forPath(foo);
client.create().orSetData().forPath(foo, data);
</pre>
</div></div>

<p>Does getData() need an addition?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>:</i>
<p>I can't find those methods: quietly() / orSetData().</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>No, I'm proposing to add them.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benjamin.jaton">benjamin.jaton</a>:</i>
<p>Yeah they would be very useful I think.</p>

<p>What I do as a workaround is:</p>

<ul class="alternate" type="square">
	<li>use a connection state listener to remember the timestamp of the latest CONNECTED/RECONNECT event</li>
	<li>save a timestamp just before the create operation</li>
	<li>if I catch NodeExistsException and if the CONNECTED/RECONNECT event is more recent than our create timestamp, then I invoke a setData instead.</li>
</ul>


<p>For the delete, I just ignore the NoNodeException in that case.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p><a href="https://github.com/apache/curator/pull/111" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/111</a></p>

<p>I checked this against your test by adding delete.quietly() and create.orSetData() and the test works.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Note, ZooKeeper devs consider this a bug in ZK: <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2288" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-2288</a></p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20ZOOKEEPER-2288">ZOOKEEPER-2288</a>]</i>
