### ISSUE TITLE
[CURATOR-284] NullPointerException at EnsembleTracker.processConfigData

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#804]
<p>While using Zookeeper 3.5.1 with Curator 3.0.0, we hit this issue:</p>

<p>org.apache.curator.framework.imps.CuratorFrameworkImpl: Background exception was not retry-able or retry gave up<br/>
! java.lang.NullPointerException: null<br/>
! at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)<br/>
! at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:163)<br/>
! at org.apache.curator.framework.imps.EnsembleTracker.access$200(EnsembleTracker.java:48)<br/>
! at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:134)<br/>
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:829)<br/>
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:611)<br/>
! at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:151)<br/>
! at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:210)<br/>
! at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619)<br/>
! at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:528)</p>

---
<details><summary><i>Originally reported by <a title="G " href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkcn">gkcn</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-284" target="_blank">NullPointerException at EnsembleTracker.processConfigData</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-01-06T20:54:07+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkcn">gkcn</a>:</i>
<p>Hi,<br/>
Thanks for resolving this.<br/>
When can we expect to get 3.0.1 from Maven?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Note: I changed this to minor as this doesn't affect functionality (other than spewing to logs). For a new release, we need to get <a href="https://issues.apache.org/jira/browse/CURATOR-209" title="Background retry falls into infinite loop of reconnection after connection loss" class="issue-link" data-issue-key="CURATOR-209"><del>CURATOR-209</del></a> out first. Then, after that.</p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-285">CURATOR-285</a>]</i>
