### ISSUE TITLE
[CURATOR-285] LeaderElection with 3.0.0

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#805]
<p>I am running 3 instances of ZooKeeper and the config is this:</p>

<p>tickTime=2000<br/>
initLimit=10<br/>
syncLimit=5<br/>
dataDir=/tmp/zookeeper1<br/>
clientPort=2181<br/>
maxClientCnxns=1000<br/>
server.1=127.0.0.1:2888:3888<br/>
server.2=127.0.0.1:2889:3889<br/>
server.3=127.0.0.1:2890:3890</p>

<p>I am using the leader election example code given here: <a href="https://git-wip-us.apache.org/repos/asf?p=curator.git;a=tree;f=curator-examples/src/main/java/leader;h=73b547eadb98995c0ccbd06a5b76d0741ffef263;hb=HEAD" class="external-link" target="_blank" rel="nofollow noopener">https://git-wip-us.apache.org/repos/asf?p=curator.git;a=tree;f=curator-examples/src/main/java/leader;h=73b547eadb98995c0ccbd06a5b76d0741ffef263;hb=HEAD</a></p>

<p>The code runs fine with TestingServer but when I change connection string to : "127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183", I get the exceptions:</p>

<p><span class="error">&#91;main-SendThread(127.0.0.1:2183)&#93;</span> INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server 127.0.0.1/127.0.0.1:2183. Will not attempt to authenticate using SASL (unknown error)<br/>
<span class="error">&#91;main-SendThread(127.0.0.1:2183)&#93;</span> INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /127.0.0.1:56111, server: 127.0.0.1/127.0.0.1:2183<br/>
<span class="error">&#91;main-SendThread(127.0.0.1:2183)&#93;</span> INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server 127.0.0.1/127.0.0.1:2183, sessionid = 0x3521552283c0000, negotiated timeout = 40000<br/>
<span class="error">&#91;main-EventThread&#93;</span> INFO org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED<br/>
<span class="error">&#91;main-SendThread(127.0.0.1:2183)&#93;</span> INFO org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x3521552283c0000, likely server has closed socket, closing socket connection and attempting reconnect<br/>
<span class="error">&#91;main-EventThread&#93;</span> INFO org.apache.curator.framework.imps.EnsembleTracker - New config event received: null<br/>
<span class="error">&#91;main-EventThread&#93;</span> ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up<br/>
java.lang.NullPointerException<br/>
    at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)<br/>
    at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:163)<br/>
    at org.apache.curator.framework.imps.EnsembleTracker.access$200(EnsembleTracker.java:48)<br/>
    at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:134)<br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:829)<br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:611)<br/>
    at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:151)<br/>
    at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:210)<br/>
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619)<br/>
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:528)<br/>
<span class="error">&#91;main-EventThread&#93;</span> INFO org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED</p>

---
<details><summary><i>Originally reported by <a title="Kunal Bharati" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kunalbharati">kunalbharati</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-285" target="_blank">LeaderElection with 3.0.0</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2017-10-06T15:24:02+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=edwardlee">edwardlee</a>:</i>
<p>see <del><a href="https://issues.apache.org/jira/browse/CURATOR-284" class="external-link" rel="nofollow">CURATOR-284</a></del></p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-284">CURATOR-284</a>]</i>
