### ISSUE TITLE
[CURATOR-299] Copious "Failed to find watcher" log messages when closing Curator 3.0 recipes

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#819]
<p><span class="error">&#91;2016-02-01 14:49:47,005&#93;</span><span class="error">&#91;ERROR&#93;</span><span class="error">&#91;org.apache.zookeeper.ClientCnxn&#93;</span> Failed to find watcher!<br/>
org.apache.zookeeper.KeeperException$NoWatcherException: KeeperErrorCode = No such watcher for /zookeeper/config<br/>
    at org.apache.zookeeper.ZooKeeper$ZKWatchManager.containsWatcher(ZooKeeper.java:377) ~<span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ZooKeeper$ZKWatchManager.removeWatcher(ZooKeeper.java:252) ~<span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.WatchDeregistration.unregister(WatchDeregistration.java:58) ~<span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:712) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn.access$1500(ClientCnxn.java:97) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:948) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:99) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1236) <span class="error">&#91;zookeeper-3.5.1-alpha.jar:3.5.1-alpha-1693007&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-299" target="_blank">Copious "Failed to find watcher" log messages when closing Curator 3.0 recipes</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-04-30T20:56:09+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/145#issuecomment-212727053" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/145#issuecomment-212727053</a></p>

<p>    Looks OK to me. A couple of thoughts though. Wouldn't it have been cleaner to overload the constructor for OperationAndData with a constructor that didn't take a Watching reference? There seems to have been a lot of changes just updating the constructor reference and passing in a null Watching reference. Same for Backgrounding.checkError.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/145#issuecomment-212742420" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/145#issuecomment-212742420</a></p>

<p>    I struggled with this PR. It ended up way more complicated than I wanted but it's difficult to simplify. </p>

<p>    > Wouldn't it have been cleaner to overload the constructor for OperationAndData with a constructor that didn't take a Watching reference</p>

<p>    I don't generally like disjointed ctors. It's harder to use correctly. </p>
