### ISSUE TITLE
[CURATOR-307] InterProcessReadWriteLock can throw IndexOutOfBoundsException when connection is lost

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#827]
<p>We are using recipe InterProcessMutex as lock for our cluster environment.<br/>
We found that it is possible that acquiring and/or releasing of lock can fail when connection to ZooKeeper is lost or changed.</p>

<p>If you have have following sample code:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">InterProcessMutex.acquire();
doSomething();
InterProcessMutex.release();
</pre>
</div></div>

<p>You can get following exception in release() method, when connection is lost after lock is acquired.<br/>
Stack trace:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IllegalMonitorStateException: You <span class="code-keyword">do</span> not own the lock: /clusters/Production/something/lock
at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:128)
</pre>
</div></div>

<p>and following stack trace when lock directory is empty (because emphemeral nodes are deleted, because of connection was lost)</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.IndexOutOfBoundsException: Index: 2147483647, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at org.apache.curator.framework.recipes.locks.InterProcessReadWriteLock.readLockPredicate(InterProcessReadWriteLock.java:190)
at org.apache.curator.framework.recipes.locks.InterProcessReadWriteLock.access$0(InterProcessReadWriteLock.java:163)
at org.apache.curator.framework.recipes.locks.InterProcessReadWriteLock$2.getsTheLock(InterProcessReadWriteLock.java:137)
at org.apache.curator.framework.recipes.locks.LockInternals.internalLockLoop(LockInternals.java:287)
at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:226)
at org.apache.curator.framework.recipes.locks.InterProcessMutex.internalLock(InterProcessMutex.java:221)
at org.apache.curator.framework.recipes.locks.InterProcessMutex.acquire(InterProcessMutex.java:77)
</pre>
</div></div>

<p>These operations should fail more gracefully, maybe with dedicated exception, when connection is lost or changed.</p>

---
<details><summary><i>Originally reported by <a title="Jakub Strolený" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jstrol">jstrol</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-307" target="_blank">InterProcessReadWriteLock can throw IndexOutOfBoundsException when connection is lost</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-07-17T07:49:49+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I can't reproduce this with any tests. Please provide a test the shows the issue. Also, I believe this is misnamed as the title is InterProcessReadWriteLock but the description is for InterProcessMutex.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>This has been fixed by <a href="https://issues.apache.org/jira/browse/CURATOR-211" title="Fix InterProcessReadWriteLock#readLockPredicate() index validation issue" class="issue-link" data-issue-key="CURATOR-211"><del>CURATOR-211</del></a>. The line context matches <tt>77a1afbcc074d9ef87ba3bfc7d3cb641ad2f727e^</tt>.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tison">tison</a>:</i>
<p>Thank <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw" class="user-hover" rel="kezhuw">Kezhu Wang</a> to give the insight. I believe this issue should be resolved by <a href="https://issues.apache.org/jira/browse/CURATOR-211" title="Fix InterProcessReadWriteLock#readLockPredicate() index validation issue" class="issue-link" data-issue-key="CURATOR-211"><del>CURATOR-211</del></a> and no longer exist on master.</p>

<p>Closed as no longer valid.</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-211">CURATOR-211</a>]</i>
