### ISSUE TITLE
[CURATOR-310] Race in PersistentNode startup

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#830]
<p>We ran into what looks like a race in PersisentNode startup:</p>

<p>java.lang.IllegalArgumentException: Path cannot be null<br/>
at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:48) ~<span class="error">&#91;curator-client-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:37) ~<span class="error">&#91;curator-client-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.utils.ZKPaths.fixForNamespace(ZKPaths.java:105) ~<span class="error">&#91;curator-client-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:104) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.framework.imps.CuratorFrameworkImpl.fixForNamespace(CuratorFrameworkImpl.java:594) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:244) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:41) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
at dmg.cells.zookeeper.CellCuratorFramework$PathAndBytesableDecorator.forPath(CellCuratorFramework.java:1369) ~<span class="error">&#91;cells-2.16.0-SNAPSHOT.jar:2.16.0-SNAPSHOT&#93;</span><br/>
at org.apache.curator.framework.recipes.nodes.PersistentNode.setData(PersistentNode.java:323) ~<span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span></p>

<p>The problem here is that PersistentNode#setData calls PersistentNode#getActualPath, however the nodePath field accessed by PersistentNode#getActualPath isn't set until PersistentNode#processBackgroundCallback is called as a result of the createNode call in PersistentNode#start. </p>

<p>I.e. if one calls PersistentNode#setData right after calling start, there is a race between the node creation initializing the actual path and PersistentNode#setData accessing it.</p>

---
<details><summary><i>Originally reported by <a title="Gerd Behrmann" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=behrmann">behrmann</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-310" target="_blank">Race in PersistentNode startup</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-03-29T18:21:30+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=behrmann">behrmann</a>:</i>
<p>In case you wonder whether the custom decorator in the stack trace has anything to do with it, it's straight call through and doesn't affect the result: </p>

<p>@Override<br/>
public T forPath(String path, byte[] data) throws Exception</p>
{
    return inner.forPath(path, data);
}

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Your assessment seems correct to me. There's definitely a race condition there.</p>

<p>I guess one option is to block on initialCreateLatch in the setData() method. This may not be desirable though as it will potentially make this method block indefinitely. Other option is to block in a separate thread, but it's a bit ugly to have to introduce this for an edge case like this.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>That's a reasonable suggestion too. I haven't looked at the code again, but I imagine that you'd need to synchronize to avoid another race condition between checking that initialization is complete and it actually completing.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/140" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/140</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-310" title="Race in PersistentNode startup" class="issue-link" data-issue-key="CURATOR-310"><del>CURATOR-310</del></a> Race in PersistentNode startup</p>

<p>    This is a semi-punt but a reasonable one. The simple solution is for the client to call waitForInitialCreate() before calling setData(). So, now, setData() throws an exception if the initial create has not occurred.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-310" title="Race in PersistentNode startup" class="issue-link" data-issue-key="CURATOR-310"><del>CURATOR-310</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/140.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/140.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #140</p>

<hr />
<p>commit f4dcec3e6f80616f76f428c25787ff3293273a5a<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2016-03-29T01:32:55Z</p>

<p>    Check for initial create in setData()</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/140#discussion_r57663597" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/140#discussion_r57663597</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java &#8212;<br/>
    @@ -317,6 +317,7 @@ public String getActualPath()<br/>
 public void setData(byte[] data) throws Exception<br/>
 {<br/>
     data = Preconditions.checkNotNull(data, "data cannot be null");<br/>
    +Preconditions.checkState(nodePath.get() != null, "initial create has not been processed. Call waitForInitialCreate() to ensure.");<br/>
     this.data.set(Arrays.copyOf(data, data.length));<br/>
    &#8212; End diff &#8211;</p>

<p>    Isn't this potentially going to break legacy clients depending on how they handle exceptions thrown from this method?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/140#discussion_r57663645" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/140#discussion_r57663645</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java &#8212;<br/>
    @@ -317,6 +317,7 @@ public String getActualPath()<br/>
 public void setData(byte[] data) throws Exception<br/>
 {<br/>
     data = Preconditions.checkNotNull(data, "data cannot be null");<br/>
    +Preconditions.checkState(nodePath.get() != null, "initial create has not been processed. Call waitForInitialCreate() to ensure.");<br/>
     this.data.set(Arrays.copyOf(data, data.length));<br/>
    &#8212; End diff &#8211;</p>

<p>    The current behavior is undefined. I can't imagine anyone is dependent on an NPE. Right?</p>
