### ISSUE TITLE
[CURATOR-325] Background retry falls into infinite loop of SessionExpiredException

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#845]
<p>after long time gc pause,which longer than zookeeper session time,the zookeeper cluster invalidate the session id holding by the client and waiting the client to reconnect,but client consider the  SessionExpiredException as retry exception and re-put to the background queue,so wo get the stacktrace infinitely.</p>

<p>12:50:54.337 <span class="error">&#91;configuration-0-EventThread&#93;</span> DEBUG org.apache.curator.RetryLoop - Retrying operation<br/>
12:50:54.337 <span class="error">&#91;configuration-0-EventThread&#93;</span> DEBUG org.apache.curator.RetryLoop - Retry-able exception received<br/>
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /dynamic/apps/258741001/DEV<br/>
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:127) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
    at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155) ~<span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:304) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:293) ~<span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) ~<span class="error">&#91;curator-client-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:290) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:281) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl$1.forPath(GetDataBuilderImpl.java:105) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl$1.forPath(GetDataBuilderImpl.java:65) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at com.ctrip.flight.configuration.client.AbstractZookeeperClient.getData(AbstractZookeeperClient.java:68) <span class="error">&#91;classes/:na&#93;</span><br/>
    at com.ctrip.flight.configuration.client.ZooKeeperConfigurationSource.getPublishNodeValue(ZooKeeperConfigurationSource.java:258) <span class="error">&#91;classes/:na&#93;</span><br/>
    at com.ctrip.flight.configuration.client.ZooKeeperConfigurationSource.access$100(ZooKeeperConfigurationSource.java:45) <span class="error">&#91;classes/:na&#93;</span><br/>
    at com.ctrip.flight.configuration.client.ZooKeeperConfigurationSource$1.nodeChanged(ZooKeeperConfigurationSource.java:105) <span class="error">&#91;classes/:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:310) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:304) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) <span class="error">&#91;guava-19.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:302) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:269) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:56) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:122) <span class="error">&#91;curator-recipes-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:256) <span class="error">&#91;curator-framework-2.10.0.jar:na&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span><br/>
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) <span class="error">&#91;zookeeper-3.4.6.jar:3.4.6-1569965&#93;</span></p>

---
<details><summary><i>Originally reported by <a title="clive du" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wlongdu">wlongdu</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-325" target="_blank">Background retry falls into infinite loop of SessionExpiredException</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Can you provide a test case that shows the problem. Session expiration <em>should</em> be a retry. Internally, Curator will recreate the ZooKeeper handle when the session expires so I don't see why this is a problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wlongdu">wlongdu</a>:</i>
<p>at first hand, I think I should describe the use case, I use NodeCache provided by recipe, and handle node change event in the thread curator do the background operation. secondly,  long gc pause shouldn't happen in normal case,but do  in extreme case, I simulate this case in debug mode, I toggle a break point on onNodeChanged implement code, and pause for a long time, when I step over ,I see the stacktrace periodically</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robiplus">robiplus</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wlongdu" class="user-hover" rel="wlongdu">clive du</a></p>

<p>Hi, I seem meet a similar problem..</p>

<p>After div into code, I found this problem is caused by read data(getData or getChild) with `RetryForever like` retry policy in our custom watcher implements.</p>

<p>As result,  when session closed, EventThread maybe fall into retry infinite loop in custom watcher, and no any chance to give curator's watcher &#8212; `ConnectionState#process` to handleExpiredSession and make `ClientCnxn#state` alive again(which is needed to break infinite loop).</p>

<p>This problem can be solve if  we don't modify zookeeper/curator:</p>

<ul class="alternate" type="square">
	<li>not use forever retry policy..and infinite loop for "a while" - -</li>
	<li>or like `PathCache` does, send task to another thread after receive WatchedEvent</li>
</ul>


<p>but I think it seems a hole that user defined watcher may block framework watcher, but framework watcher  is vital to user's watcher finish work..</p>

<p>Is any ideal curator can do to improve this problem ^ ^?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>As I said, we need a test case and, ideally, a Pull Request with the fix.</p>
