### ISSUE TITLE
[CURATOR-337] LeaderSelector logs stack trace with "The leader threw an exception" message erroneously

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#857]
<p>I am using the LeaderSelector to choose a leader for a particular role in my cluster. Every time that I call close() on the leader selector, I end up with the following stack trace in my logs:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">2016-07-20 20:20:47,814 ERROR [Leader Election Notification <span class="code-object">Thread</span>-1] o.a.c.f.recipes.leader.LeaderSelector The leader threw an exception
java.lang.IllegalMonitorStateException: You <span class="code-keyword">do</span> not own the lock: /leaders/Cluster Coordinator
        at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:140) ~[curator-recipes-2.10.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:425) [curator-recipes-2.10.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.10.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.10.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.10.0.jar:na]
        at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.10.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_74]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
        at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [na:1.8.0_74]
</pre>
</div></div>

<p>This appears to be due to the fact that in LeaderSelector.doWork(), we call mutex.acquire() and then if an InterruptedException is thrown, the finally block calls mutex.release() even though the mutex has not been acquired. The finally block, then, should read:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">if</span> ( hasLeadership )
{
    hasLeadership = <span class="code-keyword">false</span>;
    <span class="code-keyword">try</span>
    {
 mutex.release();
    }
    <span class="code-keyword">catch</span> ( Exception e )
    {
ThreadUtils.checkInterrupted(e);
log.error(<span class="code-quote">"The leader threw an exception"</span>, e);
<span class="code-comment">// ignore errors - <span class="code-keyword">this</span> is just a safety
</span>    }
}
</pre>
</div></div>

<p>That is, we should execute the body of the finally block only if hasLeadership == true.</p>

---
<details><summary><i>Originally reported by <a title="Mark Payne" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=markap14">markap14</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-337" target="_blank">LeaderSelector logs stack trace with "The leader threw an exception" message erroneously</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Cam McKenzie" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-07-28T01:55:44+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>That looks like a reasonable assessment. Would happily review a PR if you'd like to provide one. Otherwise, I will fix it when I get a minute.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user markap14 opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/158" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/158</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a>: Do not attempt to release a mutex unless it has actually been acquired</p>

<p>    \Do not attempt to release a mutex unless it has actually been acquired</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/markap14/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/markap14/curator</a> master</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/158.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/158.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #158</p>

<hr />
<p>commit fe19a8c9c5523a08cab1a0e16ec536e35c0a65b7<br/>
Author: Mark Payne <markap14@hotmail.com><br/>
Date:   2016-07-28T00:17:40Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a>: Do not attempt to release a mutex unless it has actually been acquired</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user markap14 closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/158" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/158</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user markap14 opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/159" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/159</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a>: Do not attempt to release a mutex unless it has actually been acquired</p>

<p>    Do not attempt to release a mutex unless it has actually been acquired</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/markap14/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/markap14/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/159.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/159.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #159</p>

<hr />
<p>commit 6cebfc13ccdcd9cb2a5b576fa369b957e651752a<br/>
Author: Mark Payne <markap14@hotmail.com><br/>
Date:   2016-07-28T00:23:13Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a>: Do not attempt to release a mutex unless it has actually been acquired</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=markap14">markap14</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> - thanks, happy to open the PR. Unfortunately, I made a mistake when i created it the first time so you can ignore PR 158 and just look at PR 159.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/159" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/159</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Thanks for the patch!</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-468">CURATOR-468</a>]</i>
