### ISSUE TITLE
[CURATOR-344] SharedValue watcher should limit work to valid data change events 

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#864]
<p>With a RetryNTimes retry policy and a disconnect. The event thread can get blocked on retries from the SharedValue watcher readValue, blocking other listeners from getting the SUSPENDED event till retry completes.<br/>
Seems the watcher should limit work and notifications to valid change events and ignore a disconnect. The ConnectionStateListener already handles those.</p>

<p>Sample thread stack that blocks other listeners:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">main-EventThread" daemon prio=10 tid=0x00007f95d009f000 nid=0x3429 waiting on condition [0x00007f959d6d5000]
   java.lang.<span class="code-object">Thread</span>.State: TIMED_WAITING (sleeping)
	at java.lang.<span class="code-object">Thread</span>.sleep(Native Method)
	at java.lang.<span class="code-object">Thread</span>.sleep(<span class="code-object">Thread</span>.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:360)
	at org.apache.curator.RetryLoop$1.sleepFor(RetryLoop.java:74)
	at org.apache.curator.retry.SleepingRetry.allowRetry(SleepingRetry.java:46)
	at org.apache.curator.retry.RetryNTimes.allowRetry(RetryNTimes.java:24)
	at org.apache.curator.RetryLoop.takeException(RetryLoop.java:188)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:112)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:287)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:279)
	at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:41)
	at org.apache.curator.framework.recipes.shared.SharedValue.readValue(SharedValue.java:192)
	- locked <0x000000074326fb50> (a org.apache.curator.framework.recipes.shared.SharedValue)
	at org.apache.curator.framework.recipes.shared.SharedValue.access$100(SharedValue.java:42)
	at org.apache.curator.framework.recipes.shared.SharedValue$1.process(SharedValue.java:58)
	at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:67)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Gary Tully" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gtully">gtully</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-344" target="_blank">SharedValue watcher should limit work to valid data change events </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-08-31T02:02:38+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user gtully opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-344" title="SharedValue watcher should limit work to valid data change events " class="issue-link" data-issue-key="CURATOR-344"><del>CURATOR-344</del></a> - limit shared value watcher to valid change events to av…</p>

<p>    …oid work on disconnect.</p>

<p>    Test that shows the difficulty with blocking the event thread. <br/>
    When the framework is shared and one use case needs timely notification of suspend, a use case that requires retry for some period gets in the way.</p>

<p>    In any event, on a disconnect, there may or may not be change, it does not make sense to me that the listeners should be fired.</p>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/gtully/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/gtully/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-344" title="SharedValue watcher should limit work to valid data change events " class="issue-link" data-issue-key="CURATOR-344"><del>CURATOR-344</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/161.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #161</p>

<hr />
<p>commit f89ddfafb45c4656ea34474f061ca902c7060116<br/>
Author: gtully <gary.tully@gmail.com><br/>
Date:   2016-08-18T18:34:10Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-344" title="SharedValue watcher should limit work to valid data change events " class="issue-link" data-issue-key="CURATOR-344"><del>CURATOR-344</del></a> - limit shared value watcher to valid change events to avoid work on disconnect</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gtully">gtully</a>:</i>
<p>Added a test and fix in: <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a><br/>
It makes sense to me and does not break any of the existing tests.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    I don't think that this completely fixes the problem. The test fails intermittently because it's possible that the server gets stopped while the SharedValue is processing the initial connected event. When this happens, it goes through the retry loop and the assertion at the end of the test fails.</p>

<p>    I think that ultimately the processing that occurs within the watcher's process() method should be run asynchronously, and equally, the watcher should be more discriminant about which events it's interested in.</p>

<p>    Thoughts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user gtully commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    Thanks for taking the time to peek at this. I agree. <br/>
    Doing everything async will make it a little heaver weight but I think it is more correct. <br/>
    There seems to be be some recipes that take executors, others that don't, but I have not figured out if there is some pattern to this. Do you know?</p>

<p>    Short term, I can fix up the unit test to be deterministic (i.e. wait for connected).<br/>
    Maybe this can be tackled in two phases. The first making the watcher more discriminating. For my use case, disconnecting is the important event.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    I'm not sure on the pattern for executors, probably just the whim of whoever implemented the recipe I imagine.</p>

<p>    I think that you should be able to do this asynchronously without an executor though. If you change the readValue() method to have an option of executing in the background then it should fix the problem I think. When being called from the Watcher, you would make the readValue getData() call in the background and update the shared value in the asynchronous callback.</p>

<p>    That should fix the problem properly and not require the introduction of an executor. I think that we should clean up the events which actually result in the readValue() being called from the Watcher too.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user gtully commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    thanks for the feedback.<br/>
    I fixed up the unit test to make it more deterministic.<br/>
    Changed the watcher to do an update and notification in the background.<br/>
    That sorts my use case however the update events should only fire on valid change events.<br/>
    Added additional unit test to track change events between disconnect and reconnect and made the matching change to restrict the callback to valid change events.<br/>
    I think it is better on both counts.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>

<p>    Looks good to me, thanks for the patch!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/161" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/161</a></p>
