### ISSUE TITLE
[CURATOR-345] NPE in EnsembleTracker when starting Curator

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#865]
<p>We're currently getting a NPE when running Curator 3.1.0 and 3.2.0 in our environment. I don't believe this was occurring before we upgraded to ZooKeeper 3.5.1-alpha and Curator 3.1.0.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> java.lang.NullPointerException
 	at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:171) ~[curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:186) ~[curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50) ~[curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:144) ~[curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:835) [curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:618) [curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152) [curator-framework-3.2.0.jar:3.2.0]
	at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:214) [curator-framework-3.2.0.jar:3.2.0]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:587) [zookeeper-3.5.1-alpha.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499) [zookeeper-3.5.1-alpha.jar:?]
</pre>
</div></div>

<p>The problem is that the QuorumServer.clientAddr here is null. This seems to be filled by parsing the ZooKeeper server properties, which look something like:</p>

<blockquote>
<p>server.1=zoo1:2888:3888<br/>
server.2=zoo2:2888:3888<br/>
server.3=zoo3:2888:3888</p></blockquote>

<p>In the QuorumServer constructor, we parse each server line into its respective tasks. The clientAddr, however, is filled by splitting the line around a semicolon and taking the second part:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-object">String</span>[] serverClientParts = addressStr.split(<span class="code-quote">";"</span>);
...
<span class="code-keyword">if</span>(serverClientParts.length == 2) {
    <span class="code-object">String</span>[] e = splitWithLeadingHostname(serverClientParts[1]);
    <span class="code-keyword">if</span>(e.length > 2) {
<span class="code-keyword">throw</span> <span class="code-keyword">new</span> ConfigException(addressStr + <span class="code-quote">" does not have the form server_config or server_config;client_config where server_config is host:port:port or host:port:port:type and client_config is port or host:port"</span>);
    }

    <span class="code-object">String</span> hostname = e.length == 2?e[0]:<span class="code-quote">"0.0.0.0"</span>;
    ...
}
</pre>
</div></div>

<p>This suggests that the server string should be followed by a client host/port (or just port), e.g.:</p>

<blockquote>
<p>server.1=zoo1:2888:3888;2181<br/>
server.2=zoo2:2888:3888;2181<br/>
server.3=zoo3:2888:3888;localhost:2181</p></blockquote>

<p>I can't find anything in the ZooKeeper documentation about this though, and it isn't mandatory in the properties (so shouldn't throw a NPE).</p>

<p>This occurs every time we start the server, but doesn't affect functionality, hence the Minor flag. It would be nice to know what exactly is expected here though, so we can get rid of the exception.</p>

---
<details><summary><i>Originally reported by <a title="Alex Rankin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Kenco">Kenco</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-345" target="_blank">NPE in EnsembleTracker when starting Curator</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-09-30T13:44:03+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenco">kenco</a>:</i>
<p>Looks like I found the correct documentation (in the 3.4 documentation):</p>

<p><a href="https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#sc_reconfig_clientport" class="external-link" target="_blank" rel="nofollow noopener">https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#sc_reconfig_clientport</a></p>

<p>It unfortunately isn't actually listed in the 3.5.1.alpha documentation, but the value is the old clientPort value. This value apparently shouldn't be used in the zoo.cfg, but it still can be without issue, so this bug is still valid.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>I now wonder how this code ever worked. shouldn't configToConnectionString() be using server.addr not server.clientAddr? Is there any reason not to go to server.addr?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/166" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/166</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-345" title="NPE in EnsembleTracker when starting Curator" class="issue-link" data-issue-key="CURATOR-345"><del>CURATOR-345</del></a> clientAddr might be null in which case addr should be used.</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-345" title="NPE in EnsembleTracker when starting Curator" class="issue-link" data-issue-key="CURATOR-345"><del>CURATOR-345</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/166.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/166.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #166</p>

<hr />
<p>commit 1998491612c2b2658d776b6a71de41ac3d20e0f2<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2016-09-28T10:10:38Z</p>

<p>    clientAddr might be null in which case addr should be used.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/166" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/166</a></p>

<p>    Looks ok to me</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/166" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/166</a></p>
