### ISSUE TITLE
[CURATOR-358] Receiving KeeperException with NoNode when LeaderLatch#getLeader()

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#878]
<p>org.apache.curator.framework.recipes.leader.LeaderLatch#getLeader() throws KeeperException with Code#NONODE intermittently as mentioned in the stack trace below. It may be possible  participant's ephemeral ZK node is removed because its connection/session is closed. </p>

<p>You can see the below code at <a href="https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L451" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L451</a><br/>
public Participant getLeader() throws Exception<br/>
{<br/>
    Collection<String> participantNodes = LockInternals.getParticipantNodes(client, latchPath, LOCK_NAME, sorter);<br/>
    return LeaderSelector.getLeader(client, participantNodes);<br/>
}</p>

<p>I guess it hits a race condition where a participant node is retrieved but when it invokes LeaderSelector#getLeader() it would have been removed because of session timeout and it throws KeeperException with NoNode code. It does not retry as the RetryLoop retries only for connection/session timeouts. But in this case, NoNode should have been retried. I could not find any APIs on CuratorClient to configure the kind of KeeperException codes to be retried. It may be good to have a way to take what kind of errors should be retried in org.apache.curator.framework.CuratorFrameworkFactory.Builder APIs. </p>

<p>Intermittent Exception found with the stack trace:<br/>
2016-11-15 06:09:33.954 o.a.s.d.nimbus <span class="error">&#91;ERROR&#93;</span> Error when processing event<br/>
org.apache.storm.shade.org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /storm/leader-lock/_c_97c09eed-5bba-4ac8-a05f-abdc4e8e95cf-latch-0000000002<br/>
     at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:111)<br/>
     at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)<br/>
     at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:304)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:293)<br/>
     at org.apache.storm.shade.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:290)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:281)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:42)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderSelector.participantForPath(LeaderSelector.java:375)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderSelector.getLeader(LeaderSelector.java:346)<br/>
     at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.getLeader(LeaderLatch.java:454)</p>

---
<details><summary><i>Originally reported by <a title="Satish Duggana" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-358" target="_blank">Receiving KeeperException with NoNode when LeaderLatch#getLeader()</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2016-11-22T22:11:42+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user cammckenzie opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/173" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/173</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-358" title="Receiving KeeperException with NoNode when LeaderLatch#getLeader()" class="issue-link" data-issue-key="CURATOR-358"><del>CURATOR-358</del></a> - Fixed race condition with getLeader()</p>

<p>    -If leadership changes between the getParticipantNodes() call and the getLeader() internal call the NoNodeException is now handled and the next child in the list is evaluated.</p>

<p>    Another option would be to just return the default empty Participant object and not iterate over the whole list of participants.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-358" title="Receiving KeeperException with NoNode when LeaderLatch#getLeader()" class="issue-link" data-issue-key="CURATOR-358"><del>CURATOR-358</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/173.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/173.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #173</p>

<hr />
<p>commit 3478aca7ed6852484b5574a6082f4bb75c04a1e0<br/>
Author: Cam McKenzie <cammckenzie@apache.org><br/>
Date:   2016-11-20T23:38:15Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-358" title="Receiving KeeperException with NoNode when LeaderLatch#getLeader()" class="issue-link" data-issue-key="CURATOR-358"><del>CURATOR-358</del></a> - Fixed race condition with getLeader()<br/>
    -If leadership changes between the getParticipantNodes() call and the getLeader() internal call the NoNodeException is now handled and the next child in the list is evaluated.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/173#discussion_r88829307" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/173#discussion_r88829307</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java &#8212;<br/>
    @@ -341,11 +342,41 @@ public Participant getLeader() throws Exception</p>

<p> static Participant getLeader(CuratorFramework client, Collection<String> participantNodes) throws Exception<br/>
 {<br/>
    +Participant result = null;<br/>
    +<br/>
     if ( participantNodes.size() > 0 )<br/>
     {</p>
<ul class="alternate" type="square">
	<li>return participantForPath(client, participantNodes.iterator().next(), true);<br/>
    +    Iterator<String> iter = participantNodes.iterator();<br/>
    +    while ( iter.hasNext() )<br/>
    +    {<br/>
    +<br/>
    +try<br/>
    +{<br/>
    +    result = participantForPath(client, iter.next(), true);
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Why not have `participantForPath()` handle the exception and return `null`?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/173#discussion_r89223241" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/173#discussion_r89223241</a></p>

<p>    &#8212; Diff: curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java &#8212;<br/>
    @@ -341,11 +342,41 @@ public Participant getLeader() throws Exception</p>

<p> static Participant getLeader(CuratorFramework client, Collection<String> participantNodes) throws Exception<br/>
 {<br/>
    +Participant result = null;<br/>
    +<br/>
     if ( participantNodes.size() > 0 )<br/>
     {</p>
<ul class="alternate" type="square">
	<li>return participantForPath(client, participantNodes.iterator().next(), true);<br/>
    +    Iterator<String> iter = participantNodes.iterator();<br/>
    +    while ( iter.hasNext() )<br/>
    +    {<br/>
    +<br/>
    +try<br/>
    +{<br/>
    +    result = participantForPath(client, iter.next(), true);
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Yep, fair call, it's probably more Java like to just return. I've probably been writing too much C code lately!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=satish.duggana">satish.duggana</a>:</i>
<p>When will 2.11.2 release be out? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>I wouldn't think it will be any time super soon  as 2.11.1 only got released in the last couple of weeks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=general zod">general zod</a>:</i>
<p>It seems to me that this ticket deals with a problem in LeaderLatch whereas the PR on github fixes an issue in LeaderSelector. Am I missing something or should this ticket be reopened as we're still seeing this issue in LeaderLatch (used by storm-nimbus component)?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>At this point, it makes more sense to open a new issue. I took a quick look at the code and the problem can be fixed inside of LockInternals I think easily.</p>
