### ISSUE TITLE
[CURATOR-364] Persistent Node Constructor Requires a Started ZK Connection

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#884]
<p><b>Steps to reproduce:</b><br/>
1. Initialise an instance of PersistentNode<br/>
2. Ensure that CuratorFramework is Not Started (Latent)</p>

<p><b>Expected behaviour:</b><br/>
PersistentNode constructor should work without an active CuratorFramework connection to ZK</p>

<p><b>Actual behaviour</b>:<br/>
An Exception is thrown:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: java.lang.IllegalStateException: instance must be started before calling <span class="code-keyword">this</span> methodDEBUG [2016-12-14 10:25:25,641] akka.event.EventStream: logger log1-Slf4jLogger started

	at com.google.common.base.Preconditions.checkState(Preconditions.java:150)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.create(CuratorFrameworkImpl.java:351)
	at org.apache.curator.framework.recipes.nodes.PersistentNode.<init>(PersistentNode.java:173)
</pre>
</div></div>

<p><b>Thoughts</b><br/>
This behaviour is inconsistent with other Zk recepies based on Closable interface. PersistentNode should not attempt any Zk communication until start() method is called.</p>

---
<details><summary><i>Originally reported by <a title="Ilya Biryukov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iBiryukov">iBiryukov</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-364" target="_blank">Persistent Node Constructor Requires a Started ZK Connection</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-01-09T16:28:13+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ilyabiryukov-r7 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

<p>    Hey guys, are we ok to merge this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Thank you!</p>
