### ISSUE TITLE
[CURATOR-366] curator hangup and throw a CuratorConnectionLossException after timeout

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#886]
<p>here is the traceback:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:243)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:237)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:234)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:218)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:42)
</pre>
</div></div>
<p>i have tried the curator version of 2.6.0, 2.7.1, 2.9.1, 2.10.0,  the version of zookeeper server is 3.3.5</p>

---
<details><summary><i>Originally reported by <a title="xsank mar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-366" target="_blank">curator hangup and throw a CuratorConnectionLossException after timeout</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2016-12-22T02:28:17+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Why is this a bug? You've merely pasted a stack trace. Please provide details on what the issue is, how to reproduce it, etc.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>:</i>
<p>everytime i use the curator to operate the zookeeper, it will hang up, i have watched the detail of the client, it is started, the zookeeper works well and the zk-url is right.<br/>
I have used the zkcli script (version 3.4.6) to connect the zookeeper server ,it works fine as well.<br/>
I have tested the curator version 2.6.0,2.7.1,2.9.1...  All with the same problem. Start ok but operation throw exception.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Please post a code sample that shows the problem.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>:</i>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">server = <span class="code-keyword">new</span> TestingServer();
server.start();
</pre>
</div></div>
<p>then use the server.getConnectString() as the zkurl</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">client = CuratorFrameworkFactory.builder().connectString(url).namespace(ROOT_PATH)
.retryPolicy(<span class="code-keyword">new</span> RetryNTimes(DEFAULT_CONNECTION_RETRY_COUNT, DEFAULT_CONNECTION_RETRY_TIMEOUT))
.connectionTimeoutMs(DEFAULT_CONNECTION_TIMEOUT).build();
client.start();
</pre>
</div></div>
<p>then start the client, the status was START, then create a node that not exist.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">this</span>.client.create().creatingParentsIfNeeded().withMode(CreateMode.EPHEMERAL).forPath(path);
</pre>
</div></div>
<p>now just hang there and until throw exception.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>:</i>
<p>the framwork,recipes,test version are all 2.9.1</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>:</i>
<p>in fact, all the operation such as:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">client.getChildren();
client.delete();
client.create();
</pre>
</div></div>
<p>will hang there end with error code CONNECTIONLOSS</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>This isn't a bug. To get support and discuss how to use Curator please use the mailing lists. See <a href="https://curator.apache.org" class="external-link" target="_blank" rel="nofollow noopener">https://curator.apache.org</a></p>
