### ISSUE TITLE
[CURATOR-368] powermock will cause curator CONNECTIONLOSS exception

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#888]
<p>client code</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"><span class="code-keyword">public</span> <span class="code-keyword">class </span>CuratorClient {
    <span class="code-keyword">private</span> CuratorFramework client;

    <span class="code-keyword">public</span> CuratorClient(<span class="code-object">String</span> url) {
<span class="code-keyword">this</span>.client = CuratorFrameworkFactory.builder().connectString(url).namespace(<span class="code-quote">"test"</span>)
.retryPolicy(<span class="code-keyword">new</span> RetryNTimes(3, 5000))
.connectionTimeoutMs(3000).build();
<span class="code-keyword">this</span>.client.start();
    }

    <span class="code-keyword">public</span> void create(<span class="code-object">String</span> path) {
<span class="code-keyword">try</span> {
    <span class="code-keyword">this</span>.client.create().creatingParentsIfNeeded().withMode(CreateMode.EPHEMERAL).forPath(path);
} <span class="code-keyword">catch</span> (Exception e) {
    e.printStackTrace();
}
    }

    <span class="code-keyword">public</span> void lsChildren(<span class="code-object">String</span> path) {
<span class="code-keyword">try</span> {
    List<<span class="code-object">String</span>> children = <span class="code-keyword">this</span>.client.getChildren().forPath(path);
    <span class="code-keyword">for</span> (<span class="code-object">String</span> child : children) {
<span class="code-object">System</span>.out.println(child);
    }
} <span class="code-keyword">catch</span> (Exception e) {
    e.printStackTrace();
}
    }

    <span class="code-keyword">public</span> void close() {
<span class="code-keyword">this</span>.client.close();
    }
}
</pre>
</div></div>
<p>Test code</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">@RunWith(PowerMockRunner.class)
@PrepareForTest({Static.class})
<span class="code-keyword">public</span> <span class="code-keyword">class </span>CuratorTest {
    <span class="code-keyword">private</span> CuratorClient client;
    <span class="code-keyword">private</span> TestingServer server;

    @Before
    <span class="code-keyword">public</span> void setUp() <span class="code-keyword">throws</span> Exception {
server = <span class="code-keyword">new</span> TestingServer();
server.start();
client = <span class="code-keyword">new</span> CuratorClient(server.getConnectString());
    }

    @After
    <span class="code-keyword">public</span> void tearDown() <span class="code-keyword">throws</span> Exception {
client.close();
server.close();
    }

    @Test
    <span class="code-keyword">public</span> void testCreate() <span class="code-keyword">throws</span> Exception {
client.create(<span class="code-quote">"/curator"</span>);
    }

    @Test
    <span class="code-keyword">public</span> void lsChildren() <span class="code-keyword">throws</span> Exception {
client.lsChildren(<span class="code-quote">"/curator"</span>);
    }
}
</pre>
</div></div>
<p>now start testing, you will catch the exception everytime:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:195)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:487)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at org.alibaba.search.client.CuratorClient.create(CuratorClient.java:25)
	at org.alibaba.search.client.CuratorTest.testCreate(CuratorTest.java:35)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="xsank mar" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-368" target="_blank">powermock will cause curator CONNECTIONLOSS exception</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Invalid
<li><b>resolved</b>: 2023-08-07T08:17:05+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xsank">xsank</a>:</i>
<p>the static class have a static method should be mocked.  You need not care about the detail.<br/>
What matters is the annotation:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">@RunWith(PowerMockRunner.class)
@PrepareForTest({Static.class})
</pre>
</div></div>
