### ISSUE TITLE
[CURATOR-378] Dependency Refresh

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#898]
<p>It's about time we update the versions of our dependencies. Get the latest Apache parent POM, Maven plugins, etc.</p>

---
<details><summary><i>Originally reported by <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-378" target="_blank">Dependency Refresh</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Fangmin Lv" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lvfangmin">lvfangmin</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-07-21T18:51:26+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user lvfangmin opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-378" title="Dependency Refresh" class="issue-link" data-issue-key="CURATOR-378"><del>CURATOR-378</del></a> Update mvn parent pom, plugin and other dependency version</p>

<p>    Update the dependencies version to the version which is most widely used.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/lvfangmin/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/lvfangmin/curator</a> update_dependency</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/204.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #204</p>

<hr />
<p>commit c8e9f93dfd4a0f5e21c23b314b142e148c61b234<br/>
Author: Fangmin Lyu <allenlyu@fb.com><br/>
Date:   2017-03-11T23:59:45Z</p>

<p>    update mvn parent pom, plugin and other dependency version</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/204#discussion_r105804055" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204#discussion_r105804055</a></p>

<p>    &#8212; Diff: pom.xml &#8212;<br/>
    @@ -62,22 +62,22 @@</p>

<p>     <br/>
     <zookeeper-version>3.4.8</zookeeper-version></p>
<ul class="alternate" type="square">
	<li><maven-project-info-reports-plugin-version>2.7</maven-project-info-reports-plugin-version></li>
	<li><maven-bundle-plugin-version>2.3.7</maven-bundle-plugin-version></li>
	<li><maven-javadoc-plugin-version>2.10.3</maven-javadoc-plugin-version></li>
	<li><doxia-module-confluence-version>1.6</doxia-module-confluence-version><br/>
    +<maven-project-info-reports-plugin-version>2.9</maven-project-info-reports-plugin-version><br/>
    +<maven-bundle-plugin-version>3.2.0</maven-bundle-plugin-version><br/>
    +<maven-javadoc-plugin-version>2.10.4</maven-javadoc-plugin-version><br/>
    +<doxia-module-confluence-version>1.7</doxia-module-confluence-version><br/>
     <maven-license-plugin-version>1.9.0</maven-license-plugin-version></li>
	<li><javassist-version>3.18.1-GA</javassist-version><br/>
    +<javassist-version>3.20.0-GA</javassist-version><br/>
     <commons-math-version>2.2</commons-math-version><br/>
     <jackson-mapper-asl-version>1.9.13</jackson-mapper-asl-version><br/>
     <jersey-version>1.18.1</jersey-version><br/>
     <jsr311-api-version>1.1.1</jsr311-api-version><br/>
     <jetty-version>6.1.26</jetty-version><br/>
     <scannotation-version>1.0.2</scannotation-version><br/>
     <resteasy-jaxrs-version>2.3.0.GA</resteasy-jaxrs-version></li>
	<li><guava-version>16.0.1</guava-version><br/>
    +<guava-version>19.0</guava-version>
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    currently, 19.0 is the version which is most widely used, so I picked it, I'm not against of using 20.0 though.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/204#discussion_r105804310" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204#discussion_r105804310</a></p>

<p>    &#8212; Diff: pom.xml &#8212;<br/>
    @@ -62,22 +62,22 @@</p>

<p>     <br/>
     <zookeeper-version>3.4.8</zookeeper-version></p>
<ul class="alternate" type="square">
	<li><maven-project-info-reports-plugin-version>2.7</maven-project-info-reports-plugin-version></li>
	<li><maven-bundle-plugin-version>2.3.7</maven-bundle-plugin-version></li>
	<li><maven-javadoc-plugin-version>2.10.3</maven-javadoc-plugin-version></li>
	<li><doxia-module-confluence-version>1.6</doxia-module-confluence-version><br/>
    +<maven-project-info-reports-plugin-version>2.9</maven-project-info-reports-plugin-version><br/>
    +<maven-bundle-plugin-version>3.2.0</maven-bundle-plugin-version><br/>
    +<maven-javadoc-plugin-version>2.10.4</maven-javadoc-plugin-version><br/>
    +<doxia-module-confluence-version>1.7</doxia-module-confluence-version><br/>
     <maven-license-plugin-version>1.9.0</maven-license-plugin-version></li>
	<li><javassist-version>3.18.1-GA</javassist-version><br/>
    +<javassist-version>3.20.0-GA</javassist-version><br/>
     <commons-math-version>2.2</commons-math-version><br/>
     <jackson-mapper-asl-version>1.9.13</jackson-mapper-asl-version><br/>
     <jersey-version>1.18.1</jersey-version><br/>
     <jsr311-api-version>1.1.1</jsr311-api-version><br/>
     <jetty-version>6.1.26</jetty-version><br/>
     <scannotation-version>1.0.2</scannotation-version><br/>
     <resteasy-jaxrs-version>2.3.0.GA</resteasy-jaxrs-version></li>
	<li><guava-version>16.0.1</guava-version><br/>
    +<guava-version>19.0</guava-version>
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    I don't really have a strong preference either way, I don't use guava a great deal outside Curator, so I'm happy to defer to those who use it more. @Randgalt?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hdeadman commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    They deleted at least one method in guava 21 that curator is still using. I am trying to use <a href="http://github.com/apereo/cas" class="external-link" target="_blank" rel="nofollow noopener">http://github.com/apereo/cas</a> with spring-cloud-zookeeper and I need to use an older version of guava or I get a NoSuchMethodError error. I can probably get away with using an older version of guava in CAS but it would be nice if curator worked with 21.  </p>

<p>    ```java<br/>
    Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;<br/>
    at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:41) ~<span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:257) ~<span class="error">&#91;curator-framework-2.10.0.jar:?&#93;</span><br/>
    at org.springframework.cloud.zookeeper.ZookeeperAutoConfiguration.curatorFramework(ZookeeperAutoConfiguration.java:70) ~<span class="error">&#91;spring-cloud-zookeeper-core-1.0.3.RELEASE.jar:1.0.3.RELEASE&#93;</span><br/>
    ```</p>

<p>    Here is where they deleted the deprecated method: <span class="error">&#91;Guava commit&#93;</span>(<a href="https://github.com/google/guava/commit/f67ab864bde63fa6602b5688de0440957ffeaa2e#diff-7a493427c77df959295f1d55574dbd50" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/google/guava/commit/f67ab864bde63fa6602b5688de0440957ffeaa2e#diff-7a493427c77df959295f1d55574dbd50</a>)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    @hdeadman as of Curator 2.12.0/3.3.0 Guava is shaded into Curator and there should be no more dependency clashes. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    This doesn't compile. TestStringsWithRestEasy.java is using `ByteStreams.newInputStreamSupplier()` which no longer exists in Guava.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user beihaifeiwu commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Hi @Randgalt, I am using curator 2.12.0 , but the class org.apache.curator.framework.listen.ListenerContainer is still use guava utils directly not the shaded one</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    `MoreExecutors` is shaded. If you look inside the JAR and/or decompile those classes you'll it. We use Maven's shade plugin to do this at compile time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    I don't understand. `com.google.common.util.concurrent.MoreExecutors` is a Google class not a Curator class. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user beihaifeiwu commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    @Randgalt Sorry about that, I see what you mean, I only see the source code not the decompile. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Here's a disassembly of that class from Curator 3.3.0. Notice that all uses of MoreExecutors is the shaded version. <a href="https://gist.github.com/Randgalt/3fcdca337a2f8527a3f7ee871852f456" class="external-link" target="_blank" rel="nofollow noopener">https://gist.github.com/Randgalt/3fcdca337a2f8527a3f7ee871852f456</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    @lvfangmin Can you bring this PR up to date please?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    @Randgalt sorry for the delay, rebased onto master, the test is still running on my mac, will make sure everything passed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    There are tests failure, those tests also failed before this patch on master, @Randgalt just saw you created Jira: <a href="https://issues.apache.org/jira/browse/CURATOR-419" title="CURATOR-397 broke some tests (and introduced new problems) - Fix these tests" class="issue-link" data-issue-key="CURATOR-419"><del>CURATOR-419</del></a>, is it related? I'll take a look later today.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Probably - I should have them fixed in the next day or so</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Master is building with all tests on Jenkins now. FYI</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    @lvfangmin can you merge this into master please?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Sure, was waiting for a LGTM, I'll merge it today.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

<p>    Has merged this into master.</p>

<p>    (Renamed my local branch to <a href="https://issues.apache.org/jira/browse/CURATOR-378" title="Dependency Refresh" class="issue-link" data-issue-key="CURATOR-378"><del>CURATOR-378</del></a>, and forgot to update here, that's why this is not show as closed, will manually close it.)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/204" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/204</a></p>

**Comment by jira-importer** [comment]
<i>[Originally duplicated by: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-398">CURATOR-398</a>]</i>
