### ISSUE TITLE
[CURATOR-392] Zookeeper Ensemble Get Incorrect Address

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#912]
<p>I've noticed an issue with Curator 3.2.1 which relates to the fix from <a href="https://issues.apache.org/jira/browse/CURATOR-345" title="NPE in EnsembleTracker when starting Curator" class="issue-link" data-issue-key="CURATOR-345"><del>CURATOR-345</del></a> (also reported by me).</p>

<p>When we would reconnect after losing connection to Zookeeper (due to network issues), our services would always have the wrong connection string, and never manage to reconnect to the Zookeeper cluster. Assuming that 10.1.2.3 is our zookeeper server, and we have two scenarios (with different zoo.cfg files) we were seeing the following results when a reconnection was established:</p>

<blockquote>
<p><b>Scenario 1:</b> ClientCnxn - Opening socket connection to server 0.0.0.0/0.0.0.0:2181.<br/>
<b>Scenario 2:</b> ClientCnxn - Opening socket connection to server 10.1.2.3/10.1.2.3:2888.</p></blockquote>

<p>Obviously these are both undesirable connection strings, as both are wrong. The issue arises in the EnsembleTracker.processConfigData() when we reconnect to Zookeeper. The config coming from zookeeper is in <a href="https://zookeeper.apache.org/doc/trunk/zookeeperReconfig.html#sc_reconfig_clientport" class="external-link" target="_blank" rel="nofollow noopener">the format</a>:</p>

<blockquote>
<p>server.<positive id> = <address1>:<port1>:<port2>[:role];[<client port address>:]<client port></p></blockquote>

<p>As we can see, both [:role] and [<client port address>:] are optional. Hence, the following string is perfectly valid:</p>

<blockquote>
<p>server.1=10.1.2.3:2888:3888:participant;2181</p></blockquote>

<p>When Zookeeper sends this, it defaults the clientAddress to 0.0.0.0, so we retrieve the following value in EnsembleTracker:</p>

<blockquote>
<p>server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181</p></blockquote>

<p>The resulting connection string, therefore, turns in to 0.0.0.0:2181 instead of 10.1.2.3:2181, and Curator creates a new ZooKeeper to connect to that IP - which obviously never works.</p>

<p>In the second scenario, our connection string looks a bit different. It is wrong according to the docs, but is valid:</p>

<blockquote>
<p>server.1=10.1.2.3:2888:3888:participant</p></blockquote>

<p>Now, this is missing the client port and address. That means that the resulting string from the EnsembleTracker is 10.1.2.3:2888 - which isn't desired. Including the port would just lead to the above scenario.</p>

<p>From what I can see, the EnsembleTracker.configToConnectionString() method is the issue here:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">InetSocketAddress address = Objects.firstNonNull(server.clientAddr, server.addr);
    sb.append(address.getAddress().getHostAddress()).append(<span class="code-quote">":"</span>).append(address.getPort());
</pre>
</div></div>

<p>In the above cases, both the server.Addr and server.clientAddr values are wrong. We also prefer the value of clientAddr for some reason, which doesn't look right to me (given that it can be 0.0.0.0 or 127.0.0.1).</p>

<p>It seems to me that Curator should use server.Addr.getHostAddress() with server.clientAddr.getPort(). When the clientAddr is missing, however, I'm not sure what should be done.</p>

---
<details><summary><i>Originally reported by <a title="Alex Rankin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Kenco">Kenco</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-392" target="_blank">Zookeeper Ensemble Get Incorrect Address</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-07-18T14:21:12+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Kenco" class="user-hover" rel="Kenco">Alex Rankin</a> - we don't accept patch files. Please open a Pull Request on Github. See here: <a href="https://cwiki.apache.org/confluence/display/CURATOR/Submitting+Pull+Requests" class="external-link" target="_blank" rel="nofollow noopener">https://cwiki.apache.org/confluence/display/CURATOR/Submitting+Pull+Requests</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<blockquote><p>Master seems to be significantly different</p></blockquote>

<p>We have two active branches. "master" corresponds to Curator 2.x and "<a href="https://issues.apache.org/jira/browse/CURATOR-3" title="LeaderLatch race condition causing extra nodes to be added in Zookeeper Edit" class="issue-link" data-issue-key="CURATOR-3"><del>CURATOR-3</del></a>.0" corresponds to Curator 3.x. In general, all patches should be against master. We then merge master into <a href="https://issues.apache.org/jira/browse/CURATOR-3" title="LeaderLatch race condition causing extra nodes to be added in Zookeeper Edit" class="issue-link" data-issue-key="CURATOR-3"><del>CURATOR-3</del></a>.0. For a change such as this, work off of <a href="https://issues.apache.org/jira/browse/CURATOR-3" title="LeaderLatch race condition causing extra nodes to be added in Zookeeper Edit" class="issue-link" data-issue-key="CURATOR-3"><del>CURATOR-3</del></a>.0 only.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Vile2539 opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-392" title="Zookeeper Ensemble Get Incorrect Address" class="issue-link" data-issue-key="CURATOR-392"><del>CURATOR-392</del></a> Fixing connection string construction for wildcard client addresses</p>

<p>    The client address in Zookeeper can be a wildcard (0.0.0.0), and if this is used by Curator, it will attempt to create a new connection to 0.0.0.0 instead of the correct server address. It is also possible that no client address or port is set, which should be counted as invalid by Curator, since the appropriate information isn't contained in the data sent.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/Vile2539/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/Vile2539/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-392" title="Zookeeper Ensemble Get Incorrect Address" class="issue-link" data-issue-key="CURATOR-392"><del>CURATOR-392</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/205.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #205</p>

<hr />
<p>commit 9b73d11bc03c6e37567e237e96c36cdf93e4ff66<br/>
Author: Kenco <davelister@gmail.com><br/>
Date:   2017-03-13T20:51:42Z</p>

<p>    Fixing connection string construction to ignore wildcard client addresses</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Vile2539 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/205" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205</a></p>

<p>    It's been about 4 months, so I'm a bit fuzzy on the exact details.</p>

<p>    > The spec of server address is server. = ::<span class="error">&#91;:role&#93;</span>;<span class="error">&#91;:&#93;</span>, and if server.clientAddr is null then it means the client port address is not present. The client port address is optional, so the address is still a valid address.</p>

<p>    The problem is that EnsembleTracker is getting the connection string for itself to Zookeeper. If it receives a config without a valid client port, then it can't create a new connection string to that client. Since Zookeeper isn't sending the clientPort configured outside of that string (in this case), we can't use any of the connection string.</p>

<p>    > I think you can just use server.addr which is guaranteed not null, and then use getHostAddress to get the hostAddress.</p>

<p>    I'm not entirely sure about that. We want to use the server.clientAddr ideally - unless it's a wildcard, in which case we use the server.addr. It's not about one of them being null, but the clientAddr should be favoured over the server.addr (for example - we might have clientAddr set to localhost to accept only local connections).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127054869" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127054869</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java &#8212;<br/>
    @@ -166,12 +166,26 @@ public static String configToConnectionString(QuorumVerifier data) throws Except<br/>
     StringBuilder sb = new StringBuilder();<br/>
     for ( QuorumPeer.QuorumServer server : data.getAllMembers().values() )<br/>
     {<br/>
    +    if ( server.clientAddr == null )<br/>
    +    </p>
{
    +// Invalid client address configuration in zoo.cfg
    +continue;
    +    }
<p> if ( sb.length() != 0 )</p>
 {
     sb.append(",");
 }
<ul class="alternate" type="square">
	<li>InetSocketAddress address = Objects.firstNonNull(server.clientAddr, server.addr);</li>
	<li>sb.append(address.getAddress().getHostAddress()).append(":").append(address.getPort());<br/>
    +    InetAddress wildcardAddress = new InetSocketAddress(0).getAddress();<br/>
    +    String hostAddress;<br/>
    +    if ( wildcardAddress.equals(server.clientAddr.getAddress()) )<br/>
    +    
{
    +hostAddress = server.addr.getAddress().getHostAddress();
    +    }
<p>    +    else<br/>
    +    </p>
{
    +hostAddress = server.clientAddr.getAddress().getHostAddress();
    +    }
<p>    +    sb.append(hostAddress).append(":").append(server.clientAddr.getPort());</p>
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    Isn't calling `getHostAddress()` really expensive? Is this necessary?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127055979" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127055979</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java &#8212;<br/>
    @@ -166,12 +166,26 @@ public static String configToConnectionString(QuorumVerifier data) throws Except<br/>
     StringBuilder sb = new StringBuilder();<br/>
     for ( QuorumPeer.QuorumServer server : data.getAllMembers().values() )<br/>
     {<br/>
    +    if ( server.clientAddr == null )<br/>
    +    </p>
{
    +// Invalid client address configuration in zoo.cfg
    +continue;
    +    }
<p> if ( sb.length() != 0 )</p>
 {
     sb.append(",");
 }
<ul class="alternate" type="square">
	<li>InetSocketAddress address = Objects.firstNonNull(server.clientAddr, server.addr);</li>
	<li>sb.append(address.getAddress().getHostAddress()).append(":").append(address.getPort());<br/>
    +    InetAddress wildcardAddress = new InetSocketAddress(0).getAddress();
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    So, @hanm you're saying the original code is correct?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127061717" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127061717</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java &#8212;<br/>
    @@ -166,12 +166,26 @@ public static String configToConnectionString(QuorumVerifier data) throws Except<br/>
     StringBuilder sb = new StringBuilder();<br/>
     for ( QuorumPeer.QuorumServer server : data.getAllMembers().values() )<br/>
     {<br/>
    +    if ( server.clientAddr == null )<br/>
    +    </p>
{
    +// Invalid client address configuration in zoo.cfg
    +continue;
    +    }
<p> if ( sb.length() != 0 )</p>
 {
     sb.append(",");
 }
<ul class="alternate" type="square">
	<li>InetSocketAddress address = Objects.firstNonNull(server.clientAddr, server.addr);</li>
	<li>sb.append(address.getAddress().getHostAddress()).append(":").append(address.getPort());<br/>
    +    InetAddress wildcardAddress = new InetSocketAddress(0).getAddress();<br/>
    +    String hostAddress;<br/>
    +    if ( wildcardAddress.equals(server.clientAddr.getAddress()) )<br/>
    +    
{
    +hostAddress = server.addr.getAddress().getHostAddress();
    +    }
<p>    +    else<br/>
    +    </p>
{
    +hostAddress = server.clientAddr.getAddress().getHostAddress();
    +    }
<p>    +    sb.append(hostAddress).append(":").append(server.clientAddr.getPort());</p>
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    @Vile2539 you're right</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hanm commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127122870" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127122870</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java &#8212;<br/>
    @@ -166,12 +166,26 @@ public static String configToConnectionString(QuorumVerifier data) throws Except<br/>
     StringBuilder sb = new StringBuilder();<br/>
     for ( QuorumPeer.QuorumServer server : data.getAllMembers().values() )<br/>
     {<br/>
    +    if ( server.clientAddr == null )<br/>
    +    </p>
{
    +// Invalid client address configuration in zoo.cfg
    +continue;
    +    }
<p> if ( sb.length() != 0 )</p>
 {
     sb.append(",");
 }
<ul class="alternate" type="square">
	<li>InetSocketAddress address = Objects.firstNonNull(server.clientAddr, server.addr);</li>
	<li>sb.append(address.getAddress().getHostAddress()).append(":").append(address.getPort());<br/>
    +    InetAddress wildcardAddress = new InetSocketAddress(0).getAddress();
	<ul class="alternate" type="square">
		<li>
		<ul class="alternate" type="square">
			<li>End diff &#8211;</li>
		</ul>
		</li>
	</ul>
	</li>
</ul>


<p>    I checked spec again, and I agree with what @Vile2539 commented - we should try clientAddr first and then fall back if necessary. So the code change in this pull request here looks good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user hanm commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127124498" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127124498</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java &#8212;<br/>
    @@ -166,12 +166,26 @@ public static String configToConnectionString(QuorumVerifier data) throws Except<br/>
     StringBuilder sb = new StringBuilder();<br/>
     for ( QuorumPeer.QuorumServer server : data.getAllMembers().values() )<br/>
     {<br/>
    +    if ( server.clientAddr == null )<br/>
    +    {<br/>
    +// Invalid client address configuration in zoo.cfg<br/>
    +continue;<br/>
    &#8212; End diff &#8211;</p>

<p>    I see what you mean - if the client_port_address is not present ZK will not initialize server.clientAddress, which is where you extract the client port. This is not a problem for ZK itself because it has the knowledge of clientPort of a quorum peer which is not publicly accessible.</p>

<p>    I think QuorumSever can provide APIs so you guys can use the APIs to get the client / server address / port rather than relying on the clientAddr etc fields. Before that happens it's fine to skip as there is no way to extract the client port (and I think that only happens when clientAddress is not explicitly present in the config string - cases like server.1= 125.23.63.23:1234:1235;1236)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user lvfangmin commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127384585" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127384585</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java &#8212;<br/>
    @@ -313,6 +313,38 @@ public void testNewMembers() throws Exception<br/>
     }<br/>
 }</p>

<p>    +    @Test<br/>
    +    public void testConfigToConnectionStringNormal() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;10.2.3.4:2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.2.3.4:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringNoClientAddr() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.1.2.3:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringWildcardClientAddr() throws Exception<br/>
    +    {<br/>
    +String config = "server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181";<br/>
    &#8212; End diff &#8211;</p>

<p>    Please also add a test case for IPv6 wildcard:</p>

<p>    server.1=<span class="error">&#91;1010:0001:0002:0003:0004:0005:0006:0007&#93;</span>:2888:3888:participant;<span class="error">&#91;::0&#93;</span>:2181</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Vile2539 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127615377" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127615377</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java &#8212;<br/>
    @@ -313,6 +313,38 @@ public void testNewMembers() throws Exception<br/>
     }<br/>
 }</p>

<p>    +    @Test<br/>
    +    public void testConfigToConnectionStringNormal() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;10.2.3.4:2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.2.3.4:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringNoClientAddr() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.1.2.3:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringWildcardClientAddr() throws Exception<br/>
    +    {<br/>
    +String config = "server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181";<br/>
    &#8212; End diff &#8211;</p>

<p>    It doesn't look like Zookeeper supports IPv6 addresses in 3.5.1-alpha (which is what Curator seems to be using). This appears to be fixed in Zookeeper 3.5.2 and 3.6.0:</p>

<p>    <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-1460" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-1460</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127615418" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127615418</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java &#8212;<br/>
    @@ -313,6 +313,38 @@ public void testNewMembers() throws Exception<br/>
     }<br/>
 }</p>

<p>    +    @Test<br/>
    +    public void testConfigToConnectionStringNormal() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;10.2.3.4:2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.2.3.4:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringNoClientAddr() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.1.2.3:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringWildcardClientAddr() throws Exception<br/>
    +    {<br/>
    +String config = "server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181";<br/>
    &#8212; End diff &#8211;</p>

<p>    Curator will be at 3.5.3-beta for the next release. That has change since this PR has started. feel free to increment the ZK version in the main pom.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Vile2539 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127615903" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127615903</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java &#8212;<br/>
    @@ -313,6 +313,38 @@ public void testNewMembers() throws Exception<br/>
     }<br/>
 }</p>

<p>    +    @Test<br/>
    +    public void testConfigToConnectionStringNormal() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;10.2.3.4:2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.2.3.4:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringNoClientAddr() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.1.2.3:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringWildcardClientAddr() throws Exception<br/>
    +    {<br/>
    +String config = "server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181";<br/>
    &#8212; End diff &#8211;</p>

<p>    I seem to be getting a NPE with 3.5.3-beta when attempting to construct the TestingZooKeeperServer:</p>

<p>java.lang.NullPointerException<br/>
    	    at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:158)<br/>
    	    at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:150)<br/>
    	    at java.lang.Thread.run(Thread.java:745)</p>

<p>    It looks like is a known issue, but I don't understand the fix version of 3.4.0 when it occurred on 3.5.3-beta only - I assume that should be 3.5.4-beta:</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-409" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-409</a></p>

<p>    I'm not really sure how I should proceed here. Updating the pom would break a lot of the tests, and I can't add IPv6 tests without the updated Zookeeper version supporting IPv6.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Vile2539 commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/205#discussion_r127640820" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205#discussion_r127640820</a></p>

<p>    &#8212; Diff: curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java &#8212;<br/>
    @@ -313,6 +313,38 @@ public void testNewMembers() throws Exception<br/>
     }<br/>
 }</p>

<p>    +    @Test<br/>
    +    public void testConfigToConnectionStringNormal() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;10.2.3.4:2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.2.3.4:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringNoClientAddr() throws Exception<br/>
    +    </p>
{
    +String config = "server.1=10.1.2.3:2888:3888:participant;2181";
    +String configString = EnsembleTracker.configToConnectionString(toQuorumVerifier(config.getBytes()));
    +Assert.assertEquals("10.1.2.3:2181", configString);
    +    }
<p>    +<br/>
    +    @Test<br/>
    +    public void testConfigToConnectionStringWildcardClientAddr() throws Exception<br/>
    +    {<br/>
    +String config = "server.1=10.1.2.3:2888:3888:participant;0.0.0.0:2181";<br/>
    &#8212; End diff &#8211;</p>

<p>    @Randgalt Ahh right. I've changed the base branch now and I'll have a look into the tests after work.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/205" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205</a></p>

<p>    thanks @Vile2539 - I'll run the tests and, assuming they pass, I'll merge. Anyone have any last objections to merging? @hanm or @lvfangmin ?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/205" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/205</a></p>
