### ISSUE TITLE
[CURATOR-409] TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#929]
<p>Zookeeper 3.5.3 has added a getQuorumPeer method to QuorumPeerMain <a href="https://github.com/apache/zookeeper/blob/release-3.5.3/src/java/main/org/apache/zookeeper/server/quorum/QuorumPeerMain.java#L194" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/zookeeper/blob/release-3.5.3/src/java/main/org/apache/zookeeper/server/quorum/QuorumPeerMain.java#L194</a>. TestingQuorumPeerMain has an identically named method, which is now unintentionally overridding the one in the base class.</p>

<p>This causes TestingCluster to be unusable.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">20:36:41.199 [<span class="code-object">Thread</span>-1] ERROR org.apache.curator.test.TestingZooKeeperServer - From testing server (random state: <span class="code-keyword">false</span>) <span class="code-keyword">for</span> instance: InstanceSpec{dataDirectory=C:\Users\Esran\AppData\Local\Temp\1494009401090-0, port=65306, electionPort=65307, quorumPort=65308, deleteDataDirectoryOnClose=<span class="code-keyword">true</span>, serverId=1, tickTime=-1, maxClientCnxns=-1, customProperties={}, hostname=127.0.0.1} org.apache.curator.test.InstanceSpec@59c4b497
java.lang.NullPointerException: <span class="code-keyword">null</span>
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:158) ~[zookeeper-3.5.3-beta.jar:3.5.3-beta-8ce24f9e675cbefffb8f21a47e06b42864475a60]
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:150) [curator-test-3.3.0.jar:3.3.0]
	at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [?:1.8.0_73]
</pre>
</div></div>

<p>The method in TestingQuorumPeerMain should be renamed.</p>

---
<details><summary><i>Originally reported by <a title="Stig Rohde Døssing" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-409" target="_blank">TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-05-08T05:13:40+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user srdo opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/219" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/219</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a>: Fix unintentional override of getQuorumPeer in TestingQu…</p>

<p>    …orumPeerMain</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-409" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-409</a></p>

<p>    I don't know if QuorumPeer is useful to users of curator-test, but getQuorumPeer isn't used anywhere in the code, so if it is possible to remove it entirely that's probably a nicer solution. </p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/srdo/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/srdo/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/219.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/219.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #219</p>

<hr />
<p>commit 956176629f5cc9d7c53b52068e4ebdcbdfb86e68<br/>
Author: Stig Rohde Døssing <stigdoessing@gmail.com><br/>
Date:   2017-05-05T18:44:10Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a>: Fix unintentional override of getQuorumPeer in TestingQuorumPeerMain</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/219" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/219</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<p>Is there any chance to backport this to 2.x and 3.x?</p>

<p>Apache Hadoop is using Curator 2.12.0 and upgraded ZooKeeper from 3.4.8 to 3.14.13. And then, hit this issue (tracked by <a href="https://issues.apache.org/jira/browse/HADOOP-15974" title="Upgrade Curator version to 2.13.0 to fix ZK tests" class="issue-link" data-issue-key="HADOOP-15974"><del>YARN-8937</del></a>).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>I think backporting this to 2.x makes sense. People should be able to upgrade to 4.x for the production Curator code, but if they're on Zookeeper 3.4.x, they'll need to use the 2.x version of curator-test (<a href="https://curator.apache.org/zk-compatibility.html" class="external-link" target="_blank" rel="nofollow noopener">https://curator.apache.org/zk-compatibility.html</a>). So people that are using Curator 3.x should just be able to upgrade to 4.x, but Zookeeper 3.4.x users will probably have this issue unless it's patched in curator-test 2.x.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> for the comment. What can I do for backporting this to 2.x?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><span class="error">&#91;~ajisakaa&#93;</span> I don't see a branch for 2.x development in Github, so not sure where the fix needs to go. Maybe try pinging <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> to see if he would be open to having this backported and releasing a 2.13?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a>, are you open to backport this to 2.x and release Curator 2.13?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>>  Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a>, are you open to backport this to 2.x and release Curator 2.13?</p>

<p>I'm not. Curator 2.x is EOL. Maybe you can do the work?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<blockquote><p>Curator 2.x is EOL. Maybe you can do the work?</p></blockquote>
<p>I'm newbie to Curator project and I don't have time to become a committer and create a new release of Curator 2.x.</p>

<p>I'd like to remove the usage of TestingQuorumPeerMain, or upgrade ZooKeeper to 3.5.x, in Hadoop project.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Just to clarify, if we (me or Akira) backport this to 2.x would you be willing to release 2.13, or are you saying that a 2.13 release is off the table? Because I wouldn't mind taking a stab at backporting it, but it's wasted work if you don't want to do a release.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Yes, if the work is done I (or maybe <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a>) can do the release.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>You'd have to start off the tag I think</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p><span class="error">&#91;~risdenk&#93;</span> Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<p>Thanks <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> and <span class="error">&#91;~risdenk&#93;</span> for your help! I tried the repository and ran the test successfully:</p>
<ol>
	<li>Checkout <a href="https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x</a> and compile</li>
	<li>Upgrade curator version to 2.13.0-SNAPSHOT in Apache Hadoop</li>
	<li>Run the hanging test reported at <a href="https://issues.apache.org/jira/browse/HADOOP-15974" title="Upgrade Curator version to 2.13.0 to fix ZK tests" class="issue-link" data-issue-key="HADOOP-15974"><del>YARN-8937</del></a></li>
</ol>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajisakaa">ajisakaa</a>:</i>
<p>> Yes, if the work is done I (or maybe <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a>) can do the release</p>

<p>Thank you, <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> and <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a>! Now I'm +1(non-binding) for the backport. <a href="https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Curator 2.x is meant to work with ZooKeeper 3.4.x. Does this change break that?</p>

<p>Wait - I see "tested against Knox with Zookeeper 3.4.13". So, I guess it's OK. I'm a bit confused though that this bug is written as "TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta".</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>Maybe the issue should be renamed. When it was originally fixed it only applied to Zookeeper 3.5.3, but the change (I believe <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2355" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/ZOOKEEPER-2355</a>) that broke curator-test has since been backported to Zookeeper 3.4.11. </p>

<p>People on Zookeeper 3.4.x and Curator 4.x are still using curator-test 2.12, which is why the fix for curator-test also needs to go in that release line. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p><a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2834" title="ZOOKEEPER-2355 fix for branch-3.4" class="issue-link" data-issue-key="ZOOKEEPER-2834"><del>ZOOKEEPER-2834</del></a> backported <a href="https://issues.apache.org/jira/browse/ZOOKEEPER-2355" title="Ephemeral node is never deleted if follower fails while reading the proposal packet" class="issue-link" data-issue-key="ZOOKEEPER-2355"><del>ZOOKEEPER-2355</del></a> to the 3.4.x line and was released in Zookeeper 3.4.11.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> / <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> / <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> - I know it was just a long holiday weekend in the US. Anything I can do to help move forward a 2.x release?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><span class="error">&#91;~risdenk&#93;</span>, sorry having some technical issues, hopefully get a release started in the next couple of days.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p>No worries <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/> Just checking to see if there was anything I could do to help keep the ball rolling. Not in a rush.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><span class="error">&#91;~risdenk&#93;</span>, actually there is something that you could try for me. My environment is hanging while trying to run the Curator unit tests. Would you be able to run them on your backported Curator branch and see if you get the same issue? Just a 'mvn test' target should do the job.</p>

<p>cheers</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p>I just setup my local Jenkins server to run a "mvn verify" against <a href="https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x." class="external-link" target="_blank" rel="nofollow noopener">https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x</a> It will run in a separate docker container to make sure there are no external dependencies. I can share the results when they finish.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie" class="user-hover" rel="cammckenzie">Cam McKenzie</a> - I checked the results this morning:</p>

<p>For Apache Curator master branch</p>
<ul>
	<li>2/2 runs failed</li>
	<li>failed due to timeout after an hour
	<ul>
		<li>Hung on test org.apache.curator.TestSessionFailRetryLoop</li>
	</ul>
	</li>
</ul>


<p>For the test-<a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a>-2.x branch</p>
<ul>
	<li>10/12 passed successfully</li>
	<li>the 2 that failed were due to timeout
	<ul>
		<li>First hung on org.apache.curator.framework.recipes.locks.TestInterProcessSemaphoreMutex</li>
		<li>Second hung on org.apache.curator.framework.recipes.locks.TestInterProcessMutex</li>
	</ul>
	</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Thanks <span class="error">&#91;~risdenk&#93;</span>,</p>

<p>I have the 2.x tests working now, will have to look into the 4.x branch, something is broken there.</p>

<p>Just to confirm, the branch that I should be using is:</p>

<p>test-<a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a>-2.x</p>

<p>from </p>

<p><a href="https://github.com/risdenk/curator/tree/test-CURATOR-409-2.x" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/risdenk/curator</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=risdenk">risdenk</a>:</i>
<p>The branch test-<a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a>-2.x has 2 commits. Commit <a href="https://github.com/risdenk/curator/commit/8974d526f6fdd5404323d73e32d3465fbad57d32" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/risdenk/curator/commit/8974d526f6fdd5404323d73e32d3465fbad57d32</a> is the one that <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Srdo" class="user-hover" rel="srdo">Stig Rohde Døssing</a> developed. The branch has one more commit to introduce the version change.</p>

<p>Really all you need is the one commit depending on how the release steps say to adjust the version number.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20HADOOP-15974">HADOOP-15974</a>]</i>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20ZOOKEEPER-3181">ZOOKEEPER-3181</a>]</i>
