### ISSUE TITLE
[CURATOR-411] Make Tests Great Again

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#931]
<p>The current master branch fails many tests and hangs on some. Let's get this fixed. </p>

---
<details><summary><i>Originally reported by <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-411" target="_blank">Make Tests Great Again</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-05-30T12:54:38+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Possibly related to <a href="https://issues.apache.org/jira/browse/CURATOR-410" title="testPathsFromProtectingInBackground fails since upgrade to Zookeeper 3.5.3" class="issue-link" data-issue-key="CURATOR-410"><del>CURATOR-410</del></a> and  <a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-411" title="Make Tests Great Again" class="issue-link" data-issue-key="CURATOR-411"><del>CURATOR-411</del></a> Fix various testing issues</p>

<ul class="alternate" type="square">
	<li>disable testMissedDelete - it needs to be re-written</li>
	<li>overload setState() in TestZooKeeperServer to avoid bogus log message</li>
	<li>Turn off JMX logging in ZooKeeper</li>
	<li>TestReconfiguration was messed up by ZK 3.5.3 reconfig changes</li>
	<li>Added a method to Timing to take from a queue with timeouts and applied it to tests that needed it</li>
	<li><a href="https://issues.apache.org/jira/browse/CURATOR-410" title="testPathsFromProtectingInBackground fails since upgrade to Zookeeper 3.5.3" class="issue-link" data-issue-key="CURATOR-410"><del>CURATOR-410</del></a> and <a href="https://issues.apache.org/jira/browse/CURATOR-409" title="TestingQuorumPeerMain does not work with Zookeeper 3.5.3-beta" class="issue-link" data-issue-key="CURATOR-409"><del>CURATOR-409</del></a></li>
</ul>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-411" title="Make Tests Great Again" class="issue-link" data-issue-key="CURATOR-411"><del>CURATOR-411</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/221.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #221</p>

<hr />
<p>commit 872bfb0285dc4807d873b9ee2707b0f6044747f6<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T04:01:45Z</p>

<p>    Added a method to Timing to take from a queue with timeouts and applied it to tests that needed it</p>

<p>commit 5407746c37c6ee08bbefe6632e25f5790226180c<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T04:15:40Z</p>

<p>    Merge branch 'master' into <a href="https://issues.apache.org/jira/browse/CURATOR-411" title="Make Tests Great Again" class="issue-link" data-issue-key="CURATOR-411"><del>CURATOR-411</del></a></p>

<p>commit 0d1aa7ed1f3fef2b9cdb1e3a7f15d6e6ae85dac0<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T17:37:06Z</p>

<p>    Have to call setReconfigEnabled(true) and set the super-user Auth to get reconfig to work</p>

<p>commit 3fa5143d6692bb18dba0d21a28328de032482d6f<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T17:43:16Z</p>

<p>    connection string cannot be empty</p>

<p>commit 4813b7924ecb6f0a2c4836e3e167e220a35f5314<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T21:29:49Z</p>

<p>    Turn off JMX logging</p>

<p>commit 70588f92e3dc7162f1e0df12ad0c09c92ab86b32<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-08T21:51:25Z</p>

<p>    extend BaseClassForTests so that retries occur</p>

<p>commit 27ddd8c90042ca7abc667edb63504d081a1ca1b4<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-09T08:50:35Z</p>

<p>    overload setState() to avoid bogus log message</p>

<p>commit 88d56219e3be026e453a5ef254bee3771d5b018b<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-05-09T10:40:50Z</p>

<p>    disable testMissedDelete() for now</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    I'm still seeing the following fail. The TestFailedDeleteManager case is intermittent, the reconfig one seems to be failing consistently.</p>

<p>    Failed tests: <br/>
    org.apache.curator.framework.imps.TestFailedDeleteManager.testWithNamespaceAndLostSessionAlt(org.apache.curator.framework.imps.TestFailedDeleteManager)<br/>
      Run 1: PASS<br/>
      Run 2: TestFailedDeleteManager.testWithNamespaceAndLostSessionAlt:203 » SessionExpired<br/>
      Run 3: PASS</p>

<p>    org.apache.curator.framework.imps.TestReconfiguration.testNewMembers(org.apache.curator.framework.imps.TestReconfiguration)<br/>
      Run 1: PASS<br/>
      Run 2: TestReconfiguration.testNewMembers:313 » ConnectionLoss KeeperErrorCode = Conn...<br/>
      Run 3: PASS<br/>
      Run 4: TestReconfiguration.testNewMembers:313 » CuratorConnectionLoss KeeperErrorCode...</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user zarfide commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    TestFailedDeleteManager.testWithNamespaceAndLostSessionAlt:203 » SessionExpired has been flaky for me for quite some time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    @cammckenzie @zarfide please re-rest. I made the following changes:</p>

<ul class="alternate" type="square">
	<li>testNewMembers() only tries to go from 5 to 4. I'm guessing the flakiness is going from 5 to 3</li>
	<li>testWithNamespaceAndLostSessionAlt() now allows either ConnectionLossException or SessionExpiredException</li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    The reconfiguration case seems to be better now. I'm still seeing failures on the </p>

<p>    TestFailedDeleteManager.testLostSession</p>

<p>    It seems that at line 77, it is sometimes getting an expired session instead of a lost connection. I wonder if this has something to do with the new way of determining LOST events when disconnected?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user zarfide commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    I was able to get two full clean test runs in.  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    For `TestFailedDeleteManager.testLostSession` I added `KeeperException.SessionExpiredException` as OK for all the tests. That should help @cammckenzie's case. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    Can anyone explain Jenkins here? In our test suite, we auto retry tests. But, Jenkins shows retried tests as failures. </p>

<ul class="alternate" type="square">
	<li><a href="https://builds.apache.org/job/Curator/lastCompletedBuild/org.apache.curator$curator-framework/testReport/" class="external-link" target="_blank" rel="nofollow noopener">https://builds.apache.org/job/Curator/lastCompletedBuild/org.apache.curator$curator-framework/testReport/</a></li>
	<li><a href="https://builds.apache.org/job/Curator/lastCompletedBuild/org.apache.curator$curator-framework/testReport/org.apache.curator.framework.imps/TestReconfiguration/testNewMembers/" class="external-link" target="_blank" rel="nofollow noopener">https://builds.apache.org/job/Curator/lastCompletedBuild/org.apache.curator$curator-framework/testReport/org.apache.curator.framework.imps/TestReconfiguration/testNewMembers/</a></li>
</ul>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    TestFailedDeleteManager seems to be ok now, but I'm still seeing fairly regular failure on TestReconfiguration.testNewMembers(). It's getting a ConnectionLossException at Line 313.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    I had a bit more of a look at the failing test and see the following being logged when the client.reconfig() call occurs. I'm not sure if these are issues or not, but they certainly seem to be. </p>

<p>    Also, I noticed that the reconfig() call to Zookeeper that Curator is using is deprecated.</p>

<p>    ERROR org.apache.zookeeper.server.NIOServerCnxnFactory  Error reconfiguring client port to /0.0.0.0:39762 Address already in use <span class="error">&#91;LearnerHandler-/127.0.0.1:52184&#93;</span><br/>
    ERROR org.apache.zookeeper.server.quorum.QuorumCnxManager  Exception while listening <span class="error">&#91;/0.0.0.0:34491&#93;</span><br/>
    java.net.BindException: Address already in use (Bind failed)<br/>
    	at java.net.PlainSocketImpl.socketBind(Native Method)<br/>
    	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)<br/>
    	at java.net.ServerSocket.bind(ServerSocket.java:376)<br/>
    	at java.net.ServerSocket.bind(ServerSocket.java:330)<br/>
    	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:638)<br/>
    ERROR org.apache.zookeeper.server.NIOServerCnxnFactory  Error reconfiguring client port to /0.0.0.0:35059 Address already in use [QuorumPeer<span class="error">&#91;myid=2&#93;</span>(plain=/127.0.0.1:35059)(secure=disabled)]<br/>
    ERROR org.apache.zookeeper.server.NIOServerCnxnFactory  Error reconfiguring client port to /0.0.0.0:33568 Address already in use [QuorumPeer<span class="error">&#91;myid=1&#93;</span>(plain=/127.0.0.1:33568)(secure=disabled)]<br/>
    ERROR org.apache.zookeeper.server.quorum.LearnerHandler  Unexpected exception causing shutdown while sock still open <span class="error">&#91;LearnerHandler-/127.0.0.1:52184&#93;</span><br/>
    java.io.EOFException<br/>
    	at java.io.DataInputStream.readInt(DataInputStream.java:392)<br/>
    	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)<br/>
    	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:83)<br/>
    	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)<br/>
    	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:515)<br/>
    ERROR org.apache.zookeeper.server.quorum.LearnerHandler  Unexpected exception causing shutdown while sock still open <span class="error">&#91;LearnerHandler-/127.0.0.1:52186&#93;</span><br/>
    java.io.EOFException<br/>
    	at java.io.DataInputStream.readInt(DataInputStream.java:392)<br/>
    	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)<br/>
    	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:83)<br/>
    	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)<br/>
    	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:515)<br/>
    ERROR org.apache.zookeeper.server.quorum.LearnerHandler  Unexpected exception causing shutdown while sock still open <span class="error">&#91;LearnerHandler-/127.0.0.1:41758&#93;</span><br/>
    java.io.IOException: Follower is ahead of the leader, leader summary: 1 (current epoch), 4294967297 (last zxid)<br/>
    	at org.apache.zookeeper.server.quorum.Leader.waitForEpochAck(Leader.java:1209)<br/>
    	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:421)<br/>
    INFO  org.apache.curator.ConnectionState  Connection string changed to: 127.0.0.1:33568,127.0.0.1:35059,127.0.0.1:39762 <span class="error">&#91;main-EventThread&#93;</span><br/>
    DEBUG org.apache.curator.ConnectionState  reset <span class="error">&#91;main-EventThread&#93;</span><br/>
    ERROR org.apache.zookeeper.server.quorum.LearnerHandler  Unexpected exception causing shutdown while sock still open <span class="error">&#91;LearnerHandler-/127.0.0.1:41768&#93;</span><br/>
    java.io.IOException: Follower is ahead of the leader, leader summary: 1 (current epoch), 4294967297 (last zxid)<br/>
    	at org.apache.zookeeper.server.quorum.Leader.waitForEpochAck(Leader.java:1209)<br/>
    	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:421)</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    Thanks for the trace @cammckenzie - I'll check it when I get a chance.</p>

<p>    Yes, the `reconfig()` API is deprecated. The ZK team is moving that stuff into a new class for 3.6.0. We'll need to deal with that at some point.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    @cammckenzie I did a bit of cleanup on testNewMembers(). Please re-test and see if it helps.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    Well, I spoke too soon @cammckenzie - Jenkins is having the same issues. <a href="https://builds.apache.org/job/Curator/org.apache.curator$curator-framework/1040/testReport/junit/org.apache.curator.framework.imps/TestReconfiguration/testNewMembers_2/" class="external-link" target="_blank" rel="nofollow noopener">https://builds.apache.org/job/Curator/org.apache.curator$curator-framework/1040/testReport/junit/org.apache.curator.framework.imps/TestReconfiguration/testNewMembers_2/</a> - I don't know what's up. I can't repro locally.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> I'll see what I can track down locally. I don't have a great understanding of the reconfig stuff works, but I'll see what I can do.<br/>
cheers</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Can someone explain the testNewMembers() test to me, maybe I'm missing something:</p>

<p>From my reading, a cluster with 5 instances is created, but only 3 of them are started.</p>

<p>The Curator client is created knowing only about the 3 instances that are started. When it connects to the cluster it queries the configuration of the cluster and finds that there are 5 instances. This much of the test works OK.</p>

<p>The next bit is what seems strange to me. It does a reconfig call to ZK withNewMembers, but passes in the existing 3 instances that the client already knows about. This seems to cause problems because ZK tries to open a server socket on the ports defined in the new connection string, but they are already present. See below:</p>

<p>ERROR org.apache.zookeeper.server.NIOServerCnxnFactory  Error reconfiguring client port to /0.0.0.0:35841 Address already in use <span class="error">&#91;LearnerHandler-/127.0.0.1:47224&#93;</span><br/>
ERROR org.apache.zookeeper.server.quorum.QuorumCnxManager  Exception while listening <span class="error">&#91;/0.0.0.0:42569&#93;</span><br/>
java.net.BindException: Address already in use (Bind failed)<br/>
	at java.net.PlainSocketImpl.socketBind(Native Method)<br/>
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)<br/>
	at java.net.ServerSocket.bind(ServerSocket.java:376)<br/>
	at java.net.ServerSocket.bind(ServerSocket.java:330)<br/>
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:638)</p>

<p>I don't understand what this part of the test is meant to be doing. If it's trying to add new members, shouldn't it be binding new ports in the connection string being passed to withNewMembers()?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>TBH - I don't know either - I didn't write it. Maybe it's an invalid test altogether.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iocanel" class="user-hover" rel="iocanel">Ioannis Canellos</a>, do you have any recollections about what this test was trying to do? I think that the reconfiguration should probably be trying to add the 2 servers that are explicitly not started at the start of the test?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>

<p>    With that disabled, all tests passed for me on the second run. On the first run, one failed due to not all watchers being removed, but I lost the output and on subsequent runs it has worked each time.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/221" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/221</a></p>
