### ISSUE TITLE
[CURATOR-415] SharedValue doesn't retry on session expiration and the approach to retries is not clear

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#935]
<p>When the session expires, seemingly on a background thread, trying to set a shared value instantly fails (in our logs there's no delay between the previous activity of the calling thread, and the exception). Judging by the code in RetryLoop that is the default behavior.<br/>
Seems like there should be some mechanism to wait and/or retry. Also, in absence of such mechanism it's not clear whether external retries should be used, or whether SharedValue object is entirely unusable after session expiration (since if it were usable across sessions, one would assume it would retry internally <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/wink.png" height="16" width="16" align="absmiddle" alt="" border="0"/>)</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2017-05-17T21:33:33,863 ERROR [b99e518c-9777-4c99-b5e7-c9a371aba3af HiveServer2-Handler-Pool: Thread-36331-EventThread]: imps.CuratorFrameworkImpl (CuratorFrameworkImpl.java:logError(546)) - Watcher exception
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for ...
...
2017-05-17T21:33:39,935 
... 
Caused by: java.lang.RuntimeException: org.apache.zookeeper.KeeperException$SessionExpiredException:KeeperErrorCode = Session expired for /zkdtsm_hive_llap0/ZKDTSMRoot/ZKDTSMSeqNumRoot
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:1270)
	at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:274)
	at org.apache.curator.framework.imps.SetDataBuilderImpl$4.call(SetDataBuilderImpl.java:270)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.pathInForeground(SetDataBuilderImpl.java:267)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:253)
	at org.apache.curator.framework.imps.SetDataBuilderImpl.forPath(SetDataBuilderImpl.java:41)
	at org.apache.curator.framework.recipes.shared.SharedValue.trySetValue(SharedValue.java:168)
	at org.apache.curator.framework.recipes.shared.SharedCount.trySetCount(SharedCount.java:111)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Sergey Shelukhin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sershe">sershe</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-415" target="_blank">SharedValue doesn't retry on session expiration and the approach to retries is not clear</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Information Provided
<li><b>resolved</b>: 2023-08-07T07:06:45+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sershe">sershe</a>:</i>
<p>cc <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=enis" class="user-hover" rel="enis">Enis Soztutar</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>Curator uses <tt>RetryPolicy</tt> to retry client operations. If you get <tt>SessionExpiredException</tt>, that means either <tt>SessionExpiredException</tt> is not allowed or the all retry permits are exhausted.</p>
