### ISSUE TITLE
[CURATOR-428] NoSuchFieldError for configFileStr in QuorumConfigBuilder

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#948]
<p>Exception in thread "Thread-0" java.lang.NoSuchFieldError: configFileStr<br/>
	at org.apache.curator.test.QuorumConfigBuilder$1.<init>(QuorumConfigBuilder.java:142)<br/>
	at org.apache.curator.test.QuorumConfigBuilder.buildConfig(QuorumConfigBuilder.java:137)<br/>
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:157)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

---
<details><summary><i>Originally reported by <a title="Jacky Chan" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=linux_china">linux_china</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-428" target="_blank">NoSuchFieldError for configFileStr in QuorumConfigBuilder</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2017-07-31T04:33:40+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>It seems like you're bringing in an older version of ZooKeeper maybe? That type of error can only be caused by a bad dependency. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=linux_china">linux_china</a>:</i>
<p>yes, My ZooKeep version is 3.4.10.  Could you make Curator 4 compatible with ZooKeeper 3.4.x?  </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Curator 4.0.0 <em>is</em> compatible with ZooKeeper 3.4 - have you seen the release notes? <a href="http://curator.apache.org/zk-compatibility.html" class="external-link" target="_blank" rel="nofollow noopener">http://curator.apache.org/zk-compatibility.html</a> - however, you're probably using version 4.0.0 of curator-testing. Please use version 2.12.0 of curator-test instead. I'll update the docs at some point to make this more clear.</p>
