### ISSUE TITLE
[CURATOR-436] NoNodeException: KeeperErrorCode KeeperException in storm-nimbus

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#956]
<p>Seeing this exception when using Storm Nimbus and Zookeeper:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>ERROR org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer - Unexpected throwable while invoking!
org.apache.storm.shade.org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /storm/leader-lock
at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:230) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:219) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:216) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:207) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:40) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.recipes.locks.LockInternals.getSortedChildren(LockInternals.java:151) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.recipes.locks.LockInternals.getParticipantNodes(LockInternals.java:133) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.shade.org.apache.curator.framework.recipes.leader.LeaderLatch.getLeader(LeaderLatch.java:453) ~[storm-core-1.1.1.jar:1.1.1]
at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.7.0.jar:?]
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313) ~[clojure-1.7.0.jar:?]
at org.apache.storm.zookeeper$zk_leader_elector$reify__1043.getLeader(zookeeper.clj:296) ~[storm-core-1.1.1.jar:1.1.1]
at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.7.0.jar:?]
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313) ~[clojure-1.7.0.jar:?]
at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10780.getLeader(nimbus.clj:2412) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.generated.Nimbus$Processor$getLeader.getResult(Nimbus.java:3944) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.generated.Nimbus$Processor$getLeader.getResult(Nimbus.java:3928) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.security.auth.SimpleTransportPlugin$SimpleWrapProcessor.process(SimpleTransportPlugin.java:162) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) ~[storm-core-1.1.1.jar:1.1.1]
at org.apache.storm.thrift.server.Invocation.run(Invocation.java:18) ~[storm-core-1.1.1.jar:1.1.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
</pre>
</div></div>

<p>There is a similar looking ticket at <a href="https://issues.apache.org/jira/browse/CURATOR-358" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-358</a> but that dealt with LeaderSelector whereas this exception seems to be caused by LeaderLatch and LockInternals.</p>

<p>Let me know if more details and/or logs are needed.</p>

---
<details><summary><i>Originally reported by <a title="Thierry Göckel" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=General Zod">General Zod</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-436" target="_blank">NoNodeException: KeeperErrorCode KeeperException in storm-nimbus</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-10-19T09:41:53+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/238" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/238</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-436" title="NoNodeException: KeeperErrorCode KeeperException in storm-nimbus" class="issue-link" data-issue-key="CURATOR-436"><del>CURATOR-436</del></a> getSortedChildren() should ignore NoNode exceptions</p>

<p>    getSortedChildren() should ignore NoNode exceptions and just treat it as if there are no children. This works around issues with container nodes, parents not yet created, etc.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-436" title="NoNodeException: KeeperErrorCode KeeperException in storm-nimbus" class="issue-link" data-issue-key="CURATOR-436"><del>CURATOR-436</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/238.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/238.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #238</p>

<hr />
<p>commit d502dde1c4601b2abc6d831d764561a73316bf00<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-10-12T10:51:39Z</p>

<p>    getSortedChildren() should ignore NoNode exceptions and just treat it as if there are no children. This works around issues with container nodes, parents not yet created, etc.</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/238" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/238</a></p>

<p>    Looks good to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=general zod">general zod</a>:</i>
<p>Will there be another 2.x release and would it be possible to cherry-pick the fix into such a version?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=general zod">general zod</a>:</i>
<p>The fix seems to be working in our environment. Thanks!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<blockquote><p>Will there be another 2.x release and would it be possible to cherry-pick the fix into such a version?</p></blockquote>

<p>None planned. Is there a corresponding issue in Storm's Jira? If the Storm committers want a new 2.x I'd consider it (or another committer can give an opinion).</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=general zod">general zod</a>:</i>
<p>Yes, there is such a ticket: <a href="https://issues.apache.org/jira/browse/STORM-2706" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/STORM-2706</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/238" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/238</a></p>
