### ISSUE TITLE
[CURATOR-440] curator-framework is unable to load in OSGi

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#960]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NoClassDefFoundError: org/apache/curator/shaded/com/google/common/cache/CacheLoader  
at org.apache.curator.framework.CuratorFrameworkFactory$Builder.<init>(CuratorFrameworkFactory.java:148) ~[171:curator-framework:4.0.0]     
at org.apache.curator.framework.CuratorFrameworkFactory$Builder.<init>(CuratorFrameworkFactory.java:130) ~[171:curator-framework:4.0.0]
at org.apache.curator.framework.CuratorFrameworkFactory.builder(CuratorFrameworkFactory.java:78) ~[171:curator-framework:4.0.0]
at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:104) ~[171:curator-framework:4.0.0] 
at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:90) ~[171:curator-framework:4.0.0]      

</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="zealot" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zealot0630">zealot0630</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-440" target="_blank">curator-framework is unable to load in OSGi</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Workaround
<li><b>resolved</b>: 2020-04-22T04:39:42+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user kghost opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/241" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/241</a></p>

<p>    Shadow guava packages inside curator-framework</p>

<p>    Fix: <a href="https://issues.apache.org/jira/browse/CURATOR-440" title="curator-framework is unable to load in OSGi" class="issue-link" data-issue-key="CURATOR-440"><del>CURATOR-440</del></a></p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/kghost/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/kghost/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-440" title="curator-framework is unable to load in OSGi" class="issue-link" data-issue-key="CURATOR-440"><del>CURATOR-440</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/241.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/241.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #241</p>

<hr />
<p>commit 27810239f76ce8fba9714e543287ba9a8026f6fe<br/>
Author: Zang MingJie <zealot0630@gmail.com><br/>
Date:   2017-11-07T07:54:32Z</p>

<p>    Shadow guava packages inside curator-framework</p>

<p>    Fix: <a href="https://issues.apache.org/jira/browse/CURATOR-440" title="curator-framework is unable to load in OSGi" class="issue-link" data-issue-key="CURATOR-440"><del>CURATOR-440</del></a></p>

<hr />
