### ISSUE TITLE
[CURATOR-446] Compile error with tests using 4.0.0 and ZK 3.4.11 - need to update docs on how to use old test lib

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#966]
<p>Attempting to start a test ZK gives the following error:</p>

<p>Exception in thread "Thread-0" java.lang.NoSuchFieldError: configFileStr<br/>
	at org.apache.curator.test.QuorumConfigBuilder$1.<init>(QuorumConfigBuilder.java:142)<br/>
	at org.apache.curator.test.QuorumConfigBuilder.buildConfig(QuorumConfigBuilder.java:137)<br/>
	at org.apache.curator.test.TestingZooKeeperServer$1.run(TestingZooKeeperServer.java:157)<br/>
	at java.lang.Thread.run(Thread.java:745)</p>

<p>Reverting back to 2.12.0 resolves the issue for me.</p>

---
<details><summary><i>Originally reported by <a title="Greg Moulliet" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=moulliet">moulliet</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-446" target="_blank">Compile error with tests using 4.0.0 and ZK 3.4.11 - need to update docs on how to use old test lib</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-20T23:51:15+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mserrano">mserrano</a>:</i>
<p>Note, while curator is compatible with ZK 3.4.x at runtime, the test ZK classes <tt>TestingZooKeeperMain</tt> and <tt>QuorumConfigBuilder</tt> (and perhaps others) use 3.5.x ZK APIs.  This means ZK 3.5.x jars need to be in the classpath for testing purposes.  This makes it very difficult to use curator 4.0.0 if the you want to work with 3.4.x.  Since ZK 3.5.x has API incompatibilities with ZK 3.4.x, it is not viable to put ZK 3.5.x in the classpath just during testing.</p>

<p>IMO, this means it is not realistic to make the soft-compatibility claim with 3.4.x and the priority of this bug should be raised or the compatibility claim removed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>We didn't claim that you could use Curator's test module with 3.4.x. But, as you point out, it would be useful. I'll see what I can do.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>If you want to use Curator's test lib with Zookeeper 3.4.x you need to use the older version (as Curator itself does in the curator-test-zk34 module):</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<dependency>
    <groupId>org.apache.curator</groupId>
    <artifactId>curator-test</artifactId>
    <version>2.12.0</version>
    <exclusions>
<exclusion>
    <groupId>org.apache.zookeeper</groupId>
    <artifactId>zookeeper</artifactId>
</exclusion>
    </exclusions>
    <scope>test</scope>
</dependency>
</pre>
</div></div>

<p>I'll update the docs when I get a chance.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mserrano">mserrano</a>:</i>
<p>Oh... duh! </p>

<p>Thanks Jordan.  Works perfectly.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/248" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/248</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-446" title="Compile error with tests using 4.0.0 and ZK 3.4.11 - need to update docs on how to use old test lib" class="issue-link" data-issue-key="CURATOR-446"><del>CURATOR-446</del></a> Update docs to document how to use the curator-test module with ZooKeeper 3.4.x</p>

<p>    Update docs to document how to use the curator-test module with ZooKeeper 3.4.x</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-446" title="Compile error with tests using 4.0.0 and ZK 3.4.11 - need to update docs on how to use old test lib" class="issue-link" data-issue-key="CURATOR-446"><del>CURATOR-446</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/248.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/248.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #248</p>

<hr />
<p>commit e37cb59c1e9b7ac7f21d3c3444b6bb789a3e3708<br/>
Author: randgalt <randgalt@apache.org><br/>
Date:   2017-12-19T02:11:27Z</p>

<p>    Update docs to document how to use the curator-test module with ZooKeeper 3.4.x</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/248" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/248</a></p>

<p>    Looks ok to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/248" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/248</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/239" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/239</a></p>

<p>    Duplicate of <a href="https://issues.apache.org/jira/browse/CURATOR-446" title="Compile error with tests using 4.0.0 and ZK 3.4.11 - need to update docs on how to use old test lib" class="issue-link" data-issue-key="CURATOR-446"><del>CURATOR-446</del></a> - <a href="https://github.com/apache/curator/pull/248" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/248</a></p>
