### ISSUE TITLE
[CURATOR-448] Include curator framework state in error messages

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#968]
<p>While looking into <a href="https://github.com/apache/fluo/pull/1004" class="external-link" target="_blank" rel="nofollow noopener">Apache Fluo #1004</a> I am seeing error messages like the following.  </p>

<p> </p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-01-22 02:57:23,383 [leader.LeaderSelector] ERROR: The leader threw an exception
java.lang.IllegalStateException: instance must be started before calling this method
at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:363)
at org.apache.fluo.core.oracle.OracleServer.takeLeadership(OracleServer.java:426)
TRUNCATED</pre>
</div></div>
<p> </p>

<p>When I see this error message I know the  <a href="https://curator.apache.org/apidocs/org/apache/curator/framework/imps/CuratorFrameworkState.html" class="external-link" target="_blank" rel="nofollow noopener">CuratorFrameworkState</a> is not STARTED.  However I don't know if its LATENT or STOPPED.  From a debugging standpoint this information would be very useful.  An example of the code that generates this error messages is at <a href="https://github.com/apache/curator/blob/3f7b610ad5c5a0c6a7b0331f02294bd433a54554/curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java#L408" class="external-link" target="_blank" rel="nofollow noopener">CuratorFrameworkImpl.java line 408</a>.  This code could be changed to call an internal method like the following :</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">private</span> void checkState() {
  CuratorFrameworkState state = getState(); <span class="code-comment">//store state in local <span class="code-keyword">var</span> to avoid race conditions since it may be read twice
</span>  Preconditions.checkState(state == CuratorFrameworkState.STARTED, <span class="code-quote">"instance state must be %s before calling <span class="code-keyword">this</span> method, however its %s"</span>, CuratorFrameworkState.STARTED, state);
}
</pre>
</div></div>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Keith Turner" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-448" target="_blank">Include curator framework state in error messages</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-06-24T15:36:36+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>:</i>
<p>The current error message was misleading.  It made me think I had not yet started the framework.  Therefore I did not consider the case that I had possibly stopped it until digging deeper.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user cjmctague opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/267" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/267</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-448" title="Include curator framework state in error messages" class="issue-link" data-issue-key="CURATOR-448"><del>CURATOR-448</del></a> - Include curator framework state in error messages</p>



<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/cjmctague/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/cjmctague/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-448" title="Include curator framework state in error messages" class="issue-link" data-issue-key="CURATOR-448"><del>CURATOR-448</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/267.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/267.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #267</p>

<hr />
<p>commit 49485b8fa40c5d5fa95e60ffea3514acf548964b<br/>
Author: Christopher McTague <cjmctague@...><br/>
Date:   2018-06-11T16:41:58Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-448" title="Include curator framework state in error messages" class="issue-link" data-issue-key="CURATOR-448"><del>CURATOR-448</del></a> - Include curator framework state in error messages</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user keith-turner commented on a diff in the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/267#discussion_r194743349" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/267#discussion_r194743349</a></p>

<p>    &#8212; Diff: curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java &#8212;<br/>
    @@ -402,75 +402,72 @@ public String getNamespace()<br/>
     return (str != null) ? str : "";<br/>
 }</p>

<p>    +    private void checkState()<br/>
    +    {<br/>
    +CuratorFrameworkState state = getState();<br/>
    +Preconditions.checkState(state == CuratorFrameworkState.STARTED, "instance state must be %s before calling this method, however its %s", CuratorFrameworkState.STARTED, state);<br/>
    &#8212; End diff &#8211;</p>

<p>    Could make it less wordy, like : `Expected state %s, however it was %s`</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/267" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/267</a></p>
