### ISSUE TITLE
[CURATOR-452] ChildData.getData() can be null

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#972]
<p>Curator client tries to make ObjectMapper to parse null (ChildData.getData() can be null).</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.NullPointerException
 at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:604)
 at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1973)
 at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:50)
 at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:193)
 at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:96)
 at org.apache.curator.x.discovery.details.ServiceProviderImpl.start(ServiceProviderImpl.java:67)</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Egor Ryashin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=egrs">egrs</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-452" target="_blank">ChildData.getData() can be null</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-06-24T15:09:19+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user poetwang commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    @Randgalt I think this is the bug mentioned in <a href="https://issues.apache.org/jira/browse/CURATOR-452" title="ChildData.getData() can be null" class="issue-link" data-issue-key="CURATOR-452"><del>CURATOR-452</del></a>, so I just link it to the issue.<br/>
    <a href="https://issues.apache.org/jira/browse/CURATOR-452" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-452</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user poetwang commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    The event (CHILD_ADDED or CHILD_UPDATED) comes because PathChildrenCache will force refresh when ConnectionState turns to CONNECTED(connectionStateListener), </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=poetwang">poetwang</a>:</i>
<p>@here could anyone please take a look at this the PR <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    Can you create a test that shows the problem and include it in this PR?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user poetwang commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    @Randgalt It is really hard to test without breaking the start method into tow parts. I tried my best to do so.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user egor-ryashin commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    This bug is constantly reproduced in our production environment.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=egrs">egrs</a>:</i>
<p>This bug constantly impedes one of our production pipelines.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user poetwang commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    Glad to hear that. Thanks</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    Sorry for the delay - I'll try to get to this soon.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>race in ServiceCacheImpl's start() method caused by an optimization whereby it clears the dataBytes of its internal PathChildrenCache</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cmckn commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/261" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/261</a></p>

<p>    I realize this issue has been closed, but I'm still seeing unexpected exceptions in some of my applications during `ServiceCacheImpl#start`.<br/>
    The merged changes to address this added a null-check around calls to `ServiceCacheImpl#addInstance` within `ServiceCacheImpl#start` (correct me if this is wrong).<br/>
    From what I've seen in my own apps, the issue is not caused by a `null` `char[]` being passed to `ServiceCacheImpl#addInstance` &#8211; it is caused by an <b>empty</b> `char[]` being passed. This empty array causes a `NullPointerException` to be thrown by my deserializer, or (if the empty case is handled there, returning `null` from the deserializer) causes a `NullPointerException` when the `null` instance is put in `instances` (a `ConcurrentMap`).<br/>
    The implementation of `ServiceCacheImpl#addInstance` below is what resolved things for me, patched into the `4.0.1` release. The `if` at the open of the function is the only change. Just wanted to throw this out there, because I've only been able to resolve the issue by using this patch &#8211; no dice on the current `master` branch. This patch doesn't appear to cause any issues, but I'm not sure if the `cache.clearDataBytes...` call should be performed regardless of whether or not the `byte[]` is empty (i.e. I'm not sure if bailing out of the function at this particular step is appropriate or will have side-effects).</p>

<p>    ```<br/>
    private void addInstance(ChildData childData, boolean onlyIfAbsent) throws Exception<br/>
{<br/>
    +    	if( childData.getData() == null || childData.getData().length == 0 )<br/>
    +    	</p>
{
    +    		return;
    +    	}
<p>    String  instanceId = instanceIdFromData(childData);<br/>
    ServiceInstance<T>      serviceInstance = discovery.getSerializer().deserialize(childData.getData());<br/>
    if ( onlyIfAbsent )</p>
    {
instances.putIfAbsent(instanceId, serviceInstance);
    }
<p>    else</p>
    {
instances.put(instanceId, serviceInstance);
    }
<p>    cache.clearDataBytes(childData.getPath(), childData.getStat().getVersion());<br/>
}<br/>
    ```<br/>
    Happy to provide more information if needed.</p>
