### ISSUE TITLE
[CURATOR-453] NPE in ServiceCacheImpl.start() because child.getData() returns null

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#973]
<p>This problem is in curator-discovery module where we get an NPE on ServiceProvider.start() because child.getData() can be null while starting ServiceCacheImpl. This is similar to <a href="https://issues.apache.org/jira/browse/CURATOR-452" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-452</a> but happens on adding null to map.</p>

<p><b>NPE Stacktrace</b></p>

<p><tt>java.lang.NullPointerException at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~<span class="error">&#91;?:1.8.0_112&#93;</span> at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535) ~<span class="error">&#91;?:1.8.0_112&#93;</span> at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:196) ~<span class="error">&#91;curator-x-discovery-4.0.0.jar:?&#93;</span> at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:96) ~<span class="error">&#91;curator-x-discovery-4.0.0.jar:?&#93;</span> at org.apache.curator.x.discovery.details.ServiceProviderImpl.start(ServiceProviderImpl.java:75) ~<span class="error">&#91;curator-x-discovery-4.0.0.jar:?&#93;</span></tt></p>

<p> </p>

<p><b>The code</b></p>

<p><tt>client = CuratorFrameworkFactory.newClient("localhost:2181", new ExponentialBackoffRetry(1000, 3));</tt></p>

<p><tt>client.start();</tt></p>

<p><tt>serviceDiscovery = ServiceDiscoveryBuilder.builder(ServiceRecord.class).client(client).basePath("/discovery/services/").serializer(serializer).build(); serviceDiscovery.start();</tt></p>

<p><tt>serviceProvider = serviceDiscovery.serviceProviderBuilder().serviceName(serviceName).build();</tt></p>

<p><tt>serviceProvider.start();</tt></p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Kislay Verma" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kislayverma">kislayverma</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-453" target="_blank">NPE in ServiceCacheImpl.start() because child.getData() returns null</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2024-08-11T16:01:16+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>The problem seems to be in your serializer. Are you using Curator's <tt>JsonInstanceSerializer</tt> or a custom serializer? Can you post the code of your serializer?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kezhuw">kezhuw</a>:</i>
<p>I peek the code and think it is probably has same cause as <a href="https://issues.apache.org/jira/browse/CURATOR-652" title="double-leader" class="issue-link" data-issue-key="CURATOR-652"><del>CURATOR-652</del></a>. Besides, this part of code has been rewritten substantially by <a href="https://issues.apache.org/jira/browse/CURATOR-549" title="ZooKeeper 3.6 will add support for Persistent Recursive Watchers - Add Curator support" class="issue-link" data-issue-key="CURATOR-549"><del>CURATOR-549</del></a>.</p>
