### ISSUE TITLE
[CURATOR-464] Unable to instantiate client in OSGi

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#984]
<blockquote>
<p>112 | Active  |  80 | 2.12.0 | Curator Client<br/>
113 | Active  |  80 | 2.12.0 | Curator Framework<br/>
114 | Active  |  80 | 2.12.0 | Curator Recipes</p></blockquote>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
CuratorFramework client = CuratorFrameworkFactory.newClient(<span class="code-quote">"localhost:2181"</span>, <span class="code-keyword">new</span> RetryOneTime(1000));
</pre>
</div></div>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>Caused by: java.lang.NoClassDefFoundError: org/apache/curator/shaded/com/google/common/cache/CacheBuilder
	at org.apache.curator.framework.imps.NamespaceWatcherMap.<init>(NamespaceWatcherMap.java:31) ~[?:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:81) ~[?:?]
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:145) ~[?:?]
	at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:100) ~[?:?]
	at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:81) ~[?:?]
</pre>
</div></div>

<p>curator-framework sources</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">import</span> com.google.common.cache.CacheBuilder;
</pre>
</div></div>
<p>but jar contains</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">import</span> org.apache.curator.shaded.com.google.common.cache.CacheBuilder;
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Alexey Markevich" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amarkevich">amarkevich</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-464" target="_blank">Unable to instantiate client in OSGi</a></i></summary>
<i><ul>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2020-04-20T12:47:46+01:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amarkevich">amarkevich</a>:</i>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>karaf@root()> headers curator-framework | grep google
com.google.common.collect,
com.google.common.base,
com.google.common.cache";
org.apache.curator.framework.api.transaction;uses:="com.google.common.base,org.apache.zookeeper.data,org.apache.curator.framework.api";version=2.12.0,
com.google.common.collect";
org.apache.curator.framework.state;uses:="org.apache.curator.framework,com.google.common.base,org.slf4j,org.apache.curator.utils,org.apache.curator.framework.listen";version=2.12.0,
org.apache.curator.framework.listen;uses:="org.slf4j,org.apache.curator.utils,com.google.common.base,com.google.common.util.concurrent,com.google.common.collect";version=2.12.0
com.google.common.base;version="[16.0,17)",
com.google.common.cache;version="[16.0,17)",
com.google.common.collect;version="[16.0,17)",
com.google.common.util.concurrent;version="[16.0,17)",
</pre>
</div></div>
<p>nothing about 'org.apache.curator.shaded' package</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Unfortunately, the committers don't know much about OSGi. We've always relied on contributors to maintain OSGi compatibility. So, please submit a PR with the fix.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amarkevich">amarkevich</a>:</i>
<p>Its hard to implement due to maven-shade-plugin <-> maven-bundle-plugin incompatibility; maven-shade-plugin works only on 'package' phase - same as maven-bundle-plugin.<br/>
Keep 2.11.1 as OSGi friendly with external Guava dependency.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bigmarvin" class="user-hover" rel="bigmarvin">Marvin Wu</a> This ended up getting merged by accident but it's really fine. My only question is whether or not "original" is the right classifier. I'd like to discuss alternatives. Is there a standard naming for alternate, non-shaded artifacts?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>My vote is to make the classifier <tt>osgi</tt> so that we're clear why it exists. Only OSGI users will use it AFAICT.</p>
