### ISSUE TITLE
[CURATOR-466] LeaderSelector gets in an inconsistent state when releasing resources.

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#986]
<p>I'm using the leader election recipe that works well until I encountered application shutdown.</p>

<p>here is my example:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
CuratorFramework framework = CuratorFrameworkFactory.builder()
    .connectString(<span class="code-quote">"localhost:2181"</span>)
    .retryPolicy(<span class="code-keyword">new</span> RetryOneTime(100))
    .build();

LeaderSelector leaderSelector = <span class="code-keyword">new</span> LeaderSelector(
    framework,
    <span class="code-quote">"/path"</span>,
    <span class="code-keyword">new</span> LeaderSelectorListener() {
<span class="code-keyword">volatile</span> <span class="code-object">boolean</span> stopped;
@Override
<span class="code-keyword">public</span> void takeLeadership(CuratorFramework client) <span class="code-keyword">throws</span> Exception {
    <span class="code-object">System</span>.out.println(<span class="code-quote">"I'm a <span class="code-keyword">new</span> leader!"</span>);
    <span class="code-keyword">try</span> {
<span class="code-keyword">while</span> (!<span class="code-object">Thread</span>.currentThread().isInterrupted() && !stopped) {
    TimeUnit.SECONDS.sleep(1);
}
    } <span class="code-keyword">finally</span> {
<span class="code-object">System</span>.out.println(<span class="code-quote">"I'm not a leader anymore.."</span>);
    }
}

@Override
<span class="code-keyword">public</span> void stateChanged(CuratorFramework client, ConnectionState     newState) {
    <span class="code-keyword">if</span> (client.getConnectionStateErrorPolicy().isErrorState(newState)) {
stopped = <span class="code-keyword">true</span>;
    }
 }
  }
);

framework.start();
leaderSelector.start();

TimeUnit.SECONDS.sleep(5);

leaderSelector.close();   <span class="code-comment">//(1)
</span>framework.close();<span class="code-comment">//(2)</span></pre>
</div></div>
<p> </p>

<p>When I release resources by calling close method first on the LeaderSelector instance and then on the CurtorFramework instance (lines 1 and 2) I always get the following exception:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
java.lang.IllegalStateException: instance must be started before calling <span class="code-keyword">this</span> method
at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[curator-client-4.0.1.jar:?]
at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:424) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:347) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240) [curator-recipes-4.0.1.jar:4.0.1]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_141]
</pre>
</div></div>
<p> </p>

<p>The reason for the exception is that the non-blocking LeaderSelector.close method delegates call to the internal executor service, which abruptly cancels the running futures with the interptIfRunning flag set to true. Right after this, the CuratorFramework close method is called. By the meantime, the future being canceled executes the finally block where it calls methods on the already closed CuratorFramework instance which leads to throwing an exception.</p>

<p>I thought I can wait a bit until the LeaderSelector instance is closed, so I tried to delay for some time before closing the CuratorFramework instance, but doing so leads to another exception:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
ava.lang.InterruptedException: <span class="code-keyword">null</span>
at java.lang.<span class="code-object">Object</span>.wait(Native Method) ~[?:1.8.0_141]
at java.lang.<span class="code-object">Object</span>.wait(<span class="code-object">Object</span>.java:502) ~[?:1.8.0_141]
at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1409) ~[zookeeper-3.4.12.jar:3.4.12--1]
at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:874) ~[zookeeper-3.4.12.jar:3.4.12--1]
at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:274) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:268) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64) ~[curator-client-4.0.1.jar:?]
at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100) ~[curator-client-4.0.1.jar:?]
at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:265) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:249) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:34) ~[curator-framework-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:347) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:124) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154) ~[curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246) [curator-recipes-4.0.1.jar:4.0.1]
at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240) [curator-recipes-4.0.1.jar:4.0.1]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748) [?:1.8.0_141]
</pre>
</div></div>
<p>At this time the exception is caused by the future being canceled with the interptIfRunning flag set to true in the LeaderSelector close method.</p>

<p>As the LeaderSelector implementation is based on the InterPorcessMutex that works with ephemeral nodes, do we really need to manually clean up on shutdown? As far as I know, the ephemeral nodes are deleted when the client disconnects.</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Mikhail Pryakhin" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.pryahin">m.pryahin</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-466" target="_blank">LeaderSelector gets in an inconsistent state when releasing resources.</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Not A Problem
<li><b>resolved</b>: 2018-11-13T15:53:39+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Calling {{leaderSelector.close() }}will cause the LeaderSelectorListener to get called in a separate thread. However, you are immediately closing the Curator handle after closing the leader selector therefore you're getting the error you're seeing. So, this is expected.</p>

<p> </p>
<blockquote><p>do we really need to manually clean up on shutdown? </p></blockquote>
<p>The reason for closing the leader selector is to immediately delete the ZNode so that any waiting leaders can become leader. If you don't close the leader selector you'd have to wait for the session to timeout. However, in the case above closing the Curator handle (assuming it succeeds) will close the ZK handle and thus end the session. So, it's really up to you how to handle cleanup. But, closing the Curator Handle will quickly delete any ephemeral ZNodes.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.pryahin">m.pryahin</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> Thank you. </p>

<p>Do I get you right that closing only a framework instance is a correct way for a client to give up participation in a leader election process?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Closing the Curator Handle closes the ZooKeeper Handle which closes the session on the server. Thus, any ephemeral nodes associated with that session would get deleted.</p>
