### ISSUE TITLE
[CURATOR-467] Avoid logging errors after curator framework is closed.

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#987]
<p>When the following operations are performed in rapid succession, it can lead annoying errors being logged.</p>

<ul>
	<li>Create curator framework</li>
	<li>Create leader latch</li>
	<li>Start leader latch</li>
	<li>Close leader latch</li>
	<li>Close curator framework</li>
</ul>

<p>The errors happen because background processing queued by the leader latch is still in flight when the curator framework is closed.  When these background ops try to access the closed curator framework the following exception happens.  It would be nice if the messages were logged at debug after close.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-06-01 17:35:52,095 [imps.CuratorFrameworkImpl] ERROR: Background exception was not retry-able or retry gave up
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:359)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.setNode(LeaderLatch.java:666)
	at org.apache.curator.framework.recipes.leader.LeaderLatch.access$300(LeaderLatch.java:64)
	at org.apache.curator.framework.recipes.leader.LeaderLatch$4.processResult(LeaderLatch.java:492)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522)
	at org.apache.curator.framework.imps.CreateBuilderImpl.sendBackgroundResponse(CreateBuilderImpl.java:584)
	at org.apache.curator.framework.imps.CreateBuilderImpl.access$900(CreateBuilderImpl.java:44)
	at org.apache.curator.framework.imps.CreateBuilderImpl$6.processResult(CreateBuilderImpl.java:534)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:607)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Keith Turner" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-467" target="_blank">Avoid logging errors after curator framework is closed.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>:</i>
<p>The error message <tt>instance must be started before calling this method</tt> in the exception above is misleading.  It implies that the instance was not yet started, however it was started and then stopped.  I opened <a href="https://issues.apache.org/jira/browse/CURATOR-448" title="Include curator framework state in error messages" class="issue-link" data-issue-key="CURATOR-448"><del>CURATOR-448</del></a> about this.</p>

**Comment by jira-importer** [comment]
<i>[Originally related to: <a href="https://github.com/apache/curator/issues?q=in%3Atitle%20CURATOR-469">CURATOR-469</a>]</i>
