### ISSUE TITLE
[CURATOR-468] Closing an active leader selector always logs spurious error

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#988]
<p>Closing a a leader selector seems to always log spurious error messages.  This only happens when it has assumed leadership because of <a href="https://issues.apache.org/jira/browse/CURATOR-337" title="LeaderSelector logs stack trace with "The leader threw an exception" message erroneously" class="issue-link" data-issue-key="CURATOR-337"><del>CURATOR-337</del></a>.  I think this spurious error logging highlights a conceptual problem with the code.   The primary reason that <a href="https://github.com/apache/curator/blob/ee5d65463b73abb2a2b732fb02729239b183519d/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java#L449" class="external-link" target="_blank" rel="nofollow noopener">LeaderSelector.java line 449</a> is executed is because the thread was interrupted.   Since the interrupt is set for the thread the call to release the mutex will never work, so its a bit of a catch-22.</p>

<p>Below is an example of the exception I am seeing.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-05-31 20:23:51,068 [leader.LeaderSelector] ERROR: The leader threw an exception
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1406)
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:871)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:250)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:244)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:241)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:225)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
	at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:339)
	at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:123)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</div></div>

<p>Below is an example of an exception I see when closing a leader selector and then closing the curator framework.</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2018-05-31 20:23:49,905 [leader.LeaderSelector] ERROR: The leader threw an exception
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.delete(CuratorFrameworkImpl.java:359)
	at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:339)
	at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:123)
	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:449)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:466)
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:65)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:246)
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:240)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="Keith Turner" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-468" target="_blank">Closing an active leader selector always logs spurious error</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2018-12-09T23:00:13+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpm1985">kpm1985</a>:</i>
<p>I can confirm this behavior. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cammckenzie">cammckenzie</a>:</i>
<p>Any suggestions for a fix? We can check if the thread is interrupted in the finally block and abort the clean up if it is. As you've said, the mutex won't get released if the thread is in an interrupted state anyway.</p>

<p>Alternatively, I guess we could clear the interrupted flag, clean up and then reset the flag, but I think that this is going to be more error prone.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kturner">kturner</a>:</i>
<blockquote><p>Alternatively, I guess we could clear the interrupted flag, clean up and then reset the flag, but I think that this is going to be more error prone.</p></blockquote>

<p>I am not completely sure about that approach either.  The code would look something like the following.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
    hasLeadership = <span class="code-keyword">false</span>;
    <span class="code-comment">// The following clears and returns the interrupt status.  One reason a 
</span>    <span class="code-comment">// thread may be here is because it was interrupted.  However the interrupt 
</span>    <span class="code-comment">// being set will cause releasing the mutex to fail, so clear the interrupt 
</span>    <span class="code-comment">// status.
</span>    <span class="code-object">boolean</span> wasInterruped = <span class="code-object">Thread</span>.currentThread().interrupted();
    <span class="code-keyword">try</span>
    {
mutex.release();
    }
    <span class="code-keyword">catch</span> ( Exception e )
    {
ThreadUtils.checkInterrupted(e);
log.error(<span class="code-quote">"The leader threw an exception"</span>, e);
<span class="code-comment">// ignore errors - <span class="code-keyword">this</span> is just a safety
</span>    } <span class="code-keyword">finally</span> {
      <span class="code-keyword">if</span>(wasInterruped) {
<span class="code-object">Thread</span>.currentThread().interrupt();
      }
    }
</pre>
</div></div>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user udaysagar2177 opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-468" title="Closing an active leader selector always logs spurious error" class="issue-link" data-issue-key="CURATOR-468"><del>CURATOR-468</del></a> release acquired leadership mutex properly</p>

<p>    This fixes <a href="https://issues.apache.org/jira/browse/CURATOR-468" class="external-link" rel="nofollow">https://issues.apache.org/jira/browse/CURATOR-468</a>. This PR is based on a solution suggested by cammckenzie & kturner on the jira issue.</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/udaysagar2177/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/udaysagar2177/curator</a> fixMutexRelease</p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/279.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #279</p>

<hr />
<p>commit e7c9ff7d7dddfa1e2c6c465d927afa14715061c4<br/>
Author: udaysagar2177 <uday@...><br/>
Date:   2018-09-18T19:24:58Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-468" title="Closing an active leader selector always logs spurious error" class="issue-link" data-issue-key="CURATOR-468"><del>CURATOR-468</del></a> release acquired leadership mutex properly</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279</a></p>

<p>    Can we get a test for this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279</a></p>

<p>    I have a test for this along with the fix. I'm going to close this in favor of what I have.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user Randgalt opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/285" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/285</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-468" title="Closing an active leader selector always logs spurious error" class="issue-link" data-issue-key="CURATOR-468"><del>CURATOR-468</del></a> LeaderSelector interruption causing spurious log messages, etc.</p>

<p>    Adds a test to what #279 had along with a slightly more complete fix. The finally clause of doWork() releases the mutex. In an interrupted situation this would always fail causing the failed delete manager to handle the work resulting in slightly slower deletions and spurious log messaged. This fixes this by clearing the thread interrupted state prior to releasing the mutex and then resetting afterwards if needed.</p>


<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-468" title="Closing an active leader selector always logs spurious error" class="issue-link" data-issue-key="CURATOR-468"><del>CURATOR-468</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/285.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/285.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #285</p>

<hr />
<p>commit 97e76919ae0056985aacc786d6c440fb779a6877<br/>
Author: randgalt <randgalt@...><br/>
Date:   2018-12-06T17:40:43Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-468" title="Closing an active leader selector always logs spurious error" class="issue-link" data-issue-key="CURATOR-468"><del>CURATOR-468</del></a></p>

<p>    Adds a test to what #279 had along with a slightly more complete fix. The finally clause of doWork() releases the mutex. In an interrupted situation this would always fail causing the failed delete manager to handle the work resulting in slightly slower deletions and spurious log messaged. This fixes this by clearing the thread interrupted state prior to releasing the mutex and then resetting afterwards if needed.</p>

<p>commit ddfcbc1e37fa9e8a9018f2c0d85b7f125efe173c<br/>
Author: randgalt <randgalt@...><br/>
Date:   2018-12-06T17:43:16Z</p>

<p>    Add a comment explaining</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user udaysagar2177 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/279</a></p>

<p>    @Randgalt Thank you!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user cammckenzie commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/285" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/285</a></p>

<p>    Looks ok to me.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/285" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/285</a></p>
